### ISSUE TITLE
WiFi card doesn't work with 5.19.0-7.1-liquorix-amd64 kernel

### ISSUE THREAD

**Issue by ignpaub** [damentz/liquorix-package#105]
Good afternoon:

I installed several months ago the kernel 5.19.0-7.1-liquorix-amd64 in ubuntu 18.04.6. However, I don't know how to enable the detection of the WiFi card (right know it says "No wifi adapter found"). Some more details about the system:

- lspci -> 0000:2e:00.0 Network controller: MEDIATEK Corp. MT7921 802.11ax PCI Express Wireless Network Adapter
- uname -r -> 5.19.0-7.1-liquorix-amd64

If I try to update the kernel, it says it is in the latest version, however it is not. If I search in https://launchpad.net/~damentz/+archive/ubuntu/liquorix, I can see there is 5.19.17 version. I don't know if this new version solves my problem, so that's why I'm asking.

- curl 'https://liquorix.net/add-liquorix-repo.sh' | sudo bash
- sudo add-apt-repository ppa:damentz/liquorix && sudo apt-get update
- sudo apt-get install linux-image-liquorix-amd64 linux-headers-liquorix-amd64

I hope to hear from you soon.

**Comment by damentz** [comment]
What distribution are you attempting to install from?  Output from `inxi -b` would be helpful here.

**Comment by ignpaub** [comment]
Good morning: 

I attach the output of the command.
``` 
(base) ignacio@ignacio-ROG-Zephyrus-S17-GX703HS-GX703HS:~$ inxi -b
System:    Host: ignacio-ROG-Zephyrus-S17-GX703HS-GX703HS Kernel: 5.19.0-7.1-liquorix-amd64 x86_64
           bits: 64
           Desktop: Gnome 3.28.4 Distro: Ubuntu 18.04.6 LTS
Machine:   Device: laptop System: ASUSTeK product: ROG Zephyrus S17 GX703HS_GX703HS v: 1.0 serial: N/A
           Mobo: ASUSTeK model: GX703HS v: 1.0 serial: N/A
           UEFI: American Megatrends LLC. v: GX703HS.311 date: 09/28/2021
Battery    BAT0: charge: 0.0 Wh condition: NA/NA Wh
           hidpp__0: charge: N/A condition: NA/NA Wh
           hidpp__1: charge: N/A condition: NA/NA Wh
CPU:       8 core 11th Gen Intel Core i9-11900H (-MT-MCP-)
           speed/max: 800/2501 MHz
Graphics:  Card-1: Intel TigerLake-H GT1 [UHD Graphics]
           Card-2: NVIDIA GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB]
           Display Server: x11 (X.Org 1.20.8 )
           drivers: fbdev (unloaded: modesetting,vesa)
           Resolution: 1920x1080@60.01hz, 1280x1024@60.02hz
           OpenGL: renderer: NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
           version: 4.6.0 NVIDIA 470.141.03
Network:   Card-1: Realtek RTL8111/8168/8411 PCIE Gigabit Ethernet Controller
           driver: r8169
           Card-2: MEDIATEK MT7921 802.11ax PCIE Wireless Network Adapter
           driver: mt7921e
Drives:    HDD Total Size: 1024.2GB (43.1% used)
Info:      Processes: 363 Uptime: 4:44 Memory: 3933.5/31785.5MB
           Client: Shell (bash) inxi: 2.3.56 
```
The thing is that I would like to install the wifi card in my current distribution (5.19.0-7.1-liquorix-amd64) as I have everything working there. Is it possible or I need to update?

Thanks a lot.

**Comment by Rongronggg9** [comment]
Bionic support has been dropped
https://github.com/damentz/liquorix-package/issues/110#issuecomment-1285306273

**Comment by ignpaub** [comment]
Okey, so I guess there is no help.
I'll search it in other place.

Thanks anyway.
