### ISSUE TITLE
5.19.0-14.3 error

### ISSUE THREAD

**Issue by r13s** [damentz/liquorix-package#107]
Hello.

When installing kernel 5.19-19.1~bullseye I get the following:
```
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-5.19.0-14.3-liquorix-amd64
find: ‘/var/tmp/mkinitramfs_DnVIG0/lib/modules/5.19.0-14.3-liquorix-amd64/kernel’: No such file or directory
```
After a reboot, the kernel does not boot.

LMDE 5, antiX 21

**Comment by damentz** [comment]
Did you run out of disk space?  We had another issue reported earlier that was similar but a different issue: [Out of memory error on anything above 5.19.0.11.1](https://techpatterns.com/forums/about2964.html).   The issue was resolved by publishing the version you're trying to run with compressed modules.

If you have any prior Liquorix kernels, the ramdisk may be unusually large and I recommend you purge them.

**Comment by r13s** [comment]
No, I don't think so, I have /boot inside the root partition as a directory, not as a separate partition. Free space in the root partition is about 900 GiB.

Compression in initramfs.conf is set to gzip, I also tried xz and zstd - it did not help.

Previous versions - at least 5.19.0-14.2 and 5.19.0-14.1 - with the same compression settings installed without errors.

There was a [similar error](https://unix.stackexchange.com/questions/696109/update-initramfs-does-not-fully-create-initrd-for-new-kernel) on Stack Exchange, maybe it's some kind of Debian bug?

**Comment by damentz** [comment]
Ah, it looks like you're right, Bullseye doesn't support ZSTD compressed kernels.  How bizarre since it seems like it shouldn't care.

I'll push out a new kernel using XZ instead and that should take care of the issue.

**Comment by r13s** [comment]
Thanks, 5.19-20.1~bullseye installed without issues.

By the way, following your advice, I installed Ananicy. Switched to cgroup v1 (right?) and found the following in the log:

```
ananicy[1435]: Load cgroup: /etc/ananicy.d/00-cgroups.cgroups
ananicy[1435]: File: /etc/ananicy.d/00-cgroups.cgroups, Line: 6, Error: [Errno 13] Permission denied: '/sys/fs/cgroup/cpu/cpu90/cpu.cfs_period_us'
ananicy[1435]: File: /etc/ananicy.d/00-cgroups.cgroups, Line: 7, Error: [Errno 13] Permission denied: '/sys/fs/cgroup/cpu/cpu80/cpu.cfs_period_us'
```

[Here](https://stackoverflow.com/questions/66597935/cant-find-cpu-cfs-period-us-and-cpu-cfs-quota-us-in-cgroup) it is advised to enable the [`CONFIG_FAIR_GROUP_SCHED=y`](https://www.kernel.org/doc/html/latest/scheduler/sched-design-CFS.html) option, which is not currently set. Do you think it's worth it and won't it break anything?

**Comment by damentz** [comment]
> Thanks, 5.19-20.1~bullseye installed without issues.
> 
> By the way, following your advice, I installed Ananicy. Switched to cgroup v1 (right?) and found the following in the log:
> 
> ```
> ananicy[1435]: Load cgroup: /etc/ananicy.d/00-cgroups.cgroups
> ananicy[1435]: File: /etc/ananicy.d/00-cgroups.cgroups, Line: 6, Error: [Errno 13] Permission denied: '/sys/fs/cgroup/cpu/cpu90/cpu.cfs_period_us'
> ananicy[1435]: File: /etc/ananicy.d/00-cgroups.cgroups, Line: 7, Error: [Errno 13] Permission denied: '/sys/fs/cgroup/cpu/cpu80/cpu.cfs_period_us'
> ```
> 
> [Here](https://stackoverflow.com/questions/66597935/cant-find-cpu-cfs-period-us-and-cpu-cfs-quota-us-in-cgroup) it is advised to enable the [`CONFIG_FAIR_GROUP_SCHED=y`](https://www.kernel.org/doc/html/latest/scheduler/sched-design-CFS.html) option, which is not currently set. Do you think it's worth it and won't it break anything?

You can remove the cgroups config, at least for the CPU.  PDS/BMQ (Project-C), does not implement all the files required for full cgroup support.  You can check these links below for more info:

1. https://github.com/damentz/liquorix-package/issues/82
2. https://gitlab.com/alfredchen/linux-prjc/-/issues/51

The author of Project-C is very busy though, so I doubt it'll get implemented any time soon.  No community members have stepped up to write stubs either.

**Comment by damentz** [comment]
Marking issue as resolved

**Comment by r13s** [comment]
Okay, thanks a lot.
