### ISSUE TITLE
Liquorix 4.18.12-2 fails to build due to Latex error

### ISSUE THREAD

**Issue by terencode** [damentz/liquorix-package#11]
Error log [here](https://pastebin.com/V2R4vS2r)

**Comment by damentz** [comment]
I'm not sure where you're getting that.  The Debian packages, including the Ubuntu PPA built successfully (and we're immediately available), and I just built the AUR linux-lqx update this morning.

If you're building Liquorix with any other package or system, you'll need to contact the maintainer for _that_ package, or figure it out yourself.

Also, there's no information for me to go off of besides output I've never seen before in a kernel build before, mine or others.

Closing for lack of information and only official packages are supported (Debian, PPA, and AUR)

**Comment by terencode** [comment]
Sorry for the lack of information, I'm using the AUR package with localmodcfg enabled.

**Comment by terencode** [comment]
This was due to my system not having texlive-latexextra. I'll ask the aur maintenair to include it into the makedepends.

**Comment by terencode** [comment]
Ok, can you provide a PKGBUILD for me to test? What to do for the build error?
