### ISSUE TITLE
How can i compile the Kernel from Source for Debian?

### ISSUE THREAD

**Issue by 0xIO32** [damentz/liquorix-package#111]
I would like to compile the Kernel from Source because i would like to apply a patch that brings back ashmem.

i already tested the script:
"scripts/make-debian-release.sh"

but had this error:

[INFO ] Using override process count, 6
[ERROR] No default key found in ~/.gnupg/gpg.conf or ~/.gnupg.options!  Cannot proceed with building bootstrap images.
[ERROR] No default key found in ~/.gnupg/gpg.conf or ~/.gnupg.options!  Cannot proceed with building bootstrap images.
[ERROR] No default key found in ~/.gnupg/gpg.conf or ~/.gnupg.options!  Cannot proceed with building bootstrap images.
[ERROR] No default key found in ~/.gnupg/gpg.conf or ~/.gnupg.options!  Cannot proceed with building bootstrap images.
[ERROR] No default key found in ~/.gnupg/gpg.conf or ~/.gnupg.options!  Cannot proceed with building bootstrap images.
[ERROR] No default key found in ~/.gnupg/gpg.conf or ~/.gnupg.options!  Cannot proceed with building bootstrap images.

**Comment by damentz** [comment]
The error is indicating that no default key is specified in the gnupg configuration, required for signing.  Those keys are stored in the local bootstrap images so follow-up commands that sign run successfully.

To build yourself, you effectively need to:

1. Build the bootstrap image used for building source packages: `scripts/debian/docker_bootstrap-image.sh amd64 ubuntu focal`
2. Build the bootstrap image for the target, Debian Bullseye for example: `scripts/debian/docker_bootstrap-image.sh amd64 debian bullseye`
3. Build the source package for aforementioned distribution: `scripts/debian/docker_build-source.sh debian bullseye`
4. And again for the final binary package: `scripts/debian/docker_build-binary.sh amd64 debian bullseye`

In the git cloned folder you'll see a folder named **artifacts**, and inside should be your debs.  Let me know if this helps.

**Comment by damentz** [comment]
Also a final note, this issue was brought up on the Zen Kernel issues page, ashmem was removed from mainline and isn't coming back.  The latest versions of Anbox and Waydroid _should_ work without it: https://github.com/zen-kernel/zen-kernel/issues/293
