### ISSUE TITLE
CONFIG_X86_X32: please reenable

### ISSUE THREAD

**Issue by svenha** [damentz/liquorix-package#112]
Sorry for speaking up so late (I was using other kernels and versions). x32 binaries can save a lot of CPU time (power) for link and GC intensive programs. In one of my examples from an SME, one saves 10 CPU core years out of 50 CPU core years. Please reenable `CONFIG_X86_X32`

**Comment by svenha** [comment]
A more conservative approach is Debian's approach. They configure:

    CONFIG_X86_X32=y
    CONFIG_X86_X32_DISABLED=y

So, they disable it per default (to reduce attack vector I guess), but every user can still run x32 binaries by adding a GRUB cmdline option:
  
    syscall.x32=y

**Comment by damentz** [comment]
Next release will enable CONFIG_X86_X32.
