### ISSUE TITLE
Liquorix &  Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64)

### ISSUE THREAD

**Issue by Iwhite67** [damentz/liquorix-package#117]
Hello, i just install a Ubuntu 22.04.1 LTS

```Err:6 https://liquorix.net/debian jammy Release
  404  Not Found [IP: 45.79.167.183 443]
Reading package lists... Done
E: The repository 'https://liquorix.net/debian jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```` 

Liquorix are not available on ubuntu 22.04 ?

**Comment by Rongronggg9** [comment]
https://github.com/damentz/liquorix-package/blob/11c8d75a3ce42c0654c33def1e3e5c30efb48cc5/scripts/install-liquorix.sh#L37-L49

**Comment by Iwhite67** [comment]
he return [INFO ] Distribution is debian

**Comment by Iwhite67** [comment]
https://github.com/damentz/liquorix-package/blob/11c8d75a3ce42c0654c33def1e3e5c30efb48cc5/scripts/install-liquorix.sh#L29

Return Debian

https://github.com/damentz/liquorix-package/blob/11c8d75a3ce42c0654c33def1e3e5c30efb48cc5/scripts/install-liquorix.sh#L31

Return Debian


i force Ubuntu into the variable, is good

can you check ?

**Comment by damentz** [comment]
It's turtles all the way down, Ubuntu thinks it's _like_ Debian, which is wrong.  I'll need to add a special heuristic that looks for Ubuntu anywhere and assumes it's that.

**Comment by Rongronggg9** [comment]
> Ubuntu thinks it's like Debian, which is wrong.

Though I have mysophobia on Ubuntu things, it is "appropriate" according to https://www.freedesktop.org/software/systemd/man/os-release.html 🤷🏻

> ID_LIKE=
>
> A space-separated list of operating system identifiers in the same syntax as the ID= setting. It should list identifiers of operating systems that are closely related to the local operating system in regards to packaging and programming interfaces, for example listing one or more OS identifiers the local OS is a derivative from. An OS should generally only list other OS identifiers it itself is a derivative of, and not any OSes that are derived from it, though symmetric relationships are possible. Build scripts and similar should check this variable if they need to identify the local operating system and the value of ID= is not recognized. Operating systems should be listed in order of how closely the local operating system relates to the listed ones, starting with the closest. This field is optional.
>
> Examples: for an operating system with "ID=centos", an assignment of "ID_LIKE="rhel fedora"" would be appropriate. For an operating system with "ID=ubuntu", an assignment of "ID_LIKE=debian" is appropriate.

**Comment by Rongronggg9** [comment]
>     dist="$(grep '^ID=' /etc/os-release | sed 's/ID=//' | head -1)" 
> Return Debian

Is your installation broken?

```console
$ docker run -it --rm ubuntu:jammy
root@604d98df872b:/# grep '^ID_LIKE=' /etc/os-release | sed 's/ID_LIKE=//' | head -1
debian
root@604d98df872b:/# grep '^ID=' /etc/os-release | sed 's/ID=//' | head -1
ubuntu
root@604d98df872b:/# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by damentz** [comment]
@Rongronggg9 yes you're correct, there's multiple ways to interpret ID_LIKE.  Check out the commit I just pushed here which I think will solve it: https://github.com/damentz/liquorix-package/commit/7ef68d94a1c98a04d1bad714fb89cb14411f4d29

Basically, find all distro instances and smash them into one string, then simply test in order of most likely to be on top to least likely to be based on anything.  This follows the logic that a core distribution may only reference itself, while a downstream distribution will list itself and everything that it's depending on (mint -> ubuntu -> debian for Ubuntu version, mint -> debian for Debian edition).

**Comment by damentz** [comment]
@Iwhite67 try running the script from the site again, it should be effectively a no-op since the kernel is already installed.

**Comment by Iwhite67** [comment]
i try after

**Comment by Rongronggg9** [comment]
> Check out the commit I just pushed here which I think will solve it: https://github.com/damentz/liquorix-package/commit/7ef68d94a1c98a04d1bad714fb89cb14411f4d29

Hmm, reading the manual more carefully, I found a minor problem. `ID_LIKE` may be `ID_LIKE="dist1 dist2"`, then `Possible distributions: dist0 "dist1 dist2"` is not so pleasing to the eye.

If you consider this a problem, may I rebase #118 and fix it?

**Comment by Iwhite67** [comment]
[INFO ] Possible distributions: ubuntu debian

[INFO ] Liquorix PPA repository added successfully

**Comment by damentz** [comment]
> > Check out the commit I just pushed here which I think will solve it: [7ef68d9](https://github.com/damentz/liquorix-package/commit/7ef68d94a1c98a04d1bad714fb89cb14411f4d29)
> 
> Hmm, reading the manual more carefully, I found a minor problem. `ID_LIKE` may be `ID_LIKE="dist1 dist2"`, then `Possible distributions: dist0 "dist1 dist2"` is not so pleasing to the eye.
> 
> If you consider this a problem, may I rebase #118 and fix it?

Hmm, this might be as simple as:
```
dists="${dists//'"'}" # remove double quotes
dists="${dists//"'''"}" # remove single quotes
```

**Comment by Rongronggg9** [comment]
Simpler as:

```sh
sed "s/['\"]//g"
```

**Comment by damentz** [comment]
Ah good point, sed would have worked better.  I took it one step further though and just used `tr` to strip things that are unwanted in the output.  Looks cleaner too since the character classes have full names like **lower** and **space**.
