### ISSUE TITLE
Cannot enable amd-pstate

### ISSUE THREAD

**Issue by RAMChYLD** [damentz/liquorix-package#119]
Hi,

I am using an AMD Ryzen 9 3950X CPU on a X570 mobo. I cannot enable amd-pstate on the liquorix kernel. It was working at some point but seem to have stopped again lately. 

`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver`
`cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver: No such file or directory`

`cpupower frequencty-info`
`no or unknown cpufreq driver is active on this CPU`

I have the initcall_blacklist=acpi_cpufreq_init set in the grub config and since this is a Zen2 CPU, I also have amd_pstate.shared_mem=1 set. And to be sure, I have amd_pstate listed in /etc/modules-load.d/modules.conf

amd-pstate is working on the stock Ubuntu kernels. 

`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver`
`amd-pstate`

`cpupower frequency-info`
`driver: amd-pstate`

Please advise, thanks.

**Comment by damentz** [comment]
That probably means that 6.1 broke support for AMD P-State.  You'd have to share your kernel log to see if there's anything interesting.

**Comment by RAMChYLD** [comment]
Understood. Here's the log: https://pastebin.com/GPqRia5W

**Comment by damentz** [comment]
You'll need to boot with debug logging enabled.  The pstate driver does emit a ton of logs but they're all behind debug mode.  Try adding **loglevel=7** to your boot parameters.

You can look at this function for all the logs it can possibly emit: https://github.com/zen-kernel/zen-kernel/blob/6.1/main/drivers/cpufreq/amd-pstate.c#L619

Also, it looks like your amd_pstate kernel boot params can be removed.  They've all been deprecated and/or removed.  The only parameters supported are **disable** and **passive**: https://github.com/zen-kernel/zen-kernel/blob/6.1/main/drivers/cpufreq/amd-pstate.c#L619

```c
static int __init amd_pstate_param(char *str)
{
	if (!str)
		return -EINVAL;

	if (!strcmp(str, "disable")) {
		cppc_load = 0;
		pr_info("driver is explicitly disabled\n");
	} else if (!strcmp(str, "passive"))
		cppc_load = 1;

	return 0;
}
```

EDIT: It just occurred to me that **loglevel=7** won't help here, that's just for the terminal output while booting.  The actual kernel log contains everything.  The fact there's no output for amd_pstate means your system may not be compatible with it.  Your BIOS must have CPPC support for it to turn on (and also be AMD), so the fact that there's no initialization output must mean you're missing that support.

**Comment by RAMChYLD** [comment]
Thanks for the hint! 

After a lot of faffing around, I managed to make it work by adding amd_pstate=passive to the boot parameters. Don't know why the CPU is not being autodetected. Wonder if it has something to do with Zen2 CPUs not fully supporting CPPC.

**Comment by damentz** [comment]
Yep, that might be it.  Also it's odd but all the documentation leads to adding **amd_pstate=passive** as turning on the driver.  It makes no mention of behaving like the passive mode of **intel_pstate** where incompatible CPUs can use it.

Either way, looks like you figured it out so I'll close this issue.
