### ISSUE TITLE
AMD GPU Polaris11 k mc fails to load firmware

### ISSUE THREAD

**Issue by slrslr** [damentz/liquorix-package#12]
Hello,

maybe it is several weeks i have last used Liquorix kernel instead of default one that comes with Debian based MX Linux 17.1.

I recently seen Liquorix kernel update and so i tried to boot into Liquorix kernel 4.19.0.14 and 0.16 (and also 4.20.0-3.1+systemd)
(systemd also non systemd) today and it do not boot into graphical mode which is XFCE4 4.12.3
instead i seen text login prompt and after Ctrl+Alt+Del an polaris errors similar to ones on the image.

Graphics:
  Device-1: AMD Baffin [Radeon RX 460/560D / Pro 
  450/455/460/555/555X/560/560X] 
  vendor: Sapphire Limited driver: amdgpu v: kernel bus ID: 01:00.0 
  Display: x11 server: X.Org 1.19.2 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Radeon RX 560 Series (POLARIS11 DRM 3.23.0 
  4.15.0-1-amd64 LLVM 7.0.0) 
  v: 4.5 Mesa 18.2.6 direct render: Yes 

![polaris11-fails-liquorix](https://user-images.githubusercontent.com/6596726/51499375-53eab200-1dca-11e9-9512-f8644c463491.jpg)

Note that before a few weeks when i last used Liquorix on this very same machine, it worked. And MX Linux default kernel also works, but not Liquorix (above mentioned version)

---
Also seen an error during "apt dist-upgrade":
Setting up linux-headers-4.20.0-3.1-liquorix-amd64 (4.20-1.1~sid) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.20.0-3.1-liquorix-amd64
Warning: Unable to find an initial ram disk that I know how to handle.
Will not try to make an initrd.
Error! Bad return status for module build on kernel: 4.20.0-3.1-liquorix-amd64 (x86_64)
Consult /var/lib/dkms/virtualbox-guest/5.2.22/build/make.log for more information.
Setting up linux-headers-liquorix-amd64 (4.20-1.1~sid) ...

**Comment by damentz** [comment]
What version of Linux did you jump from on MX Linux 17.1?  I suspect you'll need to manually add/replace the latest firmware here: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu

For your VirtualBox package, the latest 5.2 version is 5.2.26, and 6.0.4 is the latest major version.  You'll need to poke your package maintainer to update VirtualBox to the latest upstream or use Oracle's binary packages.

Remember, newer kernels require updated firmware and out-of-tree kernel modules (vboxsvc, nvidia, etc).  As soon as you're willing to run the latest Liquorix, you need to be prepared to update these things independently from your distribution's repository if you're running a frozen distribution.
