### ISSUE TITLE
mpv drops frames on liquorix kernel when laptop is running on battery

### ISSUE THREAD

**Issue by EmadGhazal** [damentz/liquorix-package#121]
Basically the title. It otherwise works perfectly fine when laptop is connected to power. I'm running v6.1.8-4 on debian sid. Stock kernel drops zero frames when laptop is running on battery, so it's definitely a liquorix problem. Would appreciate any help.

**Comment by damentz** [comment]
There's not enough information for me to go on here and you're basically asking for tech support.  I recommend you look at the cpufreq governor that Debian is setting, or your desktop, and modify it to not drastically reduce your CPU frequency.

Closing.

**Comment by EmadGhazal** [comment]
The cpu governor is already set to performance on all 20 processor cores, so there shouldn't be any reduction in cpu frequency. It's also not like frames are dropping all of the time. A video would play fine for some time, then eight or so frames would drop, and then the video would return to playing fine, and this process would keep repeating.

I'd be glad to offer you with any more information to help diagnose the problem. Just let me know.

Appreciate your help thus far.

**Comment by damentz** [comment]
Ok, to confirm, please provide the output of **inxi -b** so we have a better understanding of what your system is.

Also, run these two commands when on AC and then on battery while playing back video with mpv:
1. `sudo cpupower frequency-info`
2. `grep 'MHz' /proc/cpuinfo | sort`

**Comment by EmadGhazal** [comment]
`# inxi -b`
> System:
  Host: Kernel: 6.1.8-4-liquorix-amd64 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.26.90 Distro: Debian GNU/Linux bookworm/sid
Machine:
  Type: Laptop System: HUAWEI product: RLEF-XX v: M1010
    serial:
  Mobo: HUAWEI model: RLEF-XX-PCB v: M1010 serial:
    UEFI: HUAWEI v: 1.24 date: 11/08/2022
Battery:
  ID-1: BAT0 charge: 49.7 Wh (85.7%) condition: 58.0/59.4 Wh (97.6%)
CPU:
  Info: 14-core (6-mt/8-st) 12th Gen Intel Core i7-12700H [MST AMCP]
    speed (MHz): avg: 2638 min/max: 400/4600:4700:3500
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics driver: i915 v: kernel
  Device-2: Quanta FHD Camera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.6 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: iris gpu: i915 resolution: 1920x1200~60Hz
  API: OpenGL Message: Unable to show GL data. Required tool glxinfo
    missing.
Network:
  Device-1: Intel Alder Lake-P PCH CNVi WiFi driver: iwlwifi
Drives:
  Local Storage: total: 476.94 GiB used: 147.79 GiB (31.0%)
Info:
  Processes: 381 Uptime: 0m Memory: 15.35 GiB used: 1.71 GiB (11.1%)
  Shell: Sudo inxi: 3.3.24

**Comment by EmadGhazal** [comment]
On AC power:

`# cpupower frequency-info`

> analyzing CPU 0:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 400 MHz - 4.60 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 400 MHz and 4.60 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 4.40 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes

**Comment by EmadGhazal** [comment]
On AC power:

`# grep 'MHz' /proc/cpuinfo | sort`
> cpu MHz         : 1170.156
cpu MHz         : 1646.904
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 3163.980
cpu MHz         : 3608.438
cpu MHz         : 4320.931
cpu MHz         : 452.912
cpu MHz         : 551.672

**Comment by EmadGhazal** [comment]
On battery:

`# cpupower frequency-info`
> analyzing CPU 0:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 400 MHz - 4.60 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 400 MHz and 4.60 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 2.06 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes

**Comment by EmadGhazal** [comment]
On battery:

`# grep 'MHz' /proc/cpuinfo | sort`
> cpu MHz         : 1346.103
cpu MHz         : 1964.376
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 2700.000
cpu MHz         : 3596.484
cpu MHz         : 4106.111
cpu MHz         : 424.933

**Comment by damentz** [comment]
Oh I see, you're running a 12th gen Intel CPU with low power cores.  When you switch to battery the BIOS/EFI must be putting your system into a lower power state and PDS is scheduling work on your E cores.

Can you disable the E cores through your BIOS and confirm if that's the issues?  PDS has no logic to know whether it's on an E or P core, so you'll get unpredictable and random performance until they're disabled.

**Comment by damentz** [comment]
Also, it looks like you need to implement a cpufreq daemon.  Ironically, without configuring one, it appears that your laptop could be running out of power budget by running in performance mode, causing frame drops as the VRM tries to stay within its power envelope for battery mode.  By using TLP, you can switch to ondemand (acpi-cpufreq) or powersave (intel-pstate), when on battery.

And last, try passing **intel_pstate=disable** through your kernel boot parameters.  Liquorix is known to behave very badly with intel_pstate and is supposed to be disabled by default.  Some how you're running this governor, which is contributing to your performance issues.

**Comment by EmadGhazal** [comment]
> And last, try passing intel_pstate=disable through your kernel boot parameters. Liquorix is known to behave very badly with intel_pstate and is supposed to be disabled by default. Some how you're running this governor, which is contributing to your performance issues.

Great to know. I've already noticed that the liquorix kernel disables the intel_pstate driver by default, but decided to override that behavior since the consensus is that the pstate driver is best for intel platforms. Guess that that does not take into account patched kernels such as liquorix. Not that I've noticed any difference in performance or battery life anyway.

> Can you disable the E cores through your BIOS and confirm if that's the issues? PDS has no logic to know whether it's on an E or P core, so you'll get unpredictable and random performance until they're disabled.

Can't do that unfortunately. The firmware is overall very awful. Wish I had taken that into account before buying this laptop. Great information about the scheduler though. Wish that that was documented somewhere. Also, is it possible that the vanilla CFS has logic to handle P and E cores differently and that that's the reason I'm not facing this problem with the vanilla kernel?

> Also, it looks like you need to implement a cpufreq daemon. Ironically, without configuring one, it appears that your laptop could be running out of power budget by running in performance mode, causing frame drops as the VRM tries to stay within its power envelope for battery mode. By using TLP, you can switch to ondemand (acpi-cpufreq) or powersave (intel-pstate), when on battery.

I considered that at some point, and even attempted to install auto-cpufreq, but then decided to let intel_pstate do its hardware magic to manage power, especially since performance and battery life has been satisfactory thus far, and the only reasons I'm using liquorix is for its OOM patches and the fact that it's actively maintened.

Thank you very much Steven for your very informative insights and help thus far. That the PDS can't differentiate between P and E cores (which the laptop's firmware activates when running on battery) is a completely satisfactory explanation for the dropped frames in mpv while running on battery, especially since this behavior is indeed exacerbated when running HEVC-compressed videos, which require more processing power. Too bad nothing can be done about it.

**Comment by damentz** [comment]
One option you have is to disable the E cores manually.  In **/sys/devices/system/cpu**, you want to identify the E cores and echo **0** to the **online** file of each.  You could probably write a bash script tailored for your system to perform this action.

Maybe useful for reference, I also wrote a tool in perl to disable SMT cores.  Could be useful to verify online/offline configuration: https://github.com/damentz/smt-manager

Will mark this as closed since big.LITTLE or BIG.little isn't something Project-C has any code to handle today.

**Comment by EmadGhazal** [comment]
Will definitely try that. Appreciate your help and support.
