### ISSUE TITLE
Version 6.1.12-1 regressed a "ramdisk out-of-memory" issue

### ISSUE THREAD

**Issue by nickdnk** [damentz/liquorix-package#122]
Hello

I have reported this issue before, but using the forum. I would prefer GitHub, so here I am.

Essentially, https://techpatterns.com/forums/about2964.html has come back after updating 6.1.11-1 to 6.1.12-1.

The symptoms appear to be identical. Let me know what information I should provide. It's the same machine, so the reports from the post should be good to use.

**Comment by damentz** [comment]
In the original post you never identified your distribution or version.  Please post the output of `inxi -S` and/or `lsb_release -a`.

But aside from that, googling the error you had, it appears this is actively being worked on by Canonical here: https://bugs.launchpad.net/oem-priority/+bug/1842320

Not sure if you're on Ubuntu, Arch, or Debian, but you need a new version of grub.  Old versions appear to now be incompatible with Liquorix.

If you want a workaround now, it seems that these settings in **initramfs.conf** will give you the best chance of booting:
```
MODULES=dep
COMPRESS=xz
RUNSIZE=25%
```

You can also pass the runsize of initramfs through kernel boot parameters, like `initramfs.runsize=1000000000` (that's 1 gigabyte in bytes).

**Comment by nickdnk** [comment]
Thanks for the help. I will look into my options here.

**Comment by nickdnk** [comment]
Also this is Ubuntu 20.04.

**Comment by nickdnk** [comment]
I changed nothing (because I haven't had time to look into it, so I just ran `6.1.11-1`), but `6.1.15-2` just installed on its own during a regular update and booted up fine. Closing.
