### ISSUE TITLE
ubuntu builds are not updated?

### ISSUE THREAD

**Issue by serialpotato** [damentz/liquorix-package#123]
Hi. I am unable to see the new ubuntu builds. The last one is 6.1-27. Would you please update them as well?

https://launchpad.net/~damentz/+archive/ubuntu/liquorix

**Comment by damentz** [comment]
Thanks for reporting, looks like new kernels are no longer building because I've used all my storage quota.

Once I get a moment I'll try to clear out the storage and submit a new build.

**Comment by damentz** [comment]
New builds are underway through the Launchpad PPA and will be available in about 2 hours.

**Comment by serialpotato** [comment]
This has happened again. Latest built is not on launchpad

**Comment by damentz** [comment]
Yes, that's correct.  I didn't launch the Debian/Ubuntu builds since I was first testing on Arch.  Also was busy so didn't get around to running them yesterday.

You should see new builds in a few hours.
