### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by Darth-Vader2008** [damentz/liquorix-package#129]
Hi, I'm Future Flash and a big fan of your liquorix kernel but in 6.14 lqx there's an issue I don't know why it's happening to me but I'm working on my laptop at that time it crashes and says that there's an error on /dev/sdb1. So, please fix it with a new Liquorix kernel 6.3.

**Comment by damentz** [comment]
Hi @Future-Flash, it sounds one of your disks is having a hardware issue, or you have some type of filesystem corruption.  Considering the issues for Liquorix aren't tech support, I'll close this out.

If you need more help I'd recommend finding a forum to ask for help for your distribution or a general Linux advice site.  For example if you were running Arch: https://bbs.archlinux.org/
