### ISSUE TITLE
How to install archieved kernel

### ISSUE THREAD

**Issue by ignpaub** [damentz/liquorix-package#131]
Good morning:

I need to install 5.19.0-7.1-liquorix-amd64 on a Dockerfile so as to complete my project. 

The thing is that I found the 5.19-7 archieved version, but I do not know how to install it on my computer. 

Could you provide me some instructions to install this old version of kernel? 
Using the .zip of 5.19-7 will install the 5.19.0-7.1-liquorix-amd64 kernel?

Thanks a lot.

**Comment by damentz** [comment]
What zip file are you referring to?  The only supported method of installing Liquorix comes from the install script on the website: `curl -s 'https://liquorix.net/install-liquorix.sh' | sudo bash`.

Also, versions older than the latest are not supported in any way as I don't run them nor keep archives of them for later download.  I recommend you install the latest kernel as part of your project.
