### ISSUE TITLE
Difference bewteen bookworm, bullseye and sid

### ISSUE THREAD

**Issue by ignpaub** [damentz/liquorix-package#133]
Good morning:

I am trying to install from https://liquorix.net/debian/pool/main/l/linux-liquorix/ the 6.3.2-1 version of this kernel. However, I find you have 3 different versions named bookworm, bullseye and sid. Which one should I install to use liquorix kernel?

Thanks a lot.

Ignacio

**Comment by nayan1255** [comment]
Check the OS Flavour by command

cat /etc/os-release

then pick from the version which is mention in os-release

1) Bullseye
2) Bookworm
3) Sid

Basic if we a working/development on linux kernel then Select Sid (Unstable)

Warning : If you do not knowledge about kenel version please not select Sid Version

**Comment by Rongronggg9** [comment]
A notable difference: the toolchain used to build them is the one the release provides, so it differs. If you install a kernel built for Bullseye on Debian Bookworm, some kmod (kernel module) may refuse to build. In such a case, the kernel is built with GCC 10.2.1 as it is the default GCC version of Bullseye, but the one of Bookworm is 12.2.0. These kmod pre-check if the toolchain used to build the kernel is the same as the current default. Note that even though not every kmod checks this, mixing toolchain between kernel and kmod is not a good idea.

**Comment by nayan1255** [comment]
If you build the kernel for Bullseye then use Bullesye OS to build the kernel

If you build the kernel for Bookworm then use Bookworm OS to build the kernel

Mixed Toolchain can decrease the module compatibility

Also check the .config file

**Comment by damentz** [comment]
The only recommended way to install binaries for Liquorix is through the install script on the homepage.  It automatically selects the correct branch, adds correct sources list file, and installs packages.

As for which one to install manually, I think you are just asking how Debian and/or Linux works.  Basically, install the package for the distro version you are running...

Closing since this is just a support request unrelated to Liquorix itself.

**Comment by ignpaub** [comment]
> Check the OS Flavour by command
> 
> cat /etc/os-release
> 
> then pick from the version which is mention in os-release
> 
> 1. Bullseye
> 
> 2. Bookworm
> 
> 3. Sid
> 
> 
> Basic if we a working/development on linux kernel then Select Sid (Unstable)
> 
> Warning : If you do not knowledge about kenel version please not select Sid Version

The output of that command is the following:

```
ignacio@ignacio-ROG-Zephyrus-S17-GX703HS:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

So, if we do not consider SID, which one is better, bookworm or bullseye and why?

Thanks a lot.

Ignacio

**Comment by ignpaub** [comment]
> The only recommended way to install binaries for Liquorix is through the install script on the homepage. It automatically selects the correct branch, adds correct sources list file, and installs packages.
> 
> As for which one to install manually, I think you are just asking how Debian and/or Linux works. Basically, install the package for the distro version you are running...
> 
> Closing since this is just a support request unrelated to Liquorix itself.

I am not an expert in Ubuntu, kernels or related. But as far as I understand it, it is a doubt regarding your product. I recommend you to be more open-minded with the doubts since you always close my questions.

I can not install the latest version since I have to continue some projects in a newer os version using dockers. I had to install manually many different packages, so changing the version is not something inside the plans.

**Comment by damentz** [comment]
I understand you're not an expert with Ubuntu, but Liquorix is an intermediate/enthusiast project, which requires that you have more general Linux experience for when you run into problems.  With that said, the questions you're asking come off as things that are better asked in general support forum, not this project.

As for your previous issue here, https://github.com/damentz/liquorix-package/issues/131, I reviewed the documentation on this project for building a kernel on your own system and made some adjustments to account for common issues (gpg configuration, package signing).  You can try giving it a shot to build the version that you need.

But just understand, it's expected that when you run into issues, you follow the general guideline of "help me, help you".  As in, do as much troubleshooting and researching on your end before asking questions that can be answered by a simple web search.  If that fails, then there probably is something not obvious and the issue you're thinking of posting probably has merit.

**Comment by smxi** [comment]
ignpaub, it's not a project's responsibility to teach you how Linux distributions work. Try learning more on your own before posting such elementary questions that have nothing to do with the project.

> I am not an expert in Ubuntu, kernels or related. But as far as I understand it, it is a doubt regarding your product. I recommend you to be more open-minded with the doubts since you always close my questions.

 If you have an issue with Liquorix that is valid, then there's no problem, but you are asking how to use Ubuntu or Debian, which is your job to learn, and that is probably why your issues keep getting closed. 

You don't have to be an 'expert'' to understand how gnu/linux operating systems and distributions work, but if you are going to be using them at beyond a beginner level, you have to start learning how your tools work, that's how software development works, sorry to break it to you.

There is no 'doubt' about this product, it's simply your failure to learn what you need to learn to use your tools adequately. This has nothing to do with being 'open minded', and everything to do with not doing people's work for them when they clearly have no interest in doing it for themselves. The sooner you learn this basic reality, the sooner you will begin to have positive experiences posting issues, which also includes knowing when it's time for you to learn what you need to learn before asking anything.

LIquorix is intended for users who are capable of this basic level of understanding, so may simply not be the right kernel for your needs.

> I can not install the latest version since I have to continue some projects in a newer os version using dockers. I had to install manually many different packages, so changing the version is not something inside the plans.

Again, please do not confuse your own technical problems with another software project, this is why your issues are not being handled the way you want, and the sooner you learn this difference, the sooner you will first, stop posting issues not related to the project in question in any real way. It is not a liquorix issue that you have issues with your own installs, and don't want to spend the time to learn how Debian or Ubuntu work in terms of branches, releases, etc, nor  is it a Liquorix issue that 'changing the viersion is not something inside the plans'. Those plans have nothing to do with any other project, and you should learn how to understand why this is.

**Comment by ignpaub** [comment]
> I understand you're not an expert with Ubuntu, but Liquorix is an intermediate/enthusiast project, which requires that you have more general Linux experience for when you run into problems. With that said, the questions you're asking come off as things that are better asked in general support forum, not this project.
> 
> As for your previous issue here, #131, I reviewed the documentation on this project for building a kernel on your own system and made some adjustments to account for common issues (gpg configuration, package signing). You can try giving it a shot to build the version that you need.
> 
> But just understand, it's expected that when you run into issues, you follow the general guideline of "help me, help you". As in, do as much troubleshooting and researching on your end before asking questions that can be answered by a simple web search. If that fails, then there probably is something not obvious and the issue you're thinking of posting probably has merit.

Hi!

I’m more onto Ubuntu. I know there are other platforms but I have never worked with them. After a search I understood the names I asked initially are Debian releases and the correspondent to Ubuntu 22.04 Jammy is the bookworm one.

I will leave this link so if anyone in the future is in the same situation as I was know what to do: https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on

I mainly use it to install the NVIDIA RTX 3080 so as to install other programs in order to develop neural networks and more efficient algorithms. That is the reason behind searching for a concrete version.

Thanks a lot.

Ignacio

**Comment by ignpaub** [comment]
> ignpaub, it's not a project's responsibility to teach you how Linux distributions work. Try learning more on your own before posting such elementary questions that have nothing to do with the project.
> 
> > I am not an expert in Ubuntu, kernels or related. But as far as I understand it, it is a doubt regarding your product. I recommend you to be more open-minded with the doubts since you always close my questions.
> 
> If you have an issue with Liquorix that is valid, then there's no problem, but you are asking how to use Ubuntu or Debian, which is your job to learn, and that is probably why your issues keep getting closed.
> 
> You don't have to be an 'expert'' to understand how gnu/linux operating systems and distributions work, but if you are going to be using them at beyond a beginner level, you have to start learning how your tools work, that's how software development works, sorry to break it to you.
> 
> There is no 'doubt' about this product, it's simply your failure to learn what you need to learn to use your tools adequately. This has nothing to do with being 'open minded', and everything to do with not doing people's work for them when they clearly have no interest in doing it for themselves. The sooner you learn this basic reality, the sooner you will begin to have positive experiences posting issues, which also includes knowing when it's time for you to learn what you need to learn before asking anything.
> 
> LIquorix is intended for users who are capable of this basic level of understanding, so may simply not be the right kernel for your needs.
> 
> > I can not install the latest version since I have to continue some projects in a newer os version using dockers. I had to install manually many different packages, so changing the version is not something inside the plans.
> 
> Again, please do not confuse your own technical problems with another software project, this is why your issues are not being handled the way you want, and the sooner you learn this difference, the sooner you will first, stop posting issues not related to the project in question in any real way. It is not a liquorix issue that you have issues with your own installs, and don't want to spend the time to learn how Debian or Ubuntu work in terms of branches, releases, etc, nor is it a Liquorix issue that 'changing the viersion is not something inside the plans'. Those plans have nothing to do with any other project, and you should learn how to understand why this is.

I guess you are an expert in all of these topics. But normal people have a diferent learning curve or speciality field.

I’m a robotic engineer and when somebody asks me any doubt, no matter how silly it is, I try to help them. Because I also was there at some point. 

Questioning the things we do not understand is the way of moving forward and your comment will not make me change.

If you did not have the intention of helping me just skip the question. Not everybody knows everything as you do.

**Comment by smxi** [comment]
You missed the point of my answer, it is not up to  other people to learn for you, it is up to you. I am still helping you, by explaining the basic rules of what is required to get help, and what is expected, but you are not helping yourself here at all by pretending that is not something you should have to do.

This is how tech works, you should know this since you are working with it.

You did not actually ask a question in any real sense, it was below the level where what you were typing had meaning that related to the liquorix kernel.

There's a difference between beginner, intermediate, and advanced users. I try to never post a question unless I have exhausted all research avenues and simply cannot find the solution, that's the difference between being a consumer and a producer of solutions in tech. 

I'm actually surprised you find this strange or unusual, this is so standard in all technical areas I have ever been involved with that it's not something I would think needs to be explained at all to anyone with any experience in tech whatsoever.

When the main question would only take about 5 minutes to google and get a basic understanding and you don't want to spend that time, then that makes you look very bad, and generally will significantly reduce anyone's willingness to help you, and if you then respond with more attempts to justify this, it reduces that willingness even further. This may be a valuable lesson for you to learn before you go  any further in your tech career.

**Comment by damentz** [comment]
Locking issue, the original question was answered and reasons for why we're unhappy with the point of the issue was made very clear.
