### ISSUE TITLE
liquorix.net invalid certificate

### ISSUE THREAD

**Issue by vejeta** [damentz/liquorix-package#135]
Since today (1st of August 2023) when trying to update the Debian repositories, or to access the https://liquorix.net site, it results in:

```
W: https://liquorix.net/debian/dists/trixie/InRelease  Certificate verification failed: 
The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake
```

**Comment by damentz** [comment]
Can you try again?  The website is now behind Cloudflare, but if you try to still use the origin server you'll get a certificate error.

EDIT:  When running `dig`, you should see the following:

```
$ dig +short liquorix.net
104.21.76.5
172.67.184.200
```

**Comment by damentz** [comment]
Marking as resolved since this is just a DNS cache issue.

**Comment by vejeta** [comment]
yes, it is solved. Thanks for the update!
