### ISSUE TITLE
404 errors from CDN

### ISSUE THREAD

**Issue by toupeira** [damentz/liquorix-package#137]
I'm getting 404 errors when trying to update the `linux-image-liquorix-amd64` package to the latest version `6.4-9.1~sid`.

https://liquorix.net/debian/pool/main/l/linux-liquorix/ does list the file https://liquorix.net/debian/pool/main/l/linux-liquorix/linux-image-liquorix-amd64_6.4-9.1~sid_amd64.deb, but accessing that URL shows this error from the CDN:

> Error 404
> This object could not be viewed
> 
> You are not authorized to view this object
> 
> This object does not exist or is not publicly accessible at this URL. Check the URL of the object that you're looking for or contact the owner to enable Public access.
> 
> Is this your bucket?
> 
> Learn how to enable [Public Access](https://developers.cloudflare.com/r2/data-access/public-buckets/)

![image](https://github.com/damentz/liquorix-package/assets/6501/4e9d7289-7a7e-43f6-96ff-8d9e793e320c)

**Comment by damentz** [comment]
Sorry about that, need to tune the sync scripts so they fire correctly.  Should be working now.

**Comment by toupeira** [comment]
Indeed it does, thanks for the quick response! :heart:
