### ISSUE TITLE
Unable to run Docker due to missing CONFIG_CGROUP_CPUACCT

### ISSUE THREAD

**Issue by BCMM** [damentz/liquorix-package#14]
I'm using `5.0.0-9.1-liquorix-amd64` with Debian Sid, and I see the following error when I try to run any Docker container: 

    $ docker run hello-world
    docker: Error response from daemon: unable to find "cpuacct" in controller set: unknown.
    ERRO[0000] error waiting for container: context canceled

According to [this script](https://github.com/moby/moby/blob/master/contrib/check-config.sh), the only change required to run Docker on Liquorix kernels is `CONFIG_CGROUP_CPUACCT=y`. Would it be feasible to add that to future versions?

**Comment by damentz** [comment]
Hi @BCMM, this is actually a known bug that was exposed by systemd v240: https://github.com/docker/for-linux/issues/545

Looking at Debian's packages, the maintainer last updated _containerd_ January 2017 with version `0.2.3+git20170126.85.aa8187d`.  You need at least version _1.2.5_ to run containers with MuQSS without the unknown controller set bug.

You have two options, bug the maintainer in Debian to update the containerd and docker packages to latest upstream, or install the docker packages from docker.io directly.

In my opinion, Docker is a relatively popular container tool (I also use it to make kernel builds), so the fact that containerd is 2 and a half years old in Debian Sid means the maintainer lost interest in updating it and probably doesn't respond to feedback positively.  This means your own realistic option is to use the packages provided by docker.io.  If they don't package for Debian Sid, you may need to switch to a different distribution to get proper support.

**Comment by BCMM** [comment]
Ah, it's working now with the packages from docker.io. Sorry about that!

**Comment by ciaby** [comment]
@damentz 
Hi, I'm having a similar problem with kubelet/kubernetes. It won't start without cpuacct subsystem mounted in /sys/fs/cgroup/cpuacct. Obviously I can't mount it because it's not compiled in the kernel...
Is it too much work to include CONFIG_CGROUP_CPUACCT=y in the kernel config? :)

**Comment by damentz** [comment]
Your system should have a symlink from cpuacct to cpu under /sys/fs/cgroup.  The reason why is that MuQSS does not support the CPU accounting controller:

```
config CGROUP_CPUACCT
    bool "Simple CPU accounting controller"
    depends on !SCHED_MUQSS
    help
      Provides a simple controller for monitoring the
      total CPU consumed by the tasks in a cgroup.
```

Have you tried using **[minikube](https://minikube.sigs.k8s.io/docs/)**?  It's designed to configure a local kubernetes installation in a VM (and docker / bare metal, but those don't work with MuQSS).  I've used it personally to study kubernetes and didn't run into any compatibility issues.
