### ISSUE TITLE
memfd_create() without MFD_EXEC nor MFD_NOEXEC_SEAL, pid=779 'systemd'

### ISSUE THREAD

**Issue by amsaal** [damentz/liquorix-package#140]
when i was checking logs i did tail -f /var/log/syslog this showed up at last .

memfd_create() without MFD_EXEC nor MFD_NOEXEC_SEAL, pid=779 'systemd'

i dont know if this cause any concern but just wanted to share about it.

**Comment by damentz** [comment]
Appears to be an upstream bug: https://bugzilla.kernel.org/show_bug.cgi?id=217508.  Comment of note:

> Stuart Foster 2023-06-01 15:22:26 UTC
> 
> Comments received in e-mails:
> 
> Vlastimil Babka wrote:
> 
> Hm indeed it seems to have introduced 2 new flags and immediately warn if
> any process doesn't use them. Maybe it would make sense for some of the
> non-default values of vm.memfd_noexec, but it's too early to warn
> unconditionally everywhere, no?
> 
> Kees reply:
> 
> This is pretty standard for getting new options like this noticed by
> userspace -- there is no regression in _behavior_. It's just a reminder
> to fix userspace code.

Nothing to worry about here, the warning is so that developers are notified of these messages and eventually update their software.
