### ISSUE TITLE
need help recompiling kernel with specific flag(s) enabled

### ISSUE THREAD

**Issue by cg-cri-gl** [damentz/liquorix-package#141]
To keep the post short: 

The **issue** i'm facing  with your version of the kernel  (which i'm very happy about otherwise) is that the on-board sound-card isn't  working. 
Though working fine, when running stock debian kernel  6.x (running MX Linux here in case it matters).

The **solution** (which i can also confirm by doing a _diff_ on the _config.gz_s between the stock kernel and your version) implies kernel recompilation, as per solution proposed [here](https://blog.fts.scot/2020/07/04/dell-xps-2020-how-to-get-audio-working-on-linux/#comment-356)  and [here](https://blog.fts.scot/2020/07/04/dell-xps-2020-how-to-get-audio-working-on-linux/#comment-405) (not sure if this last quirk is applicable / needed...). 

The flag(s) are : _CONFIG_SND_SOC_INTEL_USER_FRIENDLY_LONG_NAMES=y”_ since _'CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m'_ is enabled already it seems.

The kind **request** for help from you is how to compile the kernel with those flags enabled , as the kernel _config_ is automatically generated , as per [documentation](https://github.com/damentz/liquorix-package/tree/6.4/master/linux-liquorix/debian) ?

Thank you 

LE: kernel compilation (inside docker containre) fails with  "**dpkg-source: info: you can integrate the local changes with dpkg-source --commit**" ; how to do such in a ephemeral container ?

Thanks 

```
[...]
[INFO ] Making source package
dpkg-buildpackage: info: source package linux-liquorix
dpkg-buildpackage: info: source version 6.2-19
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Steven Barrett <steven@liquorix.net>
 dpkg-source --before-build .
dpkg-source: info: using options from linux-liquorix/debian/source/options: --compression=xz --compression-level=3 --extend-diff-ignore=(^|/)(config\.sub|config\.guess|Makefile)$
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: applying zen/v6.2.15-lqx1.patch
dpkg-source: info: applying debian/version.patch
dpkg-source: info: applying debian/uname-version-timestamp.patch
dpkg-source: info: applying debian/kernelvariables.patch
dpkg-source: info: applying debian/module-demote-invalid-elf-header-magic-error-message-to-pr-debug.patch
 debian/rules clean
dh_testdir
rm -rf debian/build debian/stamps debian/lib/python/debian_linux/*.pyc debian/lib/python/debian_linux/__pycache__ $(find debian -maxdepth 1 -type d -name 'linux-*') debian/*-modules-*-di* debian/kernel-image-*-di* debian/xen-linux-system-*
dh_clean
 dpkg-source -b .
dpkg-source: info: using options from linux-liquorix/debian/source/options: --compression=xz --compression-level=3 --extend-diff-ignore=(^|/)(config\.sub|config\.guess|Makefile)$
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building linux-liquorix using existing ./linux-liquorix_6.2.orig.tar.xz
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: local changes detected, the modified files are:
 linux-liquorix/linux-liquorix-build-deps_6.2-19_amd64.buildinfo
 linux-liquorix/linux-liquorix-build-deps_6.2-19_amd64.changes
**dpkg-source: info: you can integrate the local changes with dpkg-source --commit**
dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/linux-liquorix_6.2-19.diff.hfM4a0
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 2


```

**Comment by damentz** [comment]
I believe this issue was resolved in https://github.com/damentz/liquorix-package/issues/142, closing.

EDIT:  And sorry for the late response, the headline of this issue looked more like a tech support request, which I de-prioritize. The person in #142 asked for the specific change you wanted here (that I missed), and was very easy for me to make.

**Comment by cg-cri-gl** [comment]
Thanks for working on the other (=same) issue
Though one question : any chance for me to compile the older kernel version  6.2-19?  The compilation fails  now, with `dpkg-source` complaining **dpkg-source: info: you can integrate the local changes with dpkg-source --commit"**  ( (see previous logs) 
The reason i'd need that is due to some nvidia kernel modules , hacked around to work for the 6.2.x source 


Thanks

**Comment by cg-cri-gl** [comment]
ping @damentz please can you jump in and help me out when hitting this error message when compiling an older kernel version ? 
Thanks !

**Comment by damentz** [comment]
I don't provide support for unsupported versions of Liquorix.  However, I believe this commit is pertinent to you: https://github.com/damentz/liquorix-package/commit/5eae49c0737cee9d68369c6c1725a07befb0dea8
