### ISSUE TITLE
[request] please set/enable specific Kconfig flag // no sound on new-ish laptop (but sound present on stock debian kernel)

### ISSUE THREAD

**Issue by cg-cri-gl** [damentz/liquorix-package#142]
This is related to the other open issue ('need help recompiling...') 
The problem is that the liquorix kernel is lacking following flags enabled, and as per [info](https://blog.fts.scot/2020/07/04/dell-xps-2020-how-to-get-audio-working-on-linux/#comment-356) it seems to cause the absence of sound. 

The kind request for you is , unless there is anything speaking against it, to enable the flag (s)  _“CONFIG_SND_SOC_INTEL_USER_FRIENDLY_LONG_NAMES=y”_  (the other related flag , '_CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m'_ is enabled already it seems.

**Comment by damentz** [comment]
Thanks for the report, config will be updated in next release.

**Comment by damentz** [comment]
Latest release adds the missing options: https://github.com/damentz/liquorix-package/releases/tag/6.5-6

Marking as resolved.
