### ISSUE TITLE
liquorix kernel updates not coming after 17 Sept 2023

### ISSUE THREAD

**Issue by amsaal** [damentz/liquorix-package#143]
The versions are not getting updates from the github anymore after 17 Sept 2023

root@ns31197xx:~# uname -a
Linux ns31197xx 6.5.3-2-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.5-2.1~bullseye (2023-09-17) x86_64 GNU/Linux
root@ns31197xx:~# curl -s 'https://liquorix.net/install-liquorix.sh' | sudo bash
[INFO ] Possible distributions: debian
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Get:6 https://packages.sury.org/apache2 bullseye InRelease [6793 B]
Hit:5 https://downloads.mariadb.com/Tools/debian bullseye InRelease
Get:8 https://dlm.mariadb.com/repo/mariadb-server/10.8/repo/debian bullseye InRelease [3885 B]
Hit:7 https://cdn.liquorix.net/debian bullseye InRelease
Get:9 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye InRelease [9347 B]
Fetched 20.0 kB in 1s (26.3 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
gpg is already the newest version (2.2.27-2+deb11u2).
curl is already the newest version (7.74.0-1.3+deb11u10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3441  100  3441    0     0  20122      0 --:--:-- --:--:-- --:--:-- 20005

[INFO ] Liquorix keyring added to /etc/apt/keyrings/liquorix-keyring.gpg

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.2.4).
lsb-release is already the newest version (11.1.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Get:6 https://packages.sury.org/apache2 bullseye InRelease [6793 B]
Hit:5 https://downloads.mariadb.com/Tools/debian bullseye InRelease
Get:8 https://dlm.mariadb.com/repo/mariadb-server/10.8/repo/debian bullseye InRelease [3885 B]
Hit:7 https://cdn.liquorix.net/debian bullseye InRelease
Get:9 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye InRelease [9347 B]
Fetched 20.0 kB in 1s (26.7 kB/s)
Reading package lists... Done

[INFO ] Liquorix repository added successfully to /etc/apt/sources.list.d/liquorix.list

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
linux-headers-liquorix-amd64 is already the newest version (6.5-2.1~bullseye).
linux-image-liquorix-amd64 is already the newest version (6.5-2.1~bullseye).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

[INFO ] Liquorix kernel installed successfully

root@ns31197xx:~# apt-get update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Get:6 https://packages.sury.org/apache2 bullseye InRelease [6793 B]
Hit:5 https://downloads.mariadb.com/Tools/debian bullseye InRelease
Get:8 https://dlm.mariadb.com/repo/mariadb-server/10.8/repo/debian bullseye InRelease [3885 B]
Hit:7 https://cdn.liquorix.net/debian bullseye InRelease
Get:9 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye InRelease [9347 B]
Fetched 20.0 kB in 1s (27.6 kB/s)
Reading package lists... Done
root@ns31197xx:~# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@ns31197xx:~# uname -a
Linux ns31197xx 6.5.3-2-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.5-2.1~bullseye (2023-09-17) x86_64 GNU/Linux
root@ns31197xx:~# apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://deb.debian.org/debian bullseye-backports InRelease
Hit:4 http://security.debian.org/debian-security bullseye-security InRelease
Get:6 https://packages.sury.org/apache2 bullseye InRelease [6793 B]
Hit:5 https://downloads.mariadb.com/Tools/debian bullseye InRelease
Get:8 https://dlm.mariadb.com/repo/mariadb-server/10.8/repo/debian bullseye InRelease [3885 B]
Hit:7 https://cdn.liquorix.net/debian bullseye InRelease
Get:9 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye InRelease [9347 B]
Fetched 20.0 kB in 1s (27.5 kB/s)
Reading package lists... Done
root@ns31197xx:~# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@ns31197xx:~# uname -a
Linux ns31197xx 6.5.3-2-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.5-2.1~bullseye (2023-09-17) x86_64 GNU/Linux
root@ns31197xx:~# uname -sr
Linux 6.5.3-2-liquorix-amd64
root@ns31197xx:~# uname -a
Linux ns31197xx 6.5.3-2-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.5-2.1~bullseye (2023-09-17) x86_64 GNU/Linux
root@ns31197xx:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
root@ns31197xx:~# cat /proc/version
Linux version 6.5.3-2-liquorix-amd64 (steven@liquorix.net) (gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 ZEN SMP PREEMPT liquorix 6.5-2.1~bullseye (2023-09-17)
root@ns31197xx:~# uname -r
6.5.3-2-liquorix-amd64
root@ns31197xx:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@ns31197xx:~# ^C
root@ns31197xx:~# apt-get update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Get:6 https://packages.sury.org/apache2 bullseye InRelease [6793 B]
Hit:5 https://downloads.mariadb.com/Tools/debian bullseye InRelease
Get:8 https://dlm.mariadb.com/repo/mariadb-server/10.8/repo/debian bullseye InRelease [3885 B]
Hit:7 https://cdn.liquorix.net/debian bullseye InRelease
Get:9 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye InRelease [9347 B]
Fetched 20.0 kB in 1s (28.5 kB/s)
Reading package lists... Done
root@ns31197xx:~# apt-get upgreate
E: Invalid operation upgreate
root@ns31197xx:~# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@ns31197xx:~# ^C
root@ns31197xx:~#

**Comment by damentz** [comment]
Bullseye support was removed for kernel v6.5 and will not be returning.  I recommend you upgrade to Bookworm.
