### ISSUE TITLE
HPET disabled by CONFIG_CMDLINE

### ISSUE THREAD

**Issue by hannesmann** [damentz/liquorix-package#144]
I have a laptop that needs to use HPET because the TSC is unstable (it's this issue: https://bugzilla.kernel.org/show_bug.cgi?id=216166, Lenovo still hasn't provided a BIOS update). I boot with `tsc=unstable clocksource=hpet` but this doesn't work on Liquorix because the built-in kernel command line sets `hpet=disable`. This leaves `acpi_pm` as the only available clocksource which is apparently slower and less accurate than HPET.

I tried booting with `hpet=enable` and `hpet=force` but this doesn't work because `hpet=disable` can't be reversed (the first option doesn't even seem to exist). 

Could `hpet=disable` be removed from CONFIG_CMDLINE, or a kernel parameter added that would override the default behavior for those that need it?

**Comment by damentz** [comment]
Next release removes the `hpet=disable` cmdline.  This may affect others badly but if that's the case, I'll figure out a code change instead to only allow HPET as last resort.

**Comment by damentz** [comment]
Next release will be available with fix in the next few hours, marking as done.
