### ISSUE TITLE
crashes on Firefox

### ISSUE THREAD

**Issue by juanpc2018** [damentz/liquorix-package#146]
i have some ["Not Responding"] issues on Firefox

dont know if its the intel 4th gen integrated gpu driver, 
that has issues in Chromium and similar, Yandex, Thorium, Chome, etc...

Firefox is different, but crash is similar to Out of Memory,
could be a swapfile configuration issue, i have swap configured to lean more to Ram

["Not Responding"] has become very noticeable with Liquorix Kernel 6.5-9

just Pin many different websites.
open youtube,  play videos.
Kubuntu 22.04.1 LTS
![Screenshot_20231107_115017](https://github.com/damentz/liquorix-package/assets/33388902/57beb65b-74dd-4c1c-bf1b-7ca947a63aef)

**Comment by damentz** [comment]
You provided no information for me to go off of to help you.  Only information useful is your version of Kubuntu.  Maybe try upgrading to 23.10?  New kernel and old OS leads to unexplainable behavior.

**Comment by juanpc2018** [comment]
Problem is:
22.04 is an [LTS](https://wiki.ubuntu.com/LTS) release,
23.10 | Mantic is Not an [LTS](https://wiki.ubuntu.com/LTS).
https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions
22.04 [LTS](https://wiki.ubuntu.com/LTS) support goes to 2027, security updates to 2032.
23.10 support goes to 2024.
Non-LTS are pre-releases.
24.04 [LTS](https://wiki.ubuntu.com/LTS) | Noble Numbat | 2024-04 | 2029-05 | 2034-04

Kernel 5.19 generic comes pre-installed in 22.10 
https://web.archive.org/web/20230331130820/https://cdimage.ubuntu.com/kubuntu/releases/22.10/release/kubuntu-22.10-desktop-amd64.iso.torrent

i will try with a clean install of [LTS](https://wiki.ubuntu.com/LTS) on another SSD/M.2.
this installation had to many battles.
https://cdimage.ubuntu.com/kubuntu/releases/22.04.3/release/kubuntu-22.04.3-desktop-amd64.iso.torrent

https://web.archive.org/web/20230331130820/http://cdimage.ubuntu.com/kubuntu/releases/22.04.2/release/kubuntu-22.04.2-desktop-amd64.iso.torrent

https://web.archive.org/web/20221229231152/https://cdimage.ubuntu.com/kubuntu/releases/22.04.1/release/kubuntu-22.04.1-desktop-amd64.iso.torrent

1st i will try with another GPU.

**Comment by juanpc2018** [comment]
Kubuntu 22.04.3 LTS comes with kernel 6.2.0-36 pre-installed.
in theory 22.04.2 should come with kernel 5.19.
when released, 22.04.4 should come with kernel 6.5.0 .

more test needed, will take time to install SW again.

22.04.3 formatted with XFS,
old 22.04.1 formatted with Ext4 v2.

**Comment by damentz** [comment]
Ok, well if you're insisting on LTS even though that's probably the issue, I'll close this issue out.  Old distros with ancient user space are completely unsupportable with a modern enthusiast kernel.

**Comment by juanpc2018** [comment]
Firefox address bar, 
type:
about:crashes

Click: Submit
Click: View. 

its a [4 year old Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1614172), that got triggered somehow...

updating kernel should have No issues with Firefox...
i have installed 5.17 generic on a 20.04 LTS, and works ok.
6.10 on a 22.04.1 LTS should work ok.
New kernels are code optimizations, and new built-in drivers, Nothing extra ordinary.

**Comment by juanpc2018** [comment]
the firefox crash, does Not happen with lowlatency kernel 6.2
https://bugzilla.mozilla.org/show_bug.cgi?id=1863807

about-support file
[about-support.zip](https://github.com/damentz/liquorix-package/files/13679684/about-support.zip)

with usb audio
[about-support-usb-audio.zip](https://github.com/damentz/liquorix-package/files/13679765/about-support-usb-audio.zip)
