### ISSUE TITLE
Latest build  linux-image-6.5.11-2-liquorix-amd64 fails to mount efi partition on boot

### ISSUE THREAD

**Issue by vejeta** [damentz/liquorix-package#148]
It is failing at boot time with this message:

Failed to mount boot-efi.mount

PS: I already have tried this:

- Boot with a USB drive.
- mount the system
- mount my efi partition into /boot/efi
- grub-install
- update-grub

Still it fails when rebooting into the latest kernel.

**Comment by damentz** [comment]
Yep sorry, there should be another version on the way.  Look out for 6.5.11-3 as the version you're running has CONFIG_SECURITY_LOADPIN enabled and it can't load modules.

**Comment by vejeta** [comment]
Gee, that was fast. Thank you. 6.5.11-3 is fine!
