### ISSUE TITLE
dkms error log

### ISSUE THREAD

**Issue by netroby** [damentz/liquorix-package#15]
```
Setting up linux-image-liquorix-amd64 (5.0-13.1~sid) ...
Setting up libelf-dev:amd64 (0.176-1) ...
Setting up linux-headers-5.0.0-13.1-liquorix-amd64 (5.0-13.1~sid) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.0.0-13.1-liquorix-amd64
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.

```

seems not working good with dkms
we installed virtualbox, which need dkms auto configure the kernel

**Comment by damentz** [comment]
```
The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
```

This means the maintainer of the virtualbox package you have installed restricted the kernerls that can build the module, maybe to reduce support costs.  This is not a Liquorix problem, this is a package problem.

Where did you get your VirtualBox package?  Try using the upstream version from virtualbox.org first if you haven't already.

**Comment by netroby** [comment]
Yes, i got the package from official virtualbox.org repository.
