### ISSUE TITLE
Segmentation Fault when executing any Nix command

### ISSUE THREAD

**Issue by tuxiqae** [damentz/liquorix-package#155]
Hi, I've been using Liquorix `6.7.1-lqx1-1-lqx` (using the package `linux-lqx` from the binary repo) on my Arch PC for a while now and for the last year started using the [Nix](https://nixos.org/) package manager on top of it.

The issue appeared about a month or two ago (November/December 2023)

How to reproduce:
- Boot into a Liquorix-powered machine
- Install the Nix package manager, I recommend to use the [official installer](https://nixos.org/download#nix-install-linux) or [this one](https://determinate.systems/posts/determinate-nix-installer) by Determinate Systems
- Run any `nix` command (e.g. `nix-shell --version`)
- Report your findings! (should error, throw out a segmentation fault)

Would appreciate any assistance regarding this issue, please let me know if you need anything from me regarding research or what not :)

**Comment by tuxiqae** [comment]
Some background:
After suffering for a while from this issue I started looking for a reason for those crashes, tried reinstalling Nix, even using different installers, nothing worked.
That's when I thought of fiddling with Nix's dependencies.
One of the upsides of Nix is that it packages the dependencies with the binaries, so I figured that if the issue is related to the package, I won't be the only one suffering and it would've been fixed by now after all this time.

Checking all of the dependencies for one of those binaries, while filtering out links to the nix store:
```
# Filtered ones which were specifically linked to the nix store 
⤅ ldd /nix/store/smfmnz0ylx80wkbqbjibj7zcw4q668xp-nix-2.19.2/bin/nix-store | rg -v '=> /nix/store/'
    linux-vdso.so.1 (0x00007fffec3e6000)
    /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007da6cbb7e000)
```
Both of the entries are directly connected to the Linux kernel, so I tried booting the default kernel which proved to be a success, all those binaries were successfully executed! On the other hand, when returning to lqx, the issue returned, so I can be certain that lqx is the cause.

**Comment by damentz** [comment]
On two systems (both Intel and AMD CPUs), I ran the multi-user daemon install and tested `nix-shell --version`, both return back output such as:

```
[steven:~] $ nix-shell --version
nix-shell (Nix) 2.20.0
```

Is there something else I can try?  Maybe I need to install some software to prompt the issue.

**Comment by tuxiqae** [comment]
@damentz Thanks for giving it a try, I don't think that installing a Nix package would make a difference but feel free to try, you can search the package catalogue for packages which might be relevant for you: https://search.nixos.org 

Once you find a package just run the following command, replacing `<package name>` with the package you chose.
`nix profile install nixpkgs#<package name>`


I don't see any reason for the behavior to change once you install a package (as it'll only affect the metadata, and symlinks/paths), so let me know if there's anything you want me to try on my machine that might help uncovering this mystery

**Comment by damentz** [comment]
@tuxiqae is this still an issue?

**Comment by tuxiqae** [comment]
@damentz It still is, even with kernel `6.8.8-lqx1-1-lqx` :(

**Comment by damentz** [comment]
Ok, well I think I'll close this out as there doesn't appear to be any interest from anyone else.

However, if you can provide complete reproducing steps from a brand new install of a popular distro, I may be able to reproduce the issue you're having.
