### ISSUE TITLE
NVIDIA driver regression on 5.1+

### ISSUE THREAD

**Issue by zrnsm** [damentz/liquorix-package#16]
Hey Steven. I'm seeing a regression on the latest 5.1 kernels from the PPA. What I think is happening is that I'm falling back to Noveau after the NVIDIA driver fails to start.

I've been using NVIDIA 418.56 from https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa. Maybe this is to be expected with 5.1 and that driver. Is there anything that comes to mind in the transition from 5.0 to 5.1 that might have affected the graphics stack? I'm going to dig a bit deeper and debug when I have some more free time.

The 5.0 releases have been rock solid for me lately. I really appreciate the work going into this project. Let me know if there's anything I can do to help out.

**Comment by zrnsm** [comment]
Looks like there is probably some breakage with 5.1 and 418.56 in general: https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-418/+bug/1827944

http://rglinuxtech.com/?p=2533

**Comment by damentz** [comment]
Per nVidia's unix download page[1], the 418 series is no longer supported.  You'll want to upgrade to the 430 series, the current long-lived branch.  The PPA you linked currently has 430.14 packaged under the `nvidia-graphics-drivers-430`.

[1] https://www.nvidia.com/object/unix.html
--
Linux x86_64/AMD64/EM64T
Latest Long Lived Branch Version: 430.14
Latest Short Lived Branch Version: 415.27

**Comment by zrnsm** [comment]
Confirming that this is resolved with the 430 driver. Thanks!
