### ISSUE TITLE
no defined frequency for cpu and low performance with encoder ffmpeg

### ISSUE THREAD

**Issue by mckaygerhard** [damentz/liquorix-package#161]
I already read https://github.com/damentz/liquorix-package/issues/13#issuecomment-665180793 about cpu frecuency and states,, 

.. but i am running the liquoris kernel and trying to enconde from mkv to mp4 H256 with cine_encoder (ffmpeg in fact its who do the job) **and seems the process apart its xtremely slow does not use so much the cpu as previusly do with lts standar kernel**

When i was trying to set a performance with cpufreq found that **there is not state for, in fact there is no state at `/sys/devices/system/cpu/cpufreq`**:

```
ls /sys/devices/system/cpu/cpufreq/
ls: cannot access '/sys/devices/system/cpu/cpufreq/policy*': No such file or directory
```

LAsted kernel does not make any difference and also there is no state defined for any cpu:

```
analyzing CPU 13:
  no or unknown cpufreq driver is active on this CPU
  maximum transition latency: 4294.55 ms.
analyzing CPU 14:
  no or unknown cpufreq driver is active on this CPU
  maximum transition latency: 4294.55 ms.
analyzing CPU 15:
  no or unknown cpufreq driver is active on this CPU
  maximum transition latency: 4294.55 ms.
root@# uname -a
Linux oficina-devel2l 6.5.11-4-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.5-17.1~bookworm (2023-11-12) x86_64 GNU/Linux
```

**This is a bug or may i have to setup something to gain good performance enconding videos?**

**Comment by mckaygerhard** [comment]
lasted kernel tested 

![image](https://github.com/damentz/liquorix-package/assets/1571724/64400663-d197-47b3-aabc-30525543b1b8)


and conding still is pretty super slow

**Comment by damentz** [comment]
Can you provide the output of the commands below?
 - `inxi -CMxxxz`
 - `sudo cpupower frequency-info` (or just switch to root and run command without sudo)

**Comment by mckaygerhard** [comment]
may you referes to "https://manpages.debian.org/experimental/linux-cpupower/cpupower-frequency-info.1.en.html" ?? igues your packages doe snot provide such command and its only provides by the linux-image kernel package of the distro.. 

```
root@oficina-devel2l:~# cpupower
-bash: cpupower: command not found
root@oficina-devel2l:~# frequency-info
-bash: frequency-info: command not found
root@oficina-devel2l:~# cpupower-frequency-info
-bash: cpupower-frequency-info: command not found
root@oficina-devel2l:~# aptitude
Performing actions...
(Reading database ... 436724 files and directories currently installed.)
Preparing to unpack .../libcpupower1_6.5.10-1~bpo12+1_amd64.deb ...
Unpacking libcpupower1 (6.5.10-1~bpo12+1) over (6.1.67-1) ...
Selecting previously unselected package linux-cpupower.
Preparing to unpack .../linux-cpupower_6.5.10-1~bpo12+1_amd64.deb ...
Unpacking linux-cpupower (6.5.10-1~bpo12+1) ...
Setting up libcpupower1 (6.5.10-1~bpo12+1) ...
Setting up linux-cpupower (6.5.10-1~bpo12+1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u3) ...
Scanning processes...                                                                                                                         
Scanning processor microcode...                                                                                                               
Scanning linux images...                                           
```

this was not necesary with normal linux distro kernel that uses cpufrequtils interfaces..  after installing from backports (cos your kernel is 6.6+) this is the information (not using sudo crap) from different boots: (i will paste on each boot using edit the issue, so waith the next two boot):

#### boot 1 using kernel 6.1.0 from debian 

```
root@oficina-devel2l:~# cpupower-frequency-info
-bash: cpupower-frequency-info: command not found
root@oficina-devel2l:~# cpupower frequency-info
analyzing CPU 5:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 5
  CPUs which need to have their frequency coordinated by software: 5
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 800 MHz - 5.00 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 800 MHz and 5.00 GHz.
                  The governor "powersave" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 3.15 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes
root@oficina-devel2l:~# uname -a
Linux oficina-devel2l 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux
root@oficina-devel2l:~# 
```

#### boot 2 using kernel 6.7 from liquoris

```
root@oficina-devel2l:~# cpupower frequency-info
analyzing CPU 0:
  no or unknown cpufreq driver is active on this CPU
  CPUs which run at the same hardware frequency: Not Available
  CPUs which need to have their frequency coordinated by software: Not Available
  maximum transition latency:  Cannot determine or is not supported.
Not Available
  available cpufreq governors: Not Available
  Unable to determine current policy
  current CPU frequency: Unable to call hardware
  current CPU frequency:  Unable to call to kernel
  boost state support:
    Supported: yes
    Active: yes
root@oficina-devel2l:~# uanme -a
-bash: uanme: command not found
root@oficina-devel2l:~# uname -a
Linux oficina-devel2l 6.7.2-3-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.7-4.1~bookworm (2024-01-28) x86_64 GNU/Linux
root@oficina-devel2l:~#
```

**Comment by damentz** [comment]
Ok, thanks for the info, can you provide the output for the two commands below too?

 - `cat /proc/cmdline`
 - `cat /etc/modprobe.d/*`

**Comment by mckaygerhard** [comment]
as i posted .. seems something is broken since long time cos i boot also kernel 5.X and 6.5.11 and the results are same.. "unknow" power state--- 

the instalation of cpupower was innecesary cos the interface is not provided by kernel.. it seems older kernels on debian 9 of liquierys are wroking .. using a repackaged from MX linux project

**Comment by damentz** [comment]
Another important note, you can get back to _normal_ by adding `intel_pstate=enable` to your kernel boot parameters.  The reason why is that `intel_pstate` doesn't guarantee the CPU gets the correct frequency when running interactive tasks, so is disabled by default on Liquorix.

The reason I ask for cmdline output and contents of modprobe.d is I suspect your system disables acpi_cpufreq by default, breaking cpu scaling with Liquorix.

**Comment by mckaygerhard** [comment]
> Ok, thanks for the info, can you provide the output for the two commands below too?
> 
> * `cat /proc/cmdline`
> * `cat /etc/modprobe.d/*`

yo answered so fast ok as you suggested YEAH you cvan enable it.. but the performance seesm still LOW.. (note the title of the issue when i try to coding.. the cpu is not so used.. **please wait for just 30 minutes to provide you more info with both parametesr and both kernels using `intel_pstate=enable` and `intel_pstate=disable` (the default and the main reason of not cpu state)** 

bescouse: so this issue is about a firt one (no state of the cpu.. the cpu is locked at 3GHz only and does not get the max of 5GH cos is an i9 9900k) 

and later as consecuence the applications runs not so performed .. like the conding and decoding on the fly..

**Comment by mckaygerhard** [comment]
ok i will paste the info in 3 edits of the same entry . (i man i will post first part, reboot return back here and paste second info and reboot and so on.. )


```
cat /etc/modprobe.d/*
blacklist microcode
options ath9k_htc use_dev_fw=1
blacklist microcode
options md_mod start_ro=1
softdep snd-pcm post: snd-pcm-oss
softdep snd-mixer post: snd-mixer-oss
softdep snd-seq post: snd-seq-midi snd-seq-oss
```

### 1 - using 6.7.2 (6.7-4.1~bookworm) liquoris with intel_pstate enabled

```
root@oficina-devel2l:~# for cpu in /sys/devices/system/cpu/cpufreq/policy*; do echo performance > ${cpu}/scaling_governor; done
root@oficina-devel2l:~# cpupower frequency-info
analyzing CPU 13:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 13
  CPUs which need to have their frequency coordinated by software: 13
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 800 MHz - 5.00 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 800 MHz and 5.00 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 3.40 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes
root@oficina-devel2l:~# cat /proc/cmdline
audit=0 intel_pstate=disable rcupdate.rcu_expedited=1  BOOT_IMAGE=/boot/vmlinuz-6.7.2-3-liquorix-amd64 root=UUID=609e7b04-0d6b-4243-81f7-0bc91dfd3e35 ro intel_pstate=enable default_hugepagesz=1G hugepagesz=1G hugepages=16 hugepagesz=2M hugepages=8192 acpi_enforce_resources=lax nomsi iomem=relaxed
root@oficina-devel2l:~# uanme -a
-bash: uanme: command not found
root@oficina-devel2l:~# uname -a
Linux oficina-devel2l 6.7.2-3-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.7-4.1~bookworm (2024-01-28) x86_64 GNU/Linux
root@oficina-devel2l:~# 
```

trying to enconde a mkv file using H256 to mp4 takes not so much but neither uses so much the cpu event if i am not making nothing more than such process (it means that with loquoris the logic unless normal kernel is to use almost as much resource can to the current process ..)


https://github.com/damentz/liquorix-package/assets/1571724/b5bf1c31-19bb-4337-8d16-0e03b40a323c

### 2 - using 6.7.2 (6.7-4.1~bookworm) liquoris with intel_pstate normally (disabled)

this is the default he grub does not have the parameter set .. the cpu usage is the same.. in fact is low, the enconding takes more.. (31 minutes agains 20 minutes with intel_pstates and performance powerstate set on each cpu)

```
root@oficina-devel2l:~# for cpu in /sys/devices/system/cpu/cpufreq/policy*; do echo performance > ${cpu}/scaling_governor; done
-bash: /sys/devices/system/cpu/cpufreq/policy*/scaling_governor: No such file or directory
root@oficina-devel2l:~# umount /dev/hugepages && mount -t hugetlbfs -o rw,pagesize=1024M,mode=1770,relatime,gid=$(getent group libvirt-qemu | cut -d':' -f3) hugetlbfs /dev/hugepages
root@oficina-devel2l:~# cpupower frequency-info
analyzing CPU 0:
  no or unknown cpufreq driver is active on this CPU
  CPUs which run at the same hardware frequency: Not Available
  CPUs which need to have their frequency coordinated by software: Not Available
  maximum transition latency:  Cannot determine or is not supported.
Not Available
  available cpufreq governors: Not Available
  Unable to determine current policy
  current CPU frequency: Unable to call hardware
  current CPU frequency:  Unable to call to kernel
  boost state support:
    Supported: yes
    Active: yes
root@oficina-devel2l:~# uname -a
Linux oficina-devel2l 6.7.2-3-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.7-4.1~bookworm (2024-01-28) x86_64 GNU/Linux
root@oficina-devel2l:~# cat /proc/cmdline
audit=0 intel_pstate=disable rcupdate.rcu_expedited=1  BOOT_IMAGE=/boot/vmlinuz-6.7.2-3-liquorix-amd64 root=UUID=609e7b04-0d6b-4243-81f7-0bc91dfd3e35 ro default_hugepagesz=1G hugepagesz=1G hugepages=16 hugepagesz=2M hugepages=8192 acpi_enforce_resources=lax nomsi iomem=relaxed
root@oficina-devel2l:~#
```


https://github.com/damentz/liquorix-package/assets/1571724/a8c359b3-4108-4d38-84dc-8bc31dad6183

### 3 - using 6.1.0  debian lts normal kernel with intel_pstate normally (sit seems enabled by default)

here with normal kernel cpu goes to the max 5GHz and process is more faster (byt some seconds.. in bach mode is a huge amoutn of time cheap

```
root@oficina-devel2l:~# umount /dev/hugepages && mount -t hugetlbfs -o rw,pagesize=1024M,mode=1770,relatime,gid=$(getent group libvirt-qemu | cut -d':' -f3) hugetlbfs /dev/hugepages
root@oficina-devel2l:~# for cpu in /sys/devices/system/cpu/cpufreq/policy*; do echo performance > ${cpu}/scaling_governor; done
root@oficina-devel2l:~# cpupower frequency-info
analyzing CPU 4:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 4
  CPUs which need to have their frequency coordinated by software: 4
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 800 MHz - 5.00 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 800 MHz and 5.00 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 4.00 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes
root@oficina-devel2l:~# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-6.1.0-16-amd64 root=UUID=609e7b04-0d6b-4243-81f7-0bc91dfd3e35 ro intel_pstate=enable default_hugepagesz=1G hugepagesz=1G hugepages=16 hugepagesz=2M hugepages=8192 acpi_enforce_resources=lax nomsi iomem=relaxed
root@oficina-devel2l:~#
```

https://github.com/damentz/liquorix-package/assets/1571724/effc9cf6-eee1-46f4-8a43-9587ce4791ce

**Comment by mckaygerhard** [comment]
so i posted the 3 cases.. it is assumed that the liquoris kernel has not only the BFS patch but also zend ones..  that the priorities are focused on active programs instead of rack processes, but seems the normal kernel now since 6.5 does not performed so well agains multimedia coding and decodign.. i was testing also in some games and performance is not so good...

what i suggest? first enable the intel pstate so seems the info provided at https://github.com/damentz/liquorix-package/issues/13#issuecomment-665180793 is not so true ! performance without intel pstate is not so good as seems and cpu usage in my intel i9 9900 its poor without it

about the rest? well are you noted i set performance governor.. so i guess some of the patches cut down the performance or the zen kernelo doe snot given so much performance, maybe we must try only the BFS patch without zen ones and test again..

**Comment by damentz** [comment]
Still waiting for the following output:
- `inxi -CMxxxz`
 - `cat /proc/cmdline`
 - `cat /etc/modprobe.d/*`

And yes, Liquorix will _always_ be slower on `intel_pstate` for throughput tasks, processes and threads are spread more evenly across all cores, preventing `intel_pstate` from raising frequency.  Mainline like to pack individual cores to maximize energy efficiency, which works well for how `intel_pstate` works, but increases latency across the board.

Ideally, `acpi_cpufreq` works, but most likely your distro is blacklisting it (thus why I'm asking for output).  It has been tuned perfectly to scale your CPU properly.

**Comment by mckaygerhard** [comment]
the information is provided in each case: of comment https://github.com/damentz/liquorix-package/issues/161#issuecomment-1944035844 the idea of module is makes it possible for the driver to be blacklisted usefully when the driver makes problems which can be seen in the kernel trace.

> And yes, Liquorix will always be slower on intel_pstate for throughput tasks, processes and threads are spread more evenly across all cores, preventing intel_pstate from raising frequency. Mainline like to pack individual cores to maximize energy efficiency, which works well for how intel_pstate works, but increases latency across the board.

err **if you take the time to read.**. the **results are pretty contradictory.. it seems the contrary**.. in first case i deactivate it. .as you suggest and the performance is slow.. later activated and performace is bit faster but still slow.. 


the `acpi_cpufreq` is not blacklisted but doe snot work with liquoris : `modprobe: ERROR: could not insert 'acpi_cpufreq': No such device` cos it depends of intel_pstates

```
root@oficina-devel2l:~# modinfo acpi_cpufreq
filename:       /lib/modules/6.7.2-3-liquorix-amd64/kernel/drivers/cpufreq/acpi-cpufreq.ko.zst
alias:          platform:acpi-cpufreq
license:        GPL
description:    ACPI Processor P-States Driver
author:         Paul Diefenbaugh, Dominik Brodowski
srcversion:     56F2DECB8EB6C926CC2EA17
depends:        
retpoline:      Y
intree:         Y
name:           acpi_cpufreq
vermagic:       6.7.2-3-liquorix-amd64 SMP preempt mod_unload 
parm:           acpi_pstate_strict:value 0 or non-zero. non-zero -> strict ACPI checks are performed during frequency changes. (uint)
root@oficina-devel2l:~# modprobe acpi_cpufreq
modprobe: ERROR: could not insert 'acpi_cpufreq': No such device
root@oficina-devel2l:~# cat /etc/modprobe.d/*
blacklist microcode
options ath9k_htc use_dev_fw=1
blacklist microcode
options md_mod start_ro=1
softdep snd-pcm post: snd-pcm-oss
softdep snd-mixer post: snd-mixer-oss
softdep snd-seq post: snd-seq-midi snd-seq-oss
root@oficina-devel2l:~#
root@oficina-devel2l:~# cat /proc/cmdline 
audit=0 intel_pstate=disable rcupdate.rcu_expedited=1  BOOT_IMAGE=/boot/vmlinuz-6.7.2-3-liquorix-amd64 root=UUID=609e7b04-0d6b-4243-81f7-0bc91dfd3e35 ro default_hugepagesz=1G hugepagesz=1G hugepages=16 hugepagesz=2M hugepages=8192 acpi_enforce_resources=lax iomem=relaxed
root@oficina-devel2l:~#
```

and the info you need is on each case take a look at the picture of the comment previously posted.. (please take the time i provide enough information)

![image](https://github.com/damentz/liquorix-package/assets/1571724/7c22be3a-a090-42f5-a660-919253314612)

**Comment by damentz** [comment]
You're still not providing what I'm asking for...

Regardless, the information you're not providing will probably reveal you're blacklisting `acpi-cpufreq`.  Upcoming kernel release compiles in `acpi-cpufreq` so it can't be blacklisted.  Stay tuned for an update in about 1-2 hours.

**Comment by mckaygerhard** [comment]
@damentz  here is the info: https://github.com/damentz/liquorix-package/issues/161#issuecomment-1944035844  the acpi_cpufreq is not blacklisted but doe snot work with liquoris : modprobe: ERROR: could not insert 'acpi_cpufreq': No such device cos it depends of intel_pstates

![image](https://github.com/damentz/liquorix-package/assets/1571724/b8e11618-3f8e-4306-afc6-ad67952c4767)

**Comment by damentz** [comment]
Ok, third try, you were able to provide blacklists, thank you.  However, you just provided truncated cmdline, there's a lot more after `BOOT_IMAGE`.  And please stop posting screenshots, they are not indexable or searchable.  You can post text directly in github issue with triple ticks to wrap text as code or monospace content.

Also, you have not provided the output of `inxi -CMxxxz`.

**If you don't provide the output on the next post I'll close this issue out as all information is required to understand the issue.**

Now, regarding the other interesting thing you posted.

> the acpi_cpufreq is not blacklisted but doe snot work with liquoris : modprobe: ERROR: could not insert 'acpi_cpufreq': No such device cos it depends of intel_pstates

That's nonsense, acpi_cpufreq does not depend on intel_pstate, they are 100% completely separate drivers.  What the output **does indicate** is that your BIOS is misconfigured or buggy.  If `acpi_cpufreq` cannot load, then that means support for `speedstep` or general power management is disabled.

You should check if your system has a BIOS update or setting to fix that.  Unfortunately, I can't tell you how to check or what to look for because you didn't provide the output of `inxi -CMxxxz`.

**Comment by mckaygerhard** [comment]
ok i will reboot (Aggaaaainnn) and check BIOS/UEFI .. is a dell optiplex 7071 with i9 9900k cpu, fresh new..  i will check again the cmd line (using default) and also checked for any hardware details on the motherboard.. acpi_cpufreq works when i enabled the intel_pstate so i guess there is some missing info about the new kernel.. i also will try to check the older debian 9 with lñiquoris older kernel --- wait for 10 minutes.. and post feedback but please please: 

> Ok, third try, you were able to provide blacklists, thank you. However, you just provided truncated cmdline, there's a lot more after BOOT_IMAGE. And please stop posting screenshots, they are not indexable or searchable. You can post text directly in github issue with triple ticks to wrap text as code or monospace content.

**men PLEASE ! the complete CMD line and info are on the comment and is not truncated.. inclusivelly i provide info of 6.7, 6.5 and 6.1 kernels versions..**  THE PICTURES WAS FOR POINTED THAT THE INFO WAS AFTYER EDITING (as i posted first)

**Comment by damentz** [comment]
> ok i will reboot (Aggaaaainnn) and check BIOS/UEFI .. is a dell optiplex 7071 with i9 9900k cpu, fresh new.. i will check again the cmd line (using default) and also checked for any hardware details on the motherboard.. acpi_cpufreq works when i enabled the intel_pstate so i guess there is some missing info about the new kernel.. i also will try to check the older debian 9 with lñiquoris older kernel --- wait for 10 minutes.. and post feedback but please please:
> 
> > Ok, third try, you were able to provide blacklists, thank you. However, you just provided truncated cmdline, there's a lot more after BOOT_IMAGE. And please stop posting screenshots, they are not indexable or searchable. You can post text directly in github issue with triple ticks to wrap text as code or monospace content.
> 
> **men PLEASE ! the complete CMD line and info are on the comment and is not truncated.. inclusivelly i provide info of 6.7, 6.5 and 6.1 kernels versions..** THE PICTURES WAS FOR POINTED THAT THE INFO WAS AFTYER EDITING (as i posted first)

Ok, I see the edited post now.  I recommend in the future that you don't go back and edit new posts as I don't receive notifications and have no idea you're making changes.  You can just make a new post with the data by itself.

If you had posted the `inxi` output we would have known you have an Optiplex 7071.  You need to upgrade your BIOS and enable dynamic CPU frequency selection: https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=jxf1f&oscode=biosa&productcode=optiplex-7071-desktop

I'm closing out this issue since this is a misconfiguration on your end.

**Comment by mckaygerhard** [comment]
err i have the update bios.. previously to report the issue enables all the bios settings and rebooted with windows.. and seems its working only in windos and debian.. but in linux with your kernel does not work.. with debian kernel it works (backpórted) reports better performance with no liquiris kernel loaded.. (see tests posted previously)

installed acpi packages and dmidecode reports up to date code .. 

BIOS information report no issue and updates does not affect cpu feq states: (cos debian kernel works perfectly)

```
root@oficina-devel2l:~# dmidecode -t bios
# dmidecode 3.4
Getting SMBIOS data from sysfs.
SMBIOS 3.1.1 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: Dell Inc.
	Version: 1.24.0
	Release Date: 02/02/2024
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 34 MB
	Characteristics:
		PCI is supported
		PNP is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		EDD is supported
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		Print screen service is supported (int 5h)
		8042 keyboard services are supported (int 9h)
		Serial services are supported (int 14h)
		Printer services are supported (int 17h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Function key-initiated network boot is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 1.24

Handle 0xF047, DMI type 13, 22 bytes
BIOS Language Information
	Language Description Format: Long
	Installable Languages: 2
		en|US|iso8859-1
		<BAD INDEX>
	Currently Installed Language: en|US|iso8859-1
```

**Comment by smxi** [comment]
Just to be clear, if there are no policyxx in the /sys cpufreq it means the kernel does not get that data probably because it's disabled. 

As damentz said, if you'd stopped wasting people's time by posting screenshots and provided the data required, you could have spared everyone a lot of pointless reading.

Also, NEVER interpret or edit data that is requested, post the full output, in text, if you don't know how to copy text from a terminal, learn. Never pick the bits of data from a command output requested because you have no idea what is required, post what is requested and then go on, otherwise you waste everyone's time, including yours. 

If someone asks you for output from command line programs don't be silly and show they are not installed, install them and show the output, this isn't elementary school or kindergarden. 

Asking for sudo is simply to tell you that it requires superuser priviliges, nobody can assume random issue posters know this. People who know what they are doing will go, ah, sudo, I use root, so no sudo required, people who do not know this, use sudo, and get the correct output. Whenever I forget this, a user will always show permission denied errors in the output, so after a while, you just start adding the sudo for people who don't know, and people who do know, know it just means requires root.

I can't place where you are from, but you need to stop, think, and most important, read and follow the directions. DO NOT show random stuff nobody asks for, it doesn't matter and just hides the issue, and learn issue posting 101, beginner lesson: do NOT show screenshots unless it is extremely specific to the exact issue being posted, for example a screen shot of screen tearing for a display/gpu driver etc.

The reason he asks for inxi is to stop the silly waste of time to get bit after bit of data from you. If you can't figure out how to find and install a program, then you should find something more basic to use than Liquorix since you clearly aren't really ready for it yet.

```
inxi -SMCaz
System:
  Kernel: 6.6.11-1-liquorix-amd64 arch: x86_64 bits: 64 compiler: gcc
    v: 13.2.0 clocksource: tsc avail: hpet,acpi_pm parameters: audit=0
    intel_pstate=disable rcupdate.rcu_expedited=1
    BOOT_IMAGE=/boot/vmlinuz-6.6.11-1-liquorix-amd64
    root=UUID=643cae5c-fe45-41ae-b8a5-d94fafe6bbc4 ro quiet
  Desktop: Xfce v: 4.18.1 tk: Gtk v: 3.24.36 wm: xfwm4 v: 4.18.0
    with: xfce4-panel tools: xfce4-screensaver avail: slock vt: 7 dm: 1: LightDM
    v: 1.32.0 2: SDDM note: stopped Distro: Debian GNU/Linux trixie/sid
Machine:
  Type: Desktop System: Gigabyte product: X470 AORUS ULTRA GAMING v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: X470 AORUS ULTRA GAMING-CF
    serial: <superuser required> uuid: <superuser required> BIOS: American
    Megatrends LLC. v: F62d date: 10/13/2021
CPU:
  Info: model: AMD Ryzen 5 2600 bits: 64 type: MT MCP arch: Zen+ gen: 2
    level: v3 note: check built: 2018-21 process: GF 12nm family: 0x17 (23)
    model-id: 8 stepping: 2 microcode: 0x800820D
  Topology: cpus: 1x cores: 6 tpc: 2 threads: 12 smt: enabled cache:
    L1: 576 KiB desc: d-6x32 KiB; i-6x64 KiB L2: 3 MiB desc: 6x512 KiB
    L3: 16 MiB desc: 2x8 MiB
  Speed (MHz): avg: 1829 high: 3899 min/max: 1550/3400 boost: enabled
    scaling: driver: acpi-cpufreq governor: ondemand cores: 1: 1557 2: 3899
    3: 1558 4: 1375 5: 1377 6: 1376 7: 1560 8: 3400 9: 1550 10: 1550 11: 1376
    12: 1375 bogomips: 81603
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
  Vulnerabilities:
  Type: gather_data_sampling status: Not affected
  Type: itlb_multihit status: Not affected
  Type: l1tf status: Not affected
  Type: mds status: Not affected
  Type: meltdown status: Not affected
  Type: mmio_stale_data status: Not affected
  Type: retbleed mitigation: untrained return thunk; SMT vulnerable
  Type: spec_rstack_overflow mitigation: Safe RET
  Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via
    prctl
  Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer
    sanitization
  Type: spectre_v2 mitigation: Retpolines, IBPB: conditional, STIBP:
    disabled, RSB filling, PBRSB-eIBRS: Not affected
  Type: srbds status: Not affected
  Type: tsx_async_abort status: Not affected
```

**Comment by mckaygerhard** [comment]
> As damentz said, if you'd stopped wasting people's time by posting screenshots and provided the data required, you could have spared everyone a lot of pointless reading.
> 
> Also, NEVER interpret or edit data that is requested, post the full output, in text, if you don't know how to copy text from a terminal, learn. Never pick the bits of data from a command output requested because you have no idea what is required, post what is requested and then go on, otherwise you waste everyone's time, including yours.

OUTPUT IS on edited messages, and inxi its not packages for debian, in fact yesterday office requested to me to use only debian kernels due the low reponse from here!

i was trying to collaborate on a obvious problem, another user already reported that zen kernel does not gives so much FPS in games and later i was curious about it! https://t.me/alpine_linux_espanol/26500

**Comment by smxi** [comment]
I think you need to work on your basic skills before you make statements like 'inxi is not packaged for Debian'. This will certainly come as a surprise to Unit193, the Debian packager for inxi, who I talk to frequently, mainly to let him know new releases are coming.  

https://repology.org/project/inxi/versions

Note I run unstable/testing so you don't see the stable package versions listed, but you do in the repology. 

Let me suggest to you that if you are not even capable of finding a package in Debian or any other distro, you need to work on your more basic skills before wasting people's time trying to do advanced stuff. If you can't grasp this, then you  need to work on more fundamental human skills. Like not mistaking ego and bluster for actual technical competence. It's fairly obvious where you are from but we won't get into that here, nobody is impressed however by such behavior, and it certainly has zero place in the modern tech world;

Again, look in the mirror, who determined that something that is, and has been for many, many years, the case, is not the case? What caused such a false conclusion to be created. I'll give you a hint, it was not me, damentz, the liquorix kernel, Debian, or your work. You have a long way to go sad to say, this is fundamentally elementary stuff, but you seem lacking in the mechanisms required to learn properly, and draw false conclusions based on false assumptions.

This makes any report you make about anything else more complicated largely not worth looking at.

I hope you are very  young, and simply have no experience, if not, I think you picked the wrong type of work.

```
apt-cache policy inxi
inxi:
  Installed: (none)
  Candidate: 3.3.33-1-1
  Version table:
     3.3.33-1-1 990
        300 http://mirrors.kernel.org/debian unstable/main amd64 Packages
        300 http://mirrors.kernel.org/debian unstable/main i386 Packages
        990 http://mirrors.kernel.org/debian testing/main amd64 Packages
        990 http://mirrors.kernel.org/debian testing/main i386 Packages
```

**Comment by damentz** [comment]
Adding to @smxi, whatever you're doing to type English has a lot of problems and makes most of what you say incomprehensible, part of the reason why you feel like you're getting unexpected responses.

Let me give an example:
> OUTPUT IS on edited messages, and inxi its not packages for debian, in fact yesterday office requested to me to use only debian kernels due the low reponse from here!

Interpreting some points:
 - "_inxi its not packages for debian_" - it's not packaged for Debian?  That's not true, so you must be saying something else?  Or you followed the "I tried nothing and I'm out of ideas, so I'll just say random things because I can".
 - "_in fact yesterday office requested to me to use only debian kernels due the low reponse from here!_" - I don't even know how to respond to this, why are you bringing up offices and what is a low or high "reponse"?  In-fact, how are you making typos consistently on the same words, did somebody sabotage your autocorrect file?

Like another example, you keep using "liquoris" and "liquiris" instead of "liquorix".  I can understand that typo but it's consistently wrong; what other words have you been translating wrong this whole time that I've been consistently also misinterpreting?  **In technical issues like this one, words matter a lot and misuse of them and bad translations will just lead to your issues being closed or ignored on a regular basis.**

I'm going to lock this thread.  You should read what @smxi posted very carefully because the way you're reporting issues is impossible to support.
