### ISSUE TITLE
Possible performance regression in 6.7-14/6.7.10-lqx1

### ISSUE THREAD

**Issue by Takei-Naodar** [damentz/liquorix-package#164]
I have a possible performance regression in and after 6.7-14.
Before when having a niced heavy CPU load while running a prioritized process, the prioritized process would run well and without lags. 
Now there is heavy dips in performance up to and including crackling sound. 
This is most notable, when it is 1 heavy load, for example and ffmpeg encode and less so with many smaller loads, for example a kernel build.

With 6.7-13 everything is fine. 
I'm using the AUR version (https://aur.archlinux.org/packages/linux-lqx) on a Manjaro base.
If it is some help, the used Processor is a 7900X.

If more info is needed, please advise.

**Comment by damentz** [comment]
Thanks for the feedback, can you try 6.7-15 as well?  6.7-14 included some optimizations that Alfred Chen worked on.  The version after contains another slew of updates that may have resolved things on your end.

If not, I'll report this to the official Project-C project and hopefully we can get the regression tracked down.

**Comment by Takei-Naodar** [comment]
Yes, I can confirm that with 6.7.10-lqx2/6.7-15 the problem does still persist. 
In any case, many thanks for your work. If I can assist, please do let me know.

**Comment by damentz** [comment]
Ok, latest release on the way should fix your issue.  I reverted all the optimizations that I cherry picked from the v6.8-r1 and v6.8-r2 enhancements in Project-C before fully switching over.

**Comment by Takei-Naodar** [comment]
Yeah, seems good. Stable performance with the niced process working in the background. 
Thank you very much.

**Comment by damentz** [comment]
No problem, I'll remember to make sure this problem doesn't resurface when Liquorix switches to kernel 6.8.  Marking as resolved.
