### ISSUE TITLE
Liquorix Binary Package Hosting Issues?

### ISSUE THREAD

**Issue by erockce** [damentz/liquorix-package#165]
Hi.  I have been using your kernel patches for Gaming and Realtime use cases for several months after coming across https://github.com/zen-kernel/zen-kernel/issues/30. Both work fantastic for me!

Instead of waiting for a compile from source with the posted packages in [AUR](https://aur.archlinux.org/packages?O=0&K=lqx), I followed guidance from the Arch Linux Wiki page [Unofficial user repositories](https://wiki.archlinux.org/title/Unofficial_user_repositories) section [2.33 liquorix](https://wiki.archlinux.org/title/Unofficial_user_repositories#liquorix) to install binary kernel packages.

However within the past month, I am not able to pull down your updates using the typical package update methods. It wasn't until I [found](https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Installing_packages_on_bad_connection) and used the `--disable-download-timeout` option with `pacman` and `yay` that it FINALLY finished the download.

Just wondering if you are either aware or have had others reach out for this issue.

**Comment by niltooth** [comment]
i am also having this issue

**Comment by damentz** [comment]
If you change the URL for the repo from https://liquorix.net to https://cdn.liquorix.net, does that alleviate the timeout issue?

EDIT: I can confirm that requests coming directly from the CDN (Cloudflare R2), is having random timeouts.  Currently investigating.

**Comment by damentz** [comment]
I've disabled the CDN redirect, can ya'll retry?  I'll continue monitoring the state of R2 and re-enable it once Cloudflare fixes the issue.

**Comment by erockce** [comment]
@damentz , thank you for responding!

Updated `/etc/pacman.conf` to use `https://cdn.liquorix.net/`
```
$ grep -A3 "\[liquorix" /etc/pacman.conf
[liquorix]
SigLevel = DatabaseOptional PackageRequired TrustedOnly
Server = https://cdn.liquorix.net/archlinux/$repo/$arch
```

Greeted with coincidental kernel updates:
```
$ yay -Syuu
:: Synchronizing package databases...
 endeavouros is up to date
 core is up to date
 extra is up to date
 multilib is up to date
 liquorix is up to date
:: Searching AUR for updates...
:: Searching databases for updates...
 -> linux: ignoring package upgrade (6.8.2.arch2-1 => 6.8.4.arch1-1)
 -> linux-headers: ignoring package upgrade (6.8.2.arch2-1 => 6.8.4.arch1-1)
 -> linux-lqx: ignoring package upgrade (6.7.12.lqx1-1 => 6.8.4.lqx1-1)
 -> linux-lqx-headers: ignoring package upgrade (6.7.12.lqx1-1 => 6.8.4.lqx1-1)
 -> linux-zen: ignoring package upgrade (6.8.2.zen2-1 => 6.8.4.zen1-1)
 -> linux-zen-headers: ignoring package upgrade (6.8.2.zen2-1 => 6.8.4.zen1-1)
 there is nothing to do
```

Updated `/etc/pacman.conf` to remove the `IgnorePkg` for the packages.  Now let's try it with default package update command:

```
$ yay
:: Synchronizing package databases...
 endeavouros is up to date
 core is up to date
 extra is up to date
 multilib is up to date
 liquorix is up to date
:: Searching AUR for updates...
:: Searching databases for updates...
:: 6 packages to upgrade/install.
6  core/linux                  6.8.2.arch2-1 -> 6.8.4.arch1-1
5  core/linux-headers          6.8.2.arch2-1 -> 6.8.4.arch1-1
4  extra/linux-zen             6.8.2.zen2-1  -> 6.8.4.zen1-1
3  extra/linux-zen-headers     6.8.2.zen2-1  -> 6.8.4.zen1-1
2  liquorix/linux-lqx          6.7.12.lqx1-1 -> 6.8.4.lqx1-1
1  liquorix/linux-lqx-headers  6.7.12.lqx1-1 -> 6.8.4.lqx1-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> Excluding packages may cause partial upgrades and break systems
==> 
Sync Explicit (6): linux-zen-headers-6.8.4.zen1-1, linux-6.8.4.arch1-1, linux-headers-6.8.4.arch1-1, linux-lqx-6.8.4.lqx1-1, linux-lqx-headers-6.8.4.lqx1-1, linux-zen-6.8.4.zen1-1
:: Synchronizing package databases...
 endeavouros is up to date
 core is up to date
 extra is up to date
 multilib is up to date
 liquorix is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (6)                 Old Version    New Version    Net Change  Download Size

core/linux                  6.8.2.arch2-1  6.8.4.arch1-1   -0.11 MiB     132.16 MiB
core/linux-headers          6.8.2.arch2-1  6.8.4.arch1-1    0.01 MiB      25.31 MiB
liquorix/linux-lqx          6.7.12.lqx1-1  6.8.4.lqx1-1     1.51 MiB     143.30 MiB
liquorix/linux-lqx-headers  6.7.12.lqx1-1  6.8.4.lqx1-1     0.53 MiB      32.44 MiB
extra/linux-zen             6.8.2.zen2-1   6.8.4.zen1-1     0.01 MiB     136.79 MiB
extra/linux-zen-headers     6.8.2.zen2-1   6.8.4.zen1-1     0.01 MiB      26.08 MiB

Total Download Size:   496.08 MiB
Total Installed Size:  796.46 MiB
Net Upgrade Size:        1.95 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 linux-lqx-6.8.4.lqx1-1-x86_64.pkg.tar.zst failed to download
 Total (1/6)                          496.1 MiB  49.6 MiB/s 00:10 [------------------------------------] 100%
error: failed retrieving file 'linux-lqx-6.8.4.lqx1-1-x86_64.pkg.tar.zst' from cdn.liquorix.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
 -> error installing repo packages
```

Unfortunately still having the same issue.

Installed my other kernels separately, e.g. standard and zen first with no issues.

Then tried again, and using the disable the timeout option.

Now `yay` just hangs infinitely waiting for `linux-lqx-6.8.4.lqx1-1-x86_64`.

**Comment by damentz** [comment]
@erockce thanks for the confirmation, Cloudflare's R2 service is impaired at the moment.  Using the normal mirror URL (https://liquorix.net), should work for now, I disabled the redirect to R2 per https://github.com/damentz/liquorix-package/issues/165#issuecomment-2041229259

**Comment by erockce** [comment]
Thank you.

I can confirm using `https://liquorix.net` allowed me to download and install the packages normally.

**Comment by niltooth** [comment]
Looks like i was already using the non-cdn url. I can also confirm this is working for me now.  Thanks for the help, i'm too impatient to wait for the aur package to compile :)

**Comment by damentz** [comment]
I converted linking back to the CDN after testing aggressively, no timeout issues on my end.  Previously I was able to reproduce it instantly.

@niltooth @erockce you can quickly test (if you're ok deleting your pacman cache), with: `yes | sudo pacman -Scc; sudo pacman -Sw linux-lqx linux-lqx-headers linux-lqx-docs --noconfirm`.  Hitting up and rerunning will let you test it indefinitely.

**Comment by erockce** [comment]
@damentz, Looks like there's a minor version pkgbuild revision available for me (`6.8.4.lqx1-1 -> 6.8.4.lqx1-2`), so I tried to install it.

Unfortunately I'm still having issues.

```
 linux-lqx-6.8.4.lqx1-2-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'linux-lqx-6.8.4.lqx1-2-x86_64.pkg.tar.zst' from liquorix.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
```

Full disclosure...I did not clear my package cache because I don't see how that is relevant to a network/hosting issue.

Also are we supposed to leave the `/etc/pacman.conf` configuration with `https://liquorix.net` or switch to `https://cdn.liquorix.net` now?

**Comment by damentz** [comment]
No, this was done at the hosting level.  I reverted the change again.  At this point I'll figure out how to get in contact with Cloudflare about this issue.

EDIT: As I was opening a case, their site informed me there's open maintenance for their Atlanta location: https://www.cloudflarestatus.com/incidents/m3w2gzynkygn from April 3rd to the 11th.  That roughly lines up with when these issues started happening.

Before posting I'll wait for them to rescind their notice and try _one_ more time and ask you guys to test for me.  And since this appears to be a repeating issue, I'll not alter the hosting site.  After the 11th (check the status link first as they may extend maintenance), please try downloads using the cdn.liquorix.net site.

**Comment by erockce** [comment]
@damentz because I no longer have timeouts pulling `liquorix` updates, I'm going to close this issue.

Thank you again for responding and being transparent of the underlying hosting problem.  I hope Cloudflare resolves their issues so that you may be able to successfully provide the best performance to everyone around the world who wants to use your kernel patches!

**Comment by damentz** [comment]
After some more testing, the CDN appears to be working again.  Just notifying you guys here that I made the change to redirect to Cloudflare, let me know if it gets busted again and I'll revert it.
