### ISSUE TITLE
ERROR (dkms apport): kernel package linux-headers-6.8.4-2-liquorix-amd64 is not supported

### ISSUE THREAD

**Issue by fhangel** [damentz/liquorix-package#166]
Hello

I'm having issues installing the latest version. I've been using this kernel for a long time without any problems until now so I'm not sure what this could be related to.

This is the error:

> Building module:
Cleaning build area...
make -j8 KERNELRELEASE=6.8.4-2-liquorix-amd64 KERNEL_DIR=/lib/modules/6.8.4-2-liquorix-amd64/build all...(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-6.8.4-2-liquorix-amd64 is not supported
Error! Bad return status for module build on kernel: 6.8.4-2-liquorix-amd64 (x86_64)
Consult /var/lib/dkms/v4l2loopback/0.12.7/build/make.log for more information.
dkms autoinstall on 6.8.4-2-liquorix-amd64/x86_64 succeeded for fwts-efi-runtime-dkms nvidia
dkms autoinstall on 6.8.4-2-liquorix-amd64/x86_64 failed for v4l2loopback(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.

>  * dkms: autoinstall for kernel 6.8.4-2-liquorix-amd64 ...fail!

> run-parts: /etc/kernel/header_postinst.d/dkms exited with return code 11
Failed to process /etc/kernel/header_postinst.d at /var/lib/dpkg/info/linux-headers-6.8.4-2-liquorix-amd64.postinst line 11.
dpkg: error processing package linux-headers-6.8.4-2-liquorix-amd64 (--configure): installed linux-headers-6.8.4-2-liquorix-amd64 package post-installation script subprocess returned error exit status 1

Here is complete output:
[liquorix_kernel_dkms_error.log](https://github.com/damentz/liquorix-package/files/14939901/liquorix_kernel_dkms_error.log)

Here is the make.log
[make.log](https://github.com/damentz/liquorix-package/files/14940016/make.log)

Here is some information about my system:

OS: Ubuntu 23.10 x86_64
Kernel: 6.7.12-1-liquorix-amd64
CPU: Intel i7-4790K (8) @ 4.001GHz
GPU: NVIDIA GeForce GTX 1050 Ti
GPU: NVIDIA GeForce GTX 750 Ti
Memory: 5439MiB / 32048MiB

Any help with this would be appreciated.

**Comment by fhangel** [comment]
Update:

I removed v4l2loopback-dkms and was able to get the kernel installed. The version of that package hasn't changed, as it is the one I get from Ubuntu universe repo, 0.12.7.

So I still don't understand why I need to remove that package to get the Kernel working?

**Comment by hrzhu** [comment]
You need to upgrade v4l2loopback to [0.12.7-2ubuntu5](https://launchpad.net/ubuntu/+source/v4l2loopback/0.12.7-2ubuntu5) for Linux 6.8

**Comment by damentz** [comment]
Yep, DKMS packages in frozen pool distros have a tendency to break on major kernel updates.  They're only guaranteed to work on the stock kernel.

Closing since this isn't a Liquorix issue.
