### ISSUE TITLE
Forum registration broken

### ISSUE THREAD

**Issue by clrg** [damentz/liquorix-package#17]
Sorry if this is the wrong place but no idea where to contact you guys.
The current forum has a broken captcha / confirmation code. It's always a dead image for me.

**Comment by damentz** [comment]
I've reached out to @smxi, maybe he can do something about it.  And sorry for the delay, things always break when I go on vacation and I normally don't check this stuff while I'm out.

**Comment by smxi** [comment]
This seems to have been the result of a relatively recent Apache update, with how cookies are handled. This issue should now be resolved. Generally for problems on a website, use the website contact page to report a problem.
