### ISSUE TITLE
In the ubuntu22 desktop version, the window dragging problem can only be clicked on the edge and dragged.

### ISSUE THREAD

**Issue by flowerseacar** [damentz/liquorix-package#171]
The original kernel of ubuntu22 can be dragged anywhere in the mpv player, but now it can only be dragged on the edge.

**Comment by flowerseacar** [comment]
The mouse must be at the edge of the mpv to drag the mpv

**Comment by damentz** [comment]
That's an MPV or desktop software bug, closing.

**Comment by flowerseacar** [comment]
> That's an MPV or desktop software bug, closing.

But this is not how it was run in the original kernel.
