### ISSUE TITLE
Kernel errors

### ISSUE THREAD

**Issue by 3DRaven** [damentz/liquorix-package#173]
Hello. I don’t know exactly where to send the problem, I’ll describe it here first. The laptop froze, this happens rarely, but this time it seems that the kernel log was sufficient. Part with an error in the attachment. This is the second laptop of this model in which this happens occasionally.

uname -r
6.8.9-5-liquorix-amd64

[kernel.log](https://github.com/damentz/liquorix-package/files/15418641/kernel.log)

**Comment by damentz** [comment]
Can you reproduce this issue on other kernels?  The logs indicate that you might have some faulty memory.

Also, please install `inxi` and `dmidecode`, and provide the output of: `sudo inxi -bmxxxz`

Running the command above as root is important to decode information on your memory that's unavailable as an unpriviliged user.

**Comment by damentz** [comment]
Closing out for inactivity.

**Comment by 3DRaven** [comment]
I'm sorry it is vacation :)


{code}
System:
  Kernel: 6.9.3-1-liquorix-amd64 arch: x86_64 bits: 64 compiler: gcc v: 13.2.0
    clocksource: hpet
  Desktop: GNOME v: 46.0 tk: GTK v: 3.24.41 wm: gnome-shell
    tools: gsd-screensaver-proxy dm: GDM3 v: 46.0 Distro: Ubuntu 24.04 LTS
    (Noble Numbat)
Machine:
  Type: Laptop System: LENOVO product: 82N6 v: Legion 7 16ACHg6
    serial: <filter> Chassis: type: 10 v: Legion 7 16ACHg6 serial: <filter>
  Mobo: LENOVO model: LNVNB161216 v: SDK0R32862 WIN serial: <filter>
    part-nu: LENOVO_MT_82N6_BU_idea_FM_Legion 7 16ACHg6
    uuid: e84195ae-11d2-11ec-80f0-84a93808b09b UEFI: LENOVO v: GKCN65WW
    date: 01/16/2024
Battery:
  ID-1: BAT0 charge: 53.6 Wh (70.0%) condition: 76.6/80.0 Wh (95.7%)
    volts: 15.9 min: 15.4 model: Celxpert L20C4PC1 type: Li-poly
    serial: <filter> status: not charging cycles: 25
  Device-1: hidpp_battery_2 model: Logitech MX Master 3S serial: <filter>
    charge: 90% rechargeable: yes status: discharging
Memory:
  System RAM: total: 32 GiB available: 27.27 GiB used: 19.71 GiB (72.3%)
  Array-1: capacity: 32 GiB slots: 2 modules: 2 EC: None
    max-module-size: 16 GiB note: est.
  Device-1: Channel-A DIMM 0 type: DDR4 detail: synchronous unbuffered
    (unregistered) size: 16 GiB speed: 3200 MT/s volts: 1.2 width (bits):
    data: 64 total: 64 manufacturer: Hynix part-no: HMAA2GS6CJR8N-XN
    serial: <filter>
  Device-2: Channel-B DIMM 0 type: DDR4 detail: synchronous unbuffered
    (unregistered) size: 16 GiB speed: 3200 MT/s volts: 1.2 width (bits):
    data: 64 total: 64 manufacturer: Hynix part-no: HMAA2GS6CJR8N-XN
    serial: <filter>
CPU:
  Info: 8-core AMD Ryzen 9 5900HX with Radeon Graphics [MT MCP] arch: Zen 3
    speed (MHz): avg: 701 min/max: 400/4680
Graphics:
  Device-1: NVIDIA GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB]
    vendor: Lenovo driver: nvidia v: 550.90.07 arch: Ampere pcie: speed: 8 GT/s
    lanes: 8 ports: active: none empty: DP-1, DP-2, HDMI-A-1, eDP-1
    bus-ID: 01:00.0 chip-ID: 10de:24dc class-ID: 0300
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    vendor: Lenovo driver: amdgpu v: kernel arch: GCN-5 pcie: speed: 8 GT/s
    lanes: 16 ports: active: eDP-2 empty: none bus-ID: 05:00.0
    chip-ID: 1002:1638 class-ID: 0300 temp: 53.0 C
  Device-3: Bison Integrated Camera driver: uvcvideo type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 bus-ID: 1-3:4 chip-ID: 5986:115f class-ID: fe01
  Display: server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6
    compositor: gnome-shell driver: X: loaded: amdgpu,nvidia
    unloaded: fbdev,modesetting,nouveau,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 3408x2130~165Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: amd mesa v: 24.0.9-0ubuntu0.1
    glx-v: 1.4 direct-render: yes renderer: AMD Radeon Graphics (radeonsi
    renoir LLVM 17.0.6 DRM 3.57 6.9.3-1-liquorix-amd64) device-ID: 1002:1638
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    vendor: Lenovo RTL8111/8168/8411 driver: r8169 v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 port: 2000 bus-ID: 03:00.0 chip-ID: 10ec:8168
    class-ID: 0200
  Device-2: Intel Wi-Fi 6 AX200 vendor: Rivet Networks Killer
    driver: iwlwifi v: kernel pcie: speed: 5 GT/s lanes: 1 bus-ID: 04:00.0
    chip-ID: 8086:2723 class-ID: 0280
  Device-3: ASIX AX88179 Gigabit Ethernet driver: ax88179_178a type: USB
    rev: 3.0 speed: 5 Gb/s lanes: 1 bus-ID: 4-2.4.1:4 chip-ID: 0b95:1790
    class-ID: ff00 serial: <filter>
Drives:
  Local Storage: total: 2.79 TiB used: 645.2 GiB (22.5%)
Info:
  Processes: 619 Power: uptime: 1d 2h 45m states: freeze,mem,disk
    suspend: deep wakeups: 0 hibernate: platform Init: systemd v: 255
    target: graphical (5) default: graphical
  Packages: 2307 pm: dpkg pkgs: 2287 pm: snap pkgs: 20 Compilers:
    gcc: 13.2.0 Shell: Sudo (sudo) v: 1.9.15p5 default: Bash v: 5.2.21
    running-in: mc inxi: 3.3.34
{code}



But I think it is just overheating in games. Some time I got this error but it is first time when I have logs.
