### ISSUE TITLE
Black screen after installing

### ISSUE THREAD

**Issue by forReason** [damentz/liquorix-package#176]
I installed liquorix using this code from the webpage on an external ssd:  
curl -s 'https://liquorix.net/install-liquorix.sh' | sudo bash

Everything worked. So I tried to install it in on my main system. Instead of 6.9-3 it installed 6.9-4 and when booting, I get a black screen with a white, still cursor.

Best regards, Julian

**Comment by damentz** [comment]
Can you provide the output of `inxi -b` from the system that doesn't work?

**Comment by forReason** [comment]
```
System:
  Host: Legion Kernel: 6.9.4-1-liquorix-amd64 arch: x86_64 bits: 64
  Console: tty 1 Distro: Ubuntu 24.04 LTS (Noble Numbat)
Machine:
  Type: Laptop System: LENOVO product: 82Y4 v: Legion Slim 7 16APH8 serial: MP2MBG3L
  Mobo: LENOVO model: LNVNB161216 v: SDK0T76461 WIN serial: MP2MBG3L UEFI: LENOVO v: M1CN40WW
    date: 04/24/2024
Battery:
  ID-1: BAT1 charge: 96.7 Wh (95.9%) condition: 100.8/99.9 Wh (100.9%)
CPU:
  Info: 8-core AMD Ryzen 7 7840HS w/ Radeon 780M Graphics [MT MCP] speed (MHz): avg: 816
    min/max: 400/5137
Graphics:
  Device-1: NVIDIA AD107M [GeForce RTX 4060 Max-Q / Mobile] driver: nvidia v: 550.78
  Device-2: AMD Phoenix1 driver: N/A
  Device-3: Chicony Integrated Camera driver: uvcvideo type: USB
  Display: server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.6 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,radeon,vesa gpu: nvidia tty: 320x100
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: mesa v: 24.0.5-1ubuntu1 note: console (EGL sourced)
    renderer: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2, llvmpipe (LLVM 17.0.6 256 bits)
Network:
  Device-1: MEDIATEK MT7922 802.11ax PCI Express Wireless Network Adapter driver: mt7921e
Drives:
  Local Storage: total: 3.68 TiB used: 625.4 GiB (16.6%)
Info:
  Memory: total: 32 GiB note: est. available: 30.55 GiB used: 725.9 MiB (2.3%)
  Processes: 333 Uptime: 3m Init: systemd Shell: Bash inxi: 3.3.34
```

To provide a little more context on how I got to the described error:
I have a Lenovo Legion Slim 7 laptop, which works in general but I have some GPU driver issues.

1. Someone recommended the liquorix kernel to me. I attached an external harddrive to the bespoken laptop and installed ubuntu 24.04 freshly, in order to test without affecting my system
2. I installed the liquorix kernel to that harddrive. It installed version 6.9.3 and every thing was working
3. I decided to test with my main system and installed liquorix with the same command from the website. However, it installed version 6.9.4

I would not get to the login screen. The final screen was a blank black screen with a fix white underscore cursor which was not blinking.
I started in recovery mode and made sure the nvidia gpu is properly recognized in nvidia smi.
From there on, i tried a couple more things, unfortunately without success:
- switching back from X11 to wayland
- install driver 535
- disable prime in grub, x11 config and nvidia xserver profile

finally, I switched back to my original mainline kernel 6.9.3, which is generally working, but as said some software such as games or davinci have certain performance issue with the nvidia card. The amd igpu is unusable due to white strobe screen effects (which are also present on liquorix kernel, i think the amd official amd drivers are not up to date for 24.04 on amd side)

**Comment by forReason** [comment]
I have gotten further with the installation.
I reinstalled ubuntu and started from a clean installation. I was able to install 6.9.4.x

unfortunately, I have stability issues in gpu intense applications (games, video, rendering)
also I seem to get a kernel panic when shutting down / rebooting.

as of right now, installing 6.9.5.1 Will follow up if its better.

**Comment by forReason** [comment]
I upgraded to the next version. Its not completely stable but i think its acceptable.
