### ISSUE TITLE
Maintain LTS branch 6.6

### ISSUE THREAD

**Issue by ogmkp** [damentz/liquorix-package#183]
Hello,

I use liquorix because I have a multimedia machine and I need a super responsive system.
Even if some people say that 1000hz is useless, I've noticed that with other custom kernels running at 250hz, I get drifts along playbacks or audio/video composition, whereas I don't get any with Liquorix.
I'm using the kernel 6.6.13 from the liquorix repository. Is it possible for you to maintain from the LTS branch of kernel.org with the Liquorix modifications in your repository?
It's for system compatibility reasons on Debian stable.

Thank you.

**Comment by ogmkp** [comment]
Currently I install liquorix like this:
sudo apt install linux-image-6.6.13-1-liquorix-amd64 linux-headers-6.6.13-1-liquorix-amd64 --no-install-recommends
(I don't install the recommendations because I don't need extra stuff like irqbalance)

It would be interesting to have a linux-image-liquorix-lts-6.6-amd64 metapackage that links to the latest LTS 6.6 kernel.
And I suggest that the https://liquorix.net/install-liquorix.sh script should not forcibly install the latest kernel (currently 6.10) but should indicate at the end of apt's sources what metapackages can be installed.

Thanks a lot.

**Comment by damentz** [comment]
Unfortunately, there's no plans to support LTS at the moment.  It will increase infrastructure costs and increase complexity for the very few that use it.  Not to mention the support to provide for a kernel I won't personally use.
