### ISSUE TITLE
Update from 6.11 to 6.12 fails with BTRFS as root filesystem

### ISSUE THREAD

**Issue by 3DRaven** [damentz/liquorix-package#186]
Hi. After a kernel upgrade, it is not possible to boot from btrfs as the root fs. Photo of an error in the attachment
![1000010521](https://github.com/user-attachments/assets/ff81942e-b392-4597-b804-2e760ecd294c)
.

**Comment by damentz** [comment]
Well this is concerning, can you still boot to a different kernel?  You may need to run **btrfs-check** with **--repair** as there may have been some latent filesystem corruption that is incompatible with kernel 6.12.

**Comment by 3DRaven** [comment]
With 6.11.10-1-liquorix-amd64 (previous installed kernel) it works fine without any errors.

**Comment by 3DRaven** [comment]
I found error in update of kernel process

 * dkms: autoinstall for kernel 6.12.1-1-liquorix-amd64
   ...fail!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11

**Comment by 3DRaven** [comment]
After reinstall all works fine, sorry, it is my mistake.
