### ISSUE TITLE
Unable to use VirtualBox host driver

### ISSUE THREAD

**Issue by Scrumplex** [damentz/liquorix-package#2]
OS: KDE neon 5.11 (based on Ubuntu 16.04 LTS)

If I try to install virtualbox-dkms it succeeds and after loading the module and trying to start a VM the system freezes forever. The network stack stops responding (ICMP timeout, Ethernet port lights on Router off). I once left the computer for an hour and it still did not recover.

**Comment by damentz** [comment]
Are you using VirtualBox that came with Ubuntu or the version available through virtualbox.org?  The version in Ubuntu's repository may be too old and not contain updates to support 4.14 or newer.

**Comment by damentz** [comment]
Hmm, then you can either use VirtualBox from virtualbox.org, switch back to the HWE kernel if you need something relatively more recent, or update Ubuntu entirely to something newer that already has all the patches for newer kernels with their OSS version of VirtualBox.

**Comment by Scrumplex** [comment]
I just tried the virtualbox-5.2 package from Oracle repos and it works flawlessly. And sorry for the misconception that the packages in that repo are closed source. They are actually classified as `contrib` (they are free software, but rely on propietary software, probably hypervisors like HyperV)
