### ISSUE TITLE
Update don't work. [homepage down]

### ISSUE THREAD

**Issue by MikkelDK** [damentz/liquorix-package#21]
Hi,

Your site doesn't works ;/

What 2 do? ;)

```bash
W: Failed to fetch http://liquorix.net/debian/dists/buster/InRelease  Temporary failure resolving 'liquorix.net'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
```bash
deb http://liquorix.net/debian buster main
deb-src http://liquorix.net/debian buster main

# Mirrors:
#
# Unit193 - France
# deb http://mirror.unit193.net/liquorix buster main
# deb-src http://mirror.unit193.net/liquorix buster main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: liquorix.net
gpg: no valid OpenPGP data found.
```

**Comment by MikkelDK** [comment]
@damentz what is happens? ;o

**Comment by bubobih** [comment]
confirm that it doesent work... in fact it doesent work for maybe day. it was cached only

**Comment by NoXPhasma** [comment]
Looks like there is no DNS entry for the domain any more. A ping from different servers and different DNS servers can't resolve the domain.

[downforeveryoneorjustme.com](https://downforeveryoneorjustme.com/liquorix.net) reports it's offline as well.

**Comment by damentz** [comment]
Yup, something weird happened to Linode's own DNS and it doesn't know what liquorix.net is.  I put in a quick /etc/hosts workaround since I don't have time to investigate (on vacation, away from home).

**Comment by damentz** [comment]
Actually, opening back up.  It looks like some name servers don't know what liquorix.net is.  But authoritatively, it exists and the major DNS providers know about it.

**Comment by bubobih** [comment]
Use cloudflare....

**Comment by damentz** [comment]
> Use cloudflare....

Cloudflare is great for caching, but doesn't help if no one can resolve the IP of your website.

Can anyone else confirm they're able to reach the website?  So far so good on my personal devices, but your mileage may vary depending on how DNS caching works with your resolvers/relays.

**Comment by damentz** [comment]
> Looks like there is no DNS entry for the domain any more. A ping from different servers and different DNS servers can't resolve the domain.
> 
> [downforeveryoneorjustme.com](https://downforeveryoneorjustme.com/liquorix.net) reports it's offline as well.

Looks like it thinks liquorix.net is up now.  Crossing my fingers that's everyone's experience now.

**Comment by bubobih** [comment]
ya i see it now.... if u have working dedi / shared hosting u can point your domain to cloudflare dns servers and ofcourse register your domain for free on cf and u will never have any problems with dns and resloving... only if your dedi/shared is dead ofcourse....

**Comment by NoXPhasma** [comment]
With a different DNS I'm able to reach the website now.
