### ISSUE TITLE
ACPI missing symbols error after installting liquorix kernel

### ISSUE THREAD

**Issue by Dark-Matter7232** [damentz/liquorix-package#27]
Every time i reboot my pc, grub shows some acpi error.
inxi -F && dmesg | grep -i error
System:    Host: Work-Station Kernel: 5.5.0-9.1-liquorix-amd64 x86_64
           bits: 64
           Desktop: Gnome 3.30.2 Distro: Zorin OS 15.2
Machine:   Device: desktop Mobo: ASRock model: A320M-HDV R4.0 serial: N/A
           UEFI: American Megatrends v: P2.30 date: 06/26/2019
CPU:       Quad core AMD Ryzen 3 2200G with Radeon Vega Graphics (-MCP-) 
           cache: 2048 KB
           clock speeds: max: 3500 MHz 1: 1587 MHz 2: 1588 MHz 3: 2814 MHz
           4: 2462 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560]
           Display Server: x11 (X.Org 1.20.5 ) driver: amdgpu
           Resolution: 1920x1080@74.97hz
           OpenGL: renderer: AMD Radeon RX 460 Graphics (POLARIS11, DRM 3.36.0, 5.5.0-9.1-liquorix-amd64, LLVM 9.0.0)
           version: 4.5 Mesa 19.2.8
Audio:     Card Advanced Micro Devices [AMD] Device 15e3
           driver: snd_hda_intel
           Sound: ALSA v: k5.5.0-9.1-liquorix-amd64
Network:   Card-1: Realtek RTL8111/8168/8411 PCIE Gigabit Ethernet Controller
           driver: r8169
           IF: enp6s0 state: down mac: 70:85:c2:db:7e:32
           Card-2: Realtek RTL8188EUS 802.11n Wireless Network Adapter
           IF: N/A state: N/A mac: N/A
Drives:    HDD Total Size: 440.1GB (2.3% used)
           ID-1: /dev/sda model: HITACHI_HTS72323 size: 320.1GB
           ID-2: /dev/sdb model: KINGSTON_SA400S3 size: 120.0GB
Partition: ID-1: / size: 110G used: 9.3G (9%) fs: ext4 dev: /dev/sdb2
Sensors:   System Temperatures: cpu: No active sensors found. Have you configured your sensors yet? mobo: N/A
Info:      Processes: 320 Uptime: 3 min Memory: 1695.6/15940.8MB
           Client: Shell (bash) inxi: 2.3.56 
[    1.226152] RAS: Correctable Errors collector initialized.
[    1.291689] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GPP0.VGA.LCD._BCM.AFN7], AE_NOT_FOUND (20191018/psargs-330)
[    1.291702] ACPI Error: Aborting method \_SB.PCI0.GPP0.VGA.LCD._BCM due to previous error (AE_NOT_FOUND) (20191018/psparse-531)
[    1.291713] ACPI Error: Evaluating _BCM failed (20191018/video-357)
[    1.291863] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GP17.VGA.LCD._BCM.AFN7], AE_NOT_FOUND (20191018/psargs-330)
[    1.291866] ACPI Error: Aborting method \_SB.PCI0.GP17.VGA.LCD._BCM due to previous error (AE_NOT_FOUND) (20191018/psparse-531)
[    1.291871] ACPI Error: Evaluating _BCM failed (20191018/video-357)
[    4.019913] EXT4-fs (sdb2): re-mounted. Opts: errors=remount-ro

**Comment by damentz** [comment]
What kernel did you switch from?  It's likely that you've "upgraded" to a newer kernel with newer ACPI handling.

Otherwise, those messages are benign as long as your system's power features work as expected.
