### ISSUE TITLE
Bad return status for module build [5.6.0-10.1-liquorix]

### ISSUE THREAD

**Issue by guekho64** [damentz/liquorix-package#28]
Since liquorix kernel has reached 5.6 version, "dkms" has started to complain about a specific module not being able to compile.

I decided to wait a little before actually posting this issue, as it could get solved in the meantime, but it didn't...

The offending module it's "bbswitch" 0.8, avaliable in Ubuntu Bionic's universe repo as a package named "bbswitch-dkms".

I did some research on bbswitch's side as well, but just looking at how long its repo has been without any news, seems almost almost impossible a fix would come up from its creator, so I decided to post this issue here, hoping it'd help in some way.

It's important to say that 5.5 liquorix kernel series (And below) don't complain about this specific issue.

This is the content of "/var/lib/dkms/bbswitch/0.8/build/make.log":

<details><summary><i><b>make.log</b></i></summary>

``` txt

DKMS make.log for bbswitch-0.8 for kernel 5.6.0-10.1-liquorix-amd64 (x86_64)
Sat May  2 19:54:59 CDT 2020
make -C /lib/modules/5.6.0-10.1-liquorix-amd64/build M="$(pwd)" modules
make[1]: Entering directory '/usr/src/linux-headers-5.6.0-10.1-liquorix-amd64'
  CC [M]  /var/lib/dkms/bbswitch/0.8/build/bbswitch.o
/var/lib/dkms/bbswitch/0.8/build/bbswitch.c: In function 'bbswitch_init':
/var/lib/dkms/bbswitch/0.8/build/bbswitch.c:460:63: error: passing argument 4 of 'proc_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
     acpi_entry = proc_create("bbswitch", 0664, acpi_root_dir, &bbswitch_fops);
                                                               ^
In file included from ./include/acpi/acpi_bus.h:83:0,
                 from ./include/linux/acpi.h:32,
                 from /var/lib/dkms/bbswitch/0.8/build/bbswitch.c:32:
./include/linux/proc_fs.h:64:24: note: expected 'const struct proc_ops *' but argument is of type 'struct file_operations *'
 struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
                        ^~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:267: recipe for target '/var/lib/dkms/bbswitch/0.8/build/bbswitch.o' failed
make[2]: *** [/var/lib/dkms/bbswitch/0.8/build/bbswitch.o] Error 1
Makefile:1696: recipe for target '/var/lib/dkms/bbswitch/0.8/build' failed
make[1]: *** [/var/lib/dkms/bbswitch/0.8/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.6.0-10.1-liquorix-amd64'
Makefile:13: recipe for target 'default' failed
make: *** [default] Error 2

```
</details>
<details><summary>Environment</summary>

``` txt

OS: Linux Mint 19.1 Tessa 64 bits
Kernel: 5.3.0-51-generic
GCC: gcc version 7.5.0

```
</details>

**Comment by damentz** [comment]
Yep, this seems to be a known issue, here's two links; an issue and its respective pull request.  What's not helping is that the project itself is unresponsive, so it's completely up to package maintainers to add compatibility patches.

Issue: https://github.com/Bumblebee-Project/bbswitch/issues/198
Pull Request: https://github.com/Bumblebee-Project/bbswitch/pull/196

Considering this patch isn't even in Ubuntu Focal (20.04), your best bet is to take the package source with apt-get source, add the patch in the issue/pull request yourself, and rebuild the package for your system.

And there is another option, maybe you don't need bbswitch.  Check out PRIME: https://wiki.archlinux.org/index.php/PRIME.  Not sure if it's available on your distribution but considering the neglect to bumblebee, it might be worth your time to look for an alternative way to manage switchable graphics.

**Comment by guekho64** [comment]
@damentz Thanks for the quick response.

After further research on this issue, now I understand what's causing the problem. As I'm busy right now doing other things, I think I'll wait a few more weeks to see if this gets solved.

In case it doesn't, then there wouldn't be any other option rather than manually patching "bbswitch", or trying to install PRIME on Ubuntu. Anyways, thanks again for replying me.

**Comment by damentz** [comment]
No problem, and good luck!
