### ISSUE TITLE
Add linux-tools-liquirox-amd64 to make cpupower work.

### ISSUE THREAD

**Issue by Armiixteryx** [damentz/liquorix-package#31]
Trying to use cpupower with liquirox gives the following error:

```
WARNING: cpupower not found for kernel 5.6.0-14.1

  You may need to install the following packages for this specific kernel:
    linux-tools-5.6.0-14.1-liquorix-amd64
    linux-cloud-tools-5.6.0-14.1-liquorix-amd64

  You may also want to install one of the following packages to keep up to date:
    linux-tools-liquorix-amd64
    linux-cloud-tools-liquorix-amd64
```

None of those suggested packages are already available.

I'm using Kubuntu 20.04 LTS with 5.6.0-14.1-liquorix-amd64.

**Comment by bubobih** [comment]
Yes i agreee i needed that many times :)

**Comment by damentz** [comment]
This is do-able but complicated.  The **linux-liquorix** packages are basically a fork that's routinely synchronized with *linux-siduction** (at siduction.org).  I asked the maintainer there if he plans to add support for linux tools, and he said no.

I'll see if I can do this myself.  It seems like I can add instructions to compile the tools in the headers and then add a _provides_ for the packages that Ubuntu needs.  I can also look at Ubuntu's kernel package and see how they do it, maybe their methodology is far simpler than what I'm reading in the debian kernel package.

**Comment by kristof-linux** [comment]
As linux newbie, i'm also interested in how to implement cpupower for liquorix. Is there a way to achieve it myself? Has anyone instructions? Thanks!

**Comment by damentz** [comment]
Tools were added to the kernel headers as part of https://github.com/damentz/liquorix-package/issues/5.  The post install script adds the tools to your PATH so you can access them.  No extra packages are required.
