### ISSUE TITLE
Possibility of enabling intel_pstate in passive mode by default

### ISSUE THREAD

**Issue by alaviss** [damentz/liquorix-package#32]
In [passive mode](https://www.kernel.org/doc/html/latest/admin-guide/pm/intel_pstate.html#passive-mode), `intel_pstate` functions like a `CPUFreq` driver and can make use of it's scheduler like `ondemand` and `pstate`. This mode also allows the entire turbo range to be accessible by `CPUFreq`, and might lead to more efficient scheduling.

I've not benchmarked `intel_pstate` in this mode, but I imagine that this should be slightly better than `acpi_cpufreq` as the default for Intel, given that this would combine the best between the two of them: full turbo range to allow for better power efficiency(? not benchmarked) and other intel-pstate powered configuration knobs, with the good old scheduling drivers from cpufreq.

**Comment by damentz** [comment]
The major difference between `acpi_cpufreq`'s `ondemand` and `intel_pstate`'s passive mode, is that `ondemand` lets you configure the core utilization that prompts full speed / turbo, while `intel_pstate` only has the concept of minimum and maximum performance, which is almost completely analogous to minimum and maximum frequency.

With `ondemand`, reducing `up_threshold` makes the governor more sensitive to light system usage, allowing for max performance under light/medium workload conditions while letting the processor dip to lowest frequencies/voltages when completely idle. `intel_pstate` doesn't have this capability, but it does allow you to set a frequency floor by configuring `min_perf_pct` to an arbitrary number over zero.  

If you'd like to use `intel_pstate` for powersaving purposes, you can add `intel_pstate=enable` in your boot parameters.  However, I don't recommend doing that unless you're looking for maximum powersavings on a laptop.

**Comment by alaviss** [comment]
That's interesting, given these statements from `intel_pstate` documentation:

> The information returned by the ACPI `_PSS` objects is used by the `acpi-cpufreq` scaling driver. On systems supported by `intel_pstate` the `acpi-cpufreq` driver uses the same hardware CPU performance scaling interface, but the set of P-states it can use is limited by the `_PSS` output.
>
> On those systems each `_PSS` object returns a list of P-states supported by the corresponding CPU which basically is a subset of the P-states range that can be used by `intel_pstate` on the same system, with one exception: the whole turbo range is represented by one item in it (the topmost one). 

and

> Apart from the above, `acpi-cpufreq` works like `intel_pstate` in the passive mode, except that the number of P-states it can set is limited to the ones listed by the ACPI `_PSS` objects.

This implies that `intel_pstate`'s passive mode have access to more frequency options than `acpi-cpufreq`, while the governors work exactly the same (I mean it's using the same ones as `acpi-cpufreq`, so it'd be strange if it acts differently).

With that said, I think I'll experiment with this on my device to see if `intel_pstate=passive` allows for more frequency choices while still using `ondemand`. Thanks you for your time :)
