### ISSUE TITLE
Package backport-iwlwifi-dkms is causing problems

### ISSUE THREAD

**Issue by CHJ85** [damentz/liquorix-package#33]
Terminal output:
ERROR (dkms apport): kernel package linux-headers-5.6.0-19.1-liquorix-amd64 is not supported
Error! Bad return status for module build on kernel: 5.6.0-19.1-liquorix-amd64 (x86_64)
Consult /var/lib/dkms/backport-iwlwifi/8324/build/make.log for more information.
dpkg: error processing package backport-iwlwifi-dkms (--configure):
 installed backport-iwlwifi-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 backport-iwlwifi-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

Error log output: 
DKMS make.log for backport-iwlwifi-8324 for kernel 5.6.0-19.1-liquorix-amd64 (x86_64)
to. 18. juni 16:22:53 +0200 2020
Generating local configuration database from kernel ... done.
cc -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer   -c -o conf.o conf.c
cc -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer   -c -o zconf.tab.o zconf.tab.c
cc   conf.o zconf.tab.o   -o conf
#
configuration written to .config
#
make[5]: 'conf' is up to date.
#
#
Building backport-include/backport/autoconf.h ... done.
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/compat/main.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/main.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/core.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/sysfs.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/status.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/radiotap.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/driver-ops.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/util.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/reg.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/sta_info.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/scan.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/mvm/fw.o
  LD [M]  /var/lib/dkms/backport-iwlwifi/8324/build/compat/compat.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/xvt.o
In file included from /var/lib/dkms/backport-iwlwifi/8324/build/backport-include/linux/pci.h:3,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/mvm/../iwl-devtrace-io.h:17,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/mvm/../iwl-devtrace.h:94,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/mvm/../iwl-io.h:61,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/mvm/fw.c:70:
./include/linux/pci.h:85:45: error: ‘PCI_STD_NUM_BARS’ undeclared here (not in a function); did you mean ‘PCI_SRIOV_NUM_BARS’?
   85 |  PCI_STD_RESOURCE_END = PCI_STD_RESOURCES + PCI_STD_NUM_BARS - 1,
      |                                             ^~~~~~~~~~~~~~~~
      |                                             PCI_SRIOV_NUM_BARS
make[9]: *** [scripts/Makefile.build:268: /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/mvm/fw.o] Error 1
make[8]: *** [scripts/Makefile.build:505: /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/mvm] Error 2
make[8]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/user-infc.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/mlme.o
In file included from /var/lib/dkms/backport-iwlwifi/8324/build/backport-include/linux/pci.h:3,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/../iwl-devtrace-io.h:17,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/../iwl-devtrace.h:94,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/../iwl-io.h:61,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/xvt.c:76:
./include/linux/pci.h:85:45: error: ‘PCI_STD_NUM_BARS’ undeclared here (not in a function); did you mean ‘PCI_SRIOV_NUM_BARS’?
   85 |  PCI_STD_RESOURCE_END = PCI_STD_RESOURCES + PCI_STD_NUM_BARS - 1,
      |                                             ^~~~~~~~~~~~~~~~
      |                                             PCI_SRIOV_NUM_BARS
make[9]: *** [scripts/Makefile.build:268: /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/xvt.o] Error 1
make[9]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/ibss.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/wep.o
In file included from /var/lib/dkms/backport-iwlwifi/8324/build/backport-include/linux/pci.h:3,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/../iwl-devtrace-io.h:17,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/../iwl-devtrace.h:94,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/../iwl-io.h:61,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/user-infc.c:77:
./include/linux/pci.h:85:45: error: ‘PCI_STD_NUM_BARS’ undeclared here (not in a function); did you mean ‘PCI_SRIOV_NUM_BARS’?
   85 |  PCI_STD_RESOURCE_END = PCI_STD_RESOURCES + PCI_STD_NUM_BARS - 1,
      |                                             ^~~~~~~~~~~~~~~~
      |                                             PCI_SRIOV_NUM_BARS
make[9]: *** [scripts/Makefile.build:268: /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt/user-infc.o] Error 1
make[8]: *** [scripts/Makefile.build:505: /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi/xvt] Error 2
make[7]: *** [scripts/Makefile.build:505: /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel/iwlwifi] Error 2
make[6]: *** [scripts/Makefile.build:505: /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless/intel] Error 2
make[5]: *** [scripts/Makefile.build:505: /var/lib/dkms/backport-iwlwifi/8324/build/drivers/net/wireless] Error 2
make[5]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/sme.o
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c: In function ‘nl80211_prepare_wdev_dump’:
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:800:11: error: implicit declaration of function ‘genl_family_attrbuf’ [-Werror=implicit-function-declaration]
  800 |           genl_family_attrbuf(&nl80211_fam),
      |           ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:800:11: warning: passing argument 3 of ‘nlmsg_parse_deprecated’ makes pointer from integer without a cast [-Wint-conversion]
  800 |           genl_family_attrbuf(&nl80211_fam),
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |           |
      |           int
In file included from /var/lib/dkms/backport-iwlwifi/8324/build/backport-include/net/netlink.h:3,
                 from ./include/net/genetlink.h:6,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/backport-include/net/genetlink.h:3,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:24:
./include/net/netlink.h:702:22: note: expected ‘struct nlattr **’ but argument is of type ‘int’
  702 |       struct nlattr *tb[], int maxtype,
      |       ~~~~~~~~~~~~~~~^~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:808:6: warning: passing argument 2 of ‘__cfg80211_wdev_from_attrs’ makes pointer from integer without a cast [-Wint-conversion]
  808 |      genl_family_attrbuf(&nl80211_fam));
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |      |
      |      int
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:67:63: note: expected ‘struct nlattr **’ but argument is of type ‘int’
   67 | __cfg80211_wdev_from_attrs(struct net *netns, struct nlattr **attrs)
      |                                               ~~~~~~~~~~~~~~~~^~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c: In function ‘nl80211_dump_wiphy_parse’:
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:2432:23: warning: initialization of ‘struct nlattr **’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2432 |  struct nlattr **tb = genl_family_attrbuf(&nl80211_fam);
      |                       ^~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/aead_api.o
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c: In function ‘nl80211_dump_survey’:
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:8777:28: warning: initialization of ‘struct nlattr **’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 8777 |  struct nlattr **attrbuf = genl_family_attrbuf(&nl80211_fam);
      |                            ^~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/chan.o
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c: In function ‘nl80211_testmode_dump’:
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:9713:29: warning: initialization of ‘struct nlattr **’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 9713 |   struct nlattr **attrbuf = genl_family_attrbuf(&nl80211_fam);
      |                             ^~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/wpa.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/scan.o
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c: In function ‘nl80211_vendor_check_policy’:
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:13059:9: error: implicit declaration of function ‘nl80211_validate_nested’; did you mean ‘nla_validate_nested’? [-Werror=implicit-function-declaration]
13059 |  return nl80211_validate_nested(attr, vcmd->maxattr, vcmd->policy,
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         nla_validate_nested
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c: In function ‘nl80211_prepare_vendor_dump’:
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.c:13143:28: warning: initialization of ‘struct nlattr **’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
13143 |  struct nlattr **attrbuf = genl_family_attrbuf(&nl80211_fam);
      |                            ^~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/offchannel.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/ethtool.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/mesh.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/ap.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/trace.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/ocb.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/ht.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/agg-tx.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/pmsr.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/debugfs.o
  GEN     /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/shipped-certs.c
  GEN     /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/extra-certs.c
In file included from ./include/trace/define_trace.h:102,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/trace.h:3469,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/trace.c:8:
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/./trace.h:2054:21: error: expected expression before ‘;’ token
 2054 |   __field(u8, bands);
      |                     ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/./trace.h:2046:1: note: in expansion of macro ‘TRACE_EVENT’
 2046 | TRACE_EVENT(rdev_nan_change_conf,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/./trace.h:2050:2: note: in expansion of macro ‘TP_STRUCT__entry’
 2050 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/agg-rx.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/shipped-certs.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/extra-certs.o
make[6]: *** [scripts/Makefile.build:268: /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/trace.o] Error 1
make[6]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/vht.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/he.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/ibss.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/iface.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/rate.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/michael.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/tkip.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/aes_cmac.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/aes_gmac.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/fils_aead.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/cfg.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/ethtool.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/rx.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/spectmgmt.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/tx.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/key.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/util.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/wme.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/chan.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/trace.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/mlme.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/tdls.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/ocb.o
  CC [M]  /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/led.o
In file included from ./include/trace/define_trace.h:102,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/trace.h:2728,
                 from /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/trace.c:11:
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:411:31: error: expected expression before ‘;’ token
  411 |   __field(s32, cqm_rssi_thold);
      |                               ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:382:1: note: in expansion of macro ‘TRACE_EVENT’
  382 | TRACE_EVENT(drv_bss_info_changed,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:390:2: note: in expansion of macro ‘TP_STRUCT__entry’
  390 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1675:44: error: expected expression before ‘;’ token
 1675 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1663:1: note: in expansion of macro ‘TRACE_EVENT’
 1663 | TRACE_EVENT(drv_start_ap,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1670:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1670 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1675:44: error: initialization of ‘const char *’ from incompatible pointer type ‘struct trace_event_fields *’ [-Werror=incompatible-pointer-types]
 1675 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1663:1: note: in expansion of macro ‘TRACE_EVENT’
 1663 | TRACE_EVENT(drv_start_ap,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1670:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1670 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1675:44: note: (near initialization for ‘trace_event_fields_drv_start_ap[8].type’)
 1675 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1663:1: note: in expansion of macro ‘TRACE_EVENT’
 1663 | TRACE_EVENT(drv_start_ap,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1670:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1670 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1675:44: error: initializer element is not constant
 1675 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1663:1: note: in expansion of macro ‘TRACE_EVENT’
 1663 | TRACE_EVENT(drv_start_ap,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1670:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1670 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1675:44: note: (near initialization for ‘trace_event_fields_drv_start_ap[8].type’)
 1675 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1663:1: note: in expansion of macro ‘TRACE_EVENT’
 1663 | TRACE_EVENT(drv_start_ap,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1670:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1670 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
./include/trace/trace_events.h:442:64: warning: missing braces around initializer [-Wmissing-braces]
  442 | static struct trace_event_fields trace_event_fields_##call[] = { \
      |                                                                ^
./include/trace/trace_events.h:75:2: note: in expansion of macro ‘DECLARE_EVENT_CLASS’
   75 |  DECLARE_EVENT_CLASS(name,          \
      |  ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1663:1: note: in expansion of macro ‘TRACE_EVENT’
 1663 | TRACE_EVENT(drv_start_ap,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1742:44: error: expected expression before ‘;’ token
 1742 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1730:1: note: in expansion of macro ‘TRACE_EVENT’
 1730 | TRACE_EVENT(drv_join_ibss,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1737:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1737 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1742:44: error: initialization of ‘const char *’ from incompatible pointer type ‘struct trace_event_fields *’ [-Werror=incompatible-pointer-types]
 1742 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1730:1: note: in expansion of macro ‘TRACE_EVENT’
 1730 | TRACE_EVENT(drv_join_ibss,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1737:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1737 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1742:44: note: (near initialization for ‘trace_event_fields_drv_join_ibss[8].type’)
 1742 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1730:1: note: in expansion of macro ‘TRACE_EVENT’
 1730 | TRACE_EVENT(drv_join_ibss,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1737:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1737 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1742:44: error: initializer element is not constant
 1742 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1730:1: note: in expansion of macro ‘TRACE_EVENT’
 1730 | TRACE_EVENT(drv_join_ibss,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1737:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1737 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1742:44: note: (near initialization for ‘trace_event_fields_drv_join_ibss[8].type’)
 1742 |   __dynamic_array(u8, ssid, info->ssid_len);
      |                                            ^
./include/trace/trace_events.h:443:2: note: in definition of macro ‘DECLARE_EVENT_CLASS’
  443 |  tstruct        \
      |  ^~~~~~~
./include/trace/trace_events.h:78:9: note: in expansion of macro ‘PARAMS’
   78 |         PARAMS(tstruct),         \
      |         ^~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1730:1: note: in expansion of macro ‘TRACE_EVENT’
 1730 | TRACE_EVENT(drv_join_ibss,
      | ^~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1737:2: note: in expansion of macro ‘TP_STRUCT__entry’
 1737 |  TP_STRUCT__entry(
      |  ^~~~~~~~~~~~~~~~
./include/trace/trace_events.h:442:64: warning: missing braces around initializer [-Wmissing-braces]
  442 | static struct trace_event_fields trace_event_fields_##call[] = { \
      |                                                                ^
./include/trace/trace_events.h:75:2: note: in expansion of macro ‘DECLARE_EVENT_CLASS’
   75 |  DECLARE_EVENT_CLASS(name,          \
      |  ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/./trace.h:1730:1: note: in expansion of macro ‘TRACE_EVENT’
 1730 | TRACE_EVENT(drv_join_ibss,
      | ^~~~~~~~~~~
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:268: /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211/trace.o] Error 1
make[6]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:267: /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless/nl80211.o] Error 1
make[5]: *** [scripts/Makefile.build:505: /var/lib/dkms/backport-iwlwifi/8324/build/net/wireless] Error 2
make[5]: *** [scripts/Makefile.build:505: /var/lib/dkms/backport-iwlwifi/8324/build/net/mac80211] Error 2
make[4]: *** [Makefile:1708: /var/lib/dkms/backport-iwlwifi/8324/build] Error 2
make[3]: *** [Makefile.build:13: modules] Error 2
make[2]: *** [Makefile.real:100: modules] Error 2
make[1]: *** [Makefile:43: modules] Error 2
make: *** [Makefile:30: default] Error 2

**Comment by damentz** [comment]
Why are you _backporting_ iwlwifi into Liquorix?  Liquorix for the most part is the latest stable upstream.  The backport package will have either the same or older version at all times.

**Comment by damentz** [comment]
Closing issue, the solution is not to install backport package, it can only install an older or identical version of iwlwifi modules.

**Comment by CHJ85** [comment]
Thank you. You're right. I thought the package was related to the kernel. Sorry about that.
But I removed the package which I don't need anyway, and that fixed the problem.
