### ISSUE TITLE
Tick rate out of date on liquorix.net

### ISSUE THREAD

**Issue by topas-rec** [damentz/liquorix-package#35]
liquorix.net says:
"High Resolution Scheduling: High resolution timeouts for precise low jitter task scheduling. Threaded IRQs and RCU to reduce jitter caused by periodic tick at 250hz."

It seems currently a 1000Hz tick rate is targeted: https://github.com/damentz/liquorix-package/commit/46d514fdd666503c8fbb7c248991cf1da5931348

**Comment by damentz** [comment]
Good catch!  For a while I was experimenting with 250hz periodic versus 1000hz tickless idle, and I had to flip flop back and forth to verify that change wasn't causing new issues.  During that process I completely forgot to update the website.

The website is now updated with the correct information:
_High Resolution Scheduling: High resolution timeouts and 1000hz tick rate for precise low jitter task scheduling._

**Comment by topas-rec** [comment]
Perhaps not updating the website until a change is stable is a good idea. 😉

I found this because I noticed a positive effect of the 1000Hz setting. (That has to be further tested) More information can be found in my comments at the [Ardour forum](https://discourse.ardour.org/t/is-it-really-possible-to-get-down-to-0-xruns/88159).
[Comment 1](https://discourse.ardour.org/t/is-it-really-possible-to-get-down-to-0-xruns/88159/59)
[Comment 2](https://discourse.ardour.org/t/is-it-really-possible-to-get-down-to-0-xruns/88159/82)
