### ISSUE TITLE
liquorix patches for LTS kernel

### ISSUE THREAD

**Issue by mabod** [damentz/liquorix-package#37]
Would it be possible to provide a liquorix patchset for the 5.4 LTS kernel?

**Comment by damentz** [comment]
Hi mabod,

I don't use LTS kernels myself so I won't provide them.  Liquorix tracks the latest stable kernel and if there's a major issue, I work to get regressions patched ASAP.

If you need an LTS kernel, you're probably looking for maximum stability.  Liquorix (and by extension Zen Kernel), are not the right place to look if that's what your objective is.
