### ISSUE TITLE
What kernel config parameters are changed?

### ISSUE THREAD

**Issue by DBLouis** [damentz/liquorix-package#39]
Could you provide a list of the kernel config parameters that are changed please? (compared to the default config)

I am making package for this kernel for Void Linux and I want to make a new config file based on the one from Void, not replace it entirely by yours.

**Comment by damentz** [comment]
The Liquorix configuration has morphed over a long period of time, but forked from Sidux/Kanotix 10 years ago.  It no longer has no direct relationship with any major distribution.

I will say however, I do use Arch's configuration as a model for whenever I'm not sure how something should be configured.  If you run a diff between Arch's and Liquorix's, you're more likely to find important difference between "stock" and "optimized".

Maybe instead you should compare Arch and Arch's Zen Kernel.  It's maintained by the same package maintainer, so he keeps the configurations very similar.  Once you have those difference down, compare Arch's Zen Kernel to Liquorix.  That should get you a good idea of what's different from a "stock" distribution kernel.
