### ISSUE TITLE
Unable to import the 9AE4078033F8024D PGP key

### ISSUE THREAD

**Issue by unfa** [damentz/liquorix-package#43]
Hi!

I'm sorry - this is probably not the best place to report this, but I'm lost.
I'm trying to use Liquorix Arch repositories to install the Liquorix kernel.

It fails to import your PGP key:

```
sudo pacman -S linux-lqx
resolving dependencies...
looking for conflicting packages...

Packages (1) linux-lqx-5.8.9.lqx3-1

Total Installed Size:  313.52 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                                                    [####################################################################################################] 100%
downloading required keys...
:: Import PGP key 9AE4078033F8024D, "Steven Barrett <steven@liquorix.net>"? [Y/n] y
error: key "9AE4078033F8024D" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```

Is this a known problem?
How can I import his key?

Thanks!

**Comment by damentz** [comment]
Does this solve it? `sudo pacman-key --keyserver hkps.pool.sks-keyservers.net --recv-keys 9AE4078033F8024D && sudo pacman-key --lsign-key 9AE4078033F8024D`

It's straight from my instructions on the AUR: https://aur.archlinux.org/packages/linux-lqx/#pinned-763286

EDIT: I think the error you're getting is gpg attempting to import the key online, but no keyserver is configured so it fails immediately.  The command I posted in the pinned comment selects *hkps.pool.sks-keyservers.net* as the keyserver, a highly available, fast, and secure keyserver pool from sks-keyservers.net.
