### ISSUE TITLE
 Liquorix kernel (Real time) Error  v4l2loopback-dkms Module

### ISSUE THREAD

**Issue by samuk190** [damentz/liquorix-package#44]
sudo apt-get install v4l2loopback-dkms
returns error:
Building initial module for 5.8.0-16.1-liquorix-amd64
ERROR (dkms apport): kernel package linux-headers-5.8.0-16.1-liquorix-amd64 is not supported
Error! Bad return status for module build on kernel: 5.8.0-16.1-liquorix-amd64 (x86_64)

Please fix it :) 

v4l2loopback-dkms is important to make webcam with android device work

**Comment by damentz** [comment]
I'm assuming you're using Ubuntu 20.04, which has version 0.12.3 of this package.  Arch has 0.12.5 and builds successfully with kernel 5.8 series:

```
:: Processing package changes...
(1/1) installing v4l2loopback-dkms    [##############################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod -m v4l2loopback -v 0.12.5 -k 5.9.1-arch1-1
==> dkms install --no-depmod -m v4l2loopback -v 0.12.5 -k 5.8.16-lqx1-4-lqx
==> depmod 5.9.1-arch1-1
==> depmod 5.8.16-lqx1-4-lqx
```

I'd recommend upgrading your distro to a version that has 0.12.5 or higher.  And if you're using Ubuntu, 20.10 came out recently and is already running it: https://packages.ubuntu.com/groovy/v4l2loopback-dkms

**Comment by samuk190** [comment]
@damentz  yes, i'm using xubuntu and it didnt released yet, but I manually built from source, installed it on thje kernel and it worked, thnaks for the reply
