### ISSUE TITLE
W: Possible missing firmware /lib/firmware/rtl_nic/rtl8125b-2.fw for module r8169

### ISSUE THREAD

**Issue by djneba** [damentz/liquorix-package#45]
After installation of version 5.9xxx I get this warning:
W: Possible missing firmware /lib/firmware/rtl_nic/rtl8125b-2.fw for module r8169

The module should be in the kernel AFAIK.
No such warning on 5.8xxx.

Using Ubuntu 20.04.

**Comment by damentz** [comment]
Your warning is for firmware, not a module.  You can either upgrade Ubuntu to get it or get the firmware yourself here: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/rtl_nic/rtl8125b-2.fw

**Comment by djneba** [comment]
Thank you for helping me! This was the first time I've met with the problem.

**Comment by deltasata** [comment]
After downloading rtl8125b-2.fw what should I do? 
Ubuntu 5.11.x kernels are killing me since they does not let me install nvida driver! And with the igpu I can't use external monitor via hdmi!
The only warnings I find during kernel installation is the above.
