### ISSUE TITLE
Ubuntu 20.10 - zfs-0.8.4 DKMS wont buiild for 5.9.0-16.1-liquorix-amd64

### ISSUE THREAD

**Issue by IvanCharcos** [damentz/liquorix-package#47]
Any workarounds?

> Done.
> Loading new zfs-0.8.4 DKMS files...
> Building for 5.9.0-16.1-liquorix-amd64
> Building initial module for 5.9.0-16.1-liquorix-amd64
> configure: error: 
> 	*** None of the expected "global page state" interfaces were detected.
> 	*** This may be because your kernel version is newer than what is
> 	*** supported, or you are using a patched custom kernel with
> 	*** incompatible modifications.
> 	***
> 	*** ZFS Version: zfs-0.8.4-1ubuntu11
> 	*** Compatible Kernels: 2.6.32 - 5.6
> 	
> ERROR (dkms apport): kernel package linux-headers-5.9.0-16.1-liquorix-amd64 is not supported
> Error! Bad return status for module build on kernel: 5.9.0-16.1-liquorix-amd64 (x86_64)
> Consult /var/lib/dkms/zfs/0.8.4/build/make.log for more information.
> dpkg: error processing package zfs-dkms (--configure):
>  installed zfs-dkms package post-installation script subprocess returned error exit status 10
> Processing triggers for initramfs-tools (0.137ubuntu12) ...
> update-initramfs: Generating /boot/initrd.img-5.9.0-16.1-liquorix-amd64
> W: Possible missing firmware /lib/firmware/ast_dp501_fw.bin for module ast
> Errors were encountered while processing:
>  zfs-dkms
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 

/var/lib/dkms/zfs/0.8.4/build/make.log

> DKMS make.log for zfs-0.8.4 for kernel 5.9.0-16.1-liquorix-amd64 (x86_64)
> Fri Dec 25 10:37:19 AM MST 2020
> make: *** No targets specified and no makefile found.  Stop.

**Comment by damentz** [comment]
Unfortunately there probably isn't a solution specifically for Ubuntu.  They don't yet have an official package for ZFS 2.0.0: https://launchpad.net/ubuntu/+source/zfs-linux

You can try backporting the `hirsute` package, it may have compatibility for 5.9+.  Or you can try this unofficial PPA, but it only supports at the latest `focal`: https://launchpad.net/~jonathonf/+archive/ubuntu/zfs?field.series_filter=focal
