### ISSUE TITLE
ixgbe support

### ISSUE THREAD

**Issue by ben-burns** [damentz/liquorix-package#48]
Hi @damentz, just curious if there is any specific reason for not setting `CONFIG_IXGBE` or support for ixgbe by default?

E.g.:

```
CONFIG_IXGBE=m
CONFIG_IXGBE_HWMON=y
CONFIG_IXGBE_DCA=y
CONFIG_IXGBE_DCB=y
CONFIG_IXGBEVF=m
```

Cheers

**Comment by damentz** [comment]
No reason, looks like I just missed it.  Enabled that device and some others that I missed, and also enabled DCB where it was missing.  Will be in next update, probably when 5.10.5 drops.
