### ISSUE TITLE
System does not boot on OVH after kernel install

### ISSUE THREAD

**Issue by enmand** [damentz/liquorix-package#49]
I recently ran into an issue using Liquorix on an OVH bare metal machine.

OS: Ubuntu 18.04
Install method: PPA
Installed kernel: 5.10

After installing the kernel, the machine no longer boots, and isn't accessible via. SSH (and the IPMI shows a black screen).

Base config (base install, 4.15): https://gist.github.com/enmand/ed5a40ba23b12a033ba189293682dd96
Base config (after upgrading to linux-generic 5.4): https://gist.github.com/enmand/bfd1c41cf7d0b65010cc153a867bd9aa
lsmod / lspci: https://gist.github.com/enmand/0004db235d90c5faf3bfc5743092db30

**Comment by damentz** [comment]
Liquorix is not a server kernel, do not run Liquorix on a server unless you really know what you're doing and understand the tradeoffs and risks.

As for why it doesn't boot, it could could be anything, unfortunately.  Without getting a hook into the bare metal machine to see what it's doing, how it's beeping, and what the screen is doing, all you can really do at the moment is guess and ask OVH to reset it.
