### ISSUE TITLE
[Use Case Feedback] 5G Deployment notes

### ISSUE THREAD

**Issue by Matheus-Garbelini** [damentz/liquorix-package#57]
Hi @damentz just want to thank you on a use case for Liquorix kernel.
 
This kernel has been validated for a 4G/5G Deployment which requires low-latency and still some good performance.
In comparison, a the full RT-patch kernel is horrible performance-wise and was not able to keep up with 5G requirements.

The included acs-patch also tremendously helps in using 10gbps ethernet cards in SR-IOV mode which is required for radio access network deployment.

If you want more details/reference on the use case, we've used this kernel with [OpenAirInterface](https://gitlab.eurecom.fr/oai/openairinterface5g) project.
Keep up the good work :+1:  and feel free to close this issue.

**Comment by damentz** [comment]
Wow, that's good news!  Do you have any details on other kernels that passed or failed validation?  I'm curious where Liquorix stands in comparison to general distro kernels and other custom kernels that have been tested.

**Comment by Matheus-Garbelini** [comment]
Hi @damentz . I personally tested the following kernels:

* 5.11.11-xanmod1    - Result: Failed      (Thread scheduler delayed)
* 5.10.10-lowlatency  - Result: Failed     (Thread scheduler delayed)
* 5.10.21-rt24             - Result: Failed     (Thread scheduler delayed by a lot!)
* 5.11.0-liquorix          - Result: Success (Thread scheduler stable)

As you can see I do not have any other benchmark metric as this is something that either works all the time or not.
In case of 5.11.0-7.1-liquorix, the thread scheduling is never failing. I wonder if this is because of your CFS/MuQSS scheduler adjustments.

The situation for this one is pretty specific, if we use RT kernel, performance is affected too much that the processing thread is delayed. In the other hand, the other kernels had a higher latency which also made the processing thread miss timing targets. 
It seems Liquorix is on the best spot between low latency and performance trade-off.

Kernel parameters:
```bash
net.ifnames=0 biosdevname=0 default_hugepagesz=1G hugepagesz=1GB hugepages=8 hugepagesz=2MB hugepages=1024 intel_iommu=on mitigations=off kthread_cpus=0,1,2,3 irqaffinity=0,1,2,3 quiet splash
```

**Comment by mjeveritt** [comment]
FYI: A real-time kernel will provide no advantage over a regular kernel unless you code for the real-time features....
