### ISSUE TITLE
threadirqs cause weird system issues

### ISSUE THREAD

**Issue by bhechinger** [damentz/liquorix-package#61]
I would love to be able to enable threadirqs so I can set RT priority for my audio device.

However, when I boot with threadirqs enabled things get... weird. Things like FFADO Mixer can no longer attach to the audio device. The display manager will lock up (switching VTs away and back gets that going again) and so on.

Is there a way to diagnose why these things are happening with threadirqs enabled?

Thanks for all your great work, liquorix is an amazing kernel!

This is on Ubuntu Studio 21.04, btw.

```
11:50:32 in ~ [I] ➜ sudo inxi -b
System:    Host: deepthought Kernel: 5.12.0-19.3-liquorix-amd64 x86_64 bits: 64 Console: tty 2 
           Distro: Ubuntu 21.04 (Hirsute Hippo) 
Machine:   Type: Desktop System: ASUS product: N/A v: N/A serial: N/A 
           Mobo: ASUSTeK model: ROG CROSSHAIR VIII DARK HERO v: Rev X.0x serial: 210382746700526 UEFI: American Megatrends 
           v: 3601 date: 05/26/2021 
CPU:       Info: 16-Core AMD Ryzen 9 5950X [MT MCP] speed: 3609 MHz min/max: 2200/3400 MHz 
Graphics:  Device-1: NVIDIA driver: nvidia v: 460.91.03 
           Display: server: X.Org 1.20.11 driver: loaded: nvidia resolution: 2560x1440~144Hz 
           OpenGL: renderer: GeForce RTX 3080 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 460.91.03 
Network:   Device-1: Realtek RTL8125 2.5GbE driver: r8169 
           Device-2: Intel I211 Gigabit Network driver: igb 
           Device-3: Intel Wi-Fi 6 AX200 driver: iwlwifi 
Drives:    Local Storage: total: 2.26 TiB used: 540.74 GiB (23.4%) 
Info:      Processes: 637 Uptime: 23m Memory: 62.79 GiB used: 10.88 GiB (17.3%) Shell: Zsh inxi: 3.3.01 
```

**Comment by damentz** [comment]
Yep, for the most part threadirqs is an unsupported parameter.  The reason why is that not all drivers for hardware are written to the same quality, so although most hardware may work fine, the few that don't make the experience miserable.

The cherry on top is that MuQSS schedules work on cores differently than mainline CFS in a way that exacerbates the issue.  So if you run into any issues using threadirqs with a MuQSS based system, you're on your own.  However, if you can replicate the same issue on CFS, I'm sure the subsystem maintainer might be interested in a bug report.

And last, if your system works stably with threadirqs, then great!  You basically have a unique system where all the hardware has drivers compatible with threaded IRQs and you can benefit from that on your own system.

This is probably not the answer you're looking for, but if you're adamant to using threaded IRQs with your work, I'd first start with replicating on a mainline kernel and submitting a bug report from there.  I'm very sure that subsystem maintainers aren't too interested in bug reports coming from kernels with an alternative scheduler that they can't replicate on CFS.

**Comment by bhechinger** [comment]
Of course that's not the answer I'm looking for. You misspelled "This is how I fix your problem for you." :-D

So the interesting thing is that threadirqs is the default on Ubuntu Studio and it works flawlessly. It looks like the issue is threadirqs with MuQSS then. That's a real shame.

Thank you so much for your very informative response!

**Comment by damentz** [comment]
@bhechinger just following up, Liquorix 5.14 uses PDS which changes the behavior of the system quite a bit.  Things like `threadirqs` may work properly now.  Can you give it a test?

Note that `threadirqs` worked for me previously on MuQSS between an Intel and AMD Ryzen system, so your mileage may vary depending on your particular hardware.

**Comment by bhechinger** [comment]
Small snag with the upgrade.

While trying to install the nvidia drivers I get this:
```
Loading new nvidia-460.91.03 DKMS files...
Building for 5.14.0-6.2-liquorix-amd64
Building for architecture x86_64
Building initial module for 5.14.0-6.2-liquorix-amd64
ERROR (dkms apport): kernel package linux-headers-5.14.0-6.2-liquorix-amd64 is not supported
Error! Bad return status for module build on kernel: 5.14.0-6.2-liquorix-amd64 (x86_64)
Consult /var/lib/dkms/nvidia/460.91.03/build/make.log for more information.
```
[make.log](https://github.com/damentz/liquorix-package/files/7194494/make.log)

This is a bit of a show stopper. In the meantime, however, I'll see how threadirqs works with nouveau.

**Comment by bhechinger** [comment]
So far system seems stable (just booted so hard to say) and threadirqs is definitely working:

```
09:45:18 in ~ [I] ➜ /etc/init.d/rtirq status

    PID CLS RTPRIO  NI PRI %CPU STAT COMMAND
    558 FF      90   - 130  1.7 S    irq/24-firewire
   1634 FF      85   - 125  0.0 S    irq/124-snd_hda
   1635 FF      85   - 125  0.0 S    irq/126-snd_hda
    505 FF      80   - 120  0.0 S    irq/78-xhci_hcd
```

**Comment by bhechinger** [comment]
Ok, after some more testing and just general use I would like to report that everything is stable and xruns have dropped to zero so threadirqs is definitely working.

I'll open a new issue for the nvidia drivers which is still currently an issue.

**Comment by bhechinger** [comment]
Ok, I stand corrected. The audio stuff just locked up hard. Going to run without threadirqs a while and see if it happens (it really shouldn't)
