### ISSUE TITLE
Kernel 5.13 - bluetooth doesn't work

### ISSUE THREAD

**Issue by meijkl** [damentz/liquorix-package#63]
Great that you now also offer a 5.13 kernel for Debian :-)

Unfortunately bluetooth doesn't work properly (at least with Gnome, Cinnamon, XFCE) in contrast to the 5.12 version. 
At least with the Intel AX210 Wifi/Bluetooth adapter.

Symptoms:
- Adapter is present (lsusb shows the adapter)
- blueman can't find the adapter
- blueman-applet isn't loaded

Some selected messages from /var/log/syslog (last " ... Adapter is none" is probably the most important):

bluetoothd[5618]: src/profile.c:register_profile() :1.174 tried to register 00001108-0000-1000-8000-00805f9b34fb which is already registered
dbus-daemon[12151]: [session uid=1000 pid=12151] Activating via systemd: service name='org.blueman.Applet' unit='blueman-applet.service' requested by ':1.167' (uid=1000 pid=13876 comm="/usr/bin/python3 /usr/bin/blueman-tray")
blueman-mechanism[13884]: Unable to init server: Could not connect: Connection refused
gdm-x-session[13773]: blueman-applet 15.07.40 WARNING  PluginManager:148 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-mechani[13884]: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
blueman-mechanism[13884]: Unable to init server: Could not connect: Connection refused
/usr/libexec/gdm-x-session[13773]: blueman-applet 15.07.40 WARNING  DiscvManager:109 update_menuitems: warning: Adapter is None

I've also tested the Sparky Linux 5.13 kernel - there bluetooth works (but unfortunately the Elan 1200 touchpad of my Asus GL753 doesn't :-().

Looking forward to new kernel versions & thanks for your effort!
Klaus

**Comment by damentz** [comment]
This may be related to what happened in the forum thread here: https://techpatterns.com/forums/about2886.html

Basically with the upgrade to kernel 5.12, bluetooth randomly stopped working on very specific devices.  I personally use bluetooth across multiple devices and haven't had an issue myself, but that's just one anecdote.

The common link here is Debian, so I may look at their patches and config and see if there's anything worthwhile I can add to Liquorix regarding bluetooth.

**Comment by meijkl** [comment]
Thanks for checking my issue!
In my case v5.12 worked flawlessly and I would assume that the Intel AX210 is a mainstream Wifi/BT module although it is relatively new.
Today I could install the first v5.13 Debian kernel from the Experimental repo and it has the same problem - no BT. 
I've now checked three v5.13 kernels, the only kernel where BT currently works is the Sparky Linux variant.

**Comment by meijkl** [comment]
Just a short update - Bluetooth works with the current official 5.13 version from the Debian Experimental repo!

**Comment by damentz** [comment]
On a working system, can you provide the output of `inxi -ENxx`?

**Comment by meijkl** [comment]
At first - good news!
Bluetooth now works with your latest kernel (linux-image-liquorix-amd64  5.13-11.1~sid) which I could check today.

The inxi output with your latest kernel is:
$ inxi -ENxx
Network:   Device-1: Intel Wi-Fi 6 AX210/AX211/AX411 160MHz driver: iwlwifi v: kernel port: e000 bus-ID: 02:00.0 
           chip-ID: 8086:2725 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK driver: r8169 v: kernel port: d000 
           bus-ID: 03:00.0 chip-ID: 10ec:8168 
Bluetooth: Device-1: Intel AX210 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 1-9:4 chip-ID: 8087:0032 
           Report: hciconfig ID: hci0 rfk-id: 1 state: up address: 7C:50:79:3E:81:FD bt-v: 3.0 lmp-v: 5.2 sub-v: 3756 

Thanks for your effort!
Klaus

**Comment by damentz** [comment]
Very interesting, one of the stable updates must have fixed it.  Skimming through the last few patches, it's not obvious to me which one may be the reason why, so most likely bluetooth wasn't working due to some other lower level interaction.

Either way, glad it works now!  I'll mark this issue as resolved.
