### ISSUE TITLE
CONFIG_X86_SGX is not enabled

### ISSUE THREAD

**Issue by jarkkojs** [damentz/liquorix-package#64]
Liquorix kernel has CONFIG_X86_SGX, meaning that, I have to boot in-between stock Ubuntu and Liquorix kernel, since I sometimes use that kernel feature. To be better in line with the stock kernel features, can you possibly enable this option?

**Comment by damentz** [comment]
@jarkk0sakkinen Enabled as part of https://github.com/damentz/liquorix-package/commit/083590fd2ae39f830cf46005d6c71ff58e210aab, will be in next release.

**Comment by jarkkojs** [comment]
Thank you!
