### ISSUE TITLE
Can't install nvidia proprietary drivers with Liquorix 5.14

### ISSUE THREAD

**Issue by bhechinger** [damentz/liquorix-package#66]
I upgraded to 5.14 and I can no longer install the nvidia proprietary drivers:

```
Loading new nvidia-460.91.03 DKMS files...
Building for 5.14.0-6.2-liquorix-amd64
Building for architecture x86_64
Building initial module for 5.14.0-6.2-liquorix-amd64
ERROR (dkms apport): kernel package linux-headers-5.14.0-6.2-liquorix-amd64 is not supported
Error! Bad return status for module build on kernel: 5.14.0-6.2-liquorix-amd64 (x86_64)
Consult /var/lib/dkms/nvidia/460.91.03/build/make.log for more information.
```

[make.log](https://github.com/damentz/liquorix-package/files/7194494/make.log)

This is a bit of a show stopper because nouveau isn't usable for anything requiring actual performance out of the video card.

**Comment by damentz** [comment]
It looks like this is a known issue.  The fix is to upgrade or apply a patch yourself if you have the means to:

https://bbs.archlinux.org/viewtopic.php?id=268421

As of  470.63.01, it looks like no patch is required to build on 5.14: https://archlinux.org/packages/extra/x86_64/nvidia/

**Comment by bhechinger** [comment]
Bah, 470 just gives me a black screen at login. I'll try the patch thing with 460. Thanks for the help!

**Comment by bhechinger** [comment]
I'll just wait for 470.74 to hit the graphics ppa and try again. If I can't game on Linux for the next couple of days that's fine.

**Comment by bhechinger** [comment]
Quick update for you: 470.63 is a black screen no matter what I do. I just installed 470.74 via the file download from nvidia and installed it and it works perfectly!
