### ISSUE TITLE
amdgpu firmware missing

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [damentz/liquorix-package#69]
`W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_gpu_info.bin for m
odule amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_gpu_info.bin for modul
e amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_gpu_info.bin for modu
le amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_ta.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_sos.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_toc.bin for module amd
gpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_asd.bin for module amd
gpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_ta.bin for module amd
gpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_asd.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_sos.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_ta.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_toc.bin for module
 amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_asd.bin for module
 amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_ta.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_sos.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_rlc.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_mec2.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_mec.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_rlc.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_mec.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_rlc.bin for module
 amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_mec2.bin for modul
e amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_mec.bin for module
 amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_me.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_pfp.bin for module
 amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_ce.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_rlc.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_mec2.bin for module
 amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_mec.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_me.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_pfp.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_ce.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_rlc.bin for module amd
gpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_mec2.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_mec.bin for module amd
gpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_me.bin for module amdg
pu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_pfp.bin for module amd
gpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_ce.bin for module amdg
pu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_sdma.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_sdma.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_sdma.bin for modul
e amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_sdma.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_sdma.bin for module
 amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sienna_cichlid_mes.bin for mod
ule amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/navi10_mes.bin for module amdg
pu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_vcn.bin for module
 amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_vcn.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_vcn.bin for module amd
gpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_vcn.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_vcn.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_smc.bin for module 
amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/arcturus_smc.bin for module am
dgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_smc.bin for module a
mdgpu
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_dmcub.bin for modu
le amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/beige_goby_dmcub.bin for modul
e amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_dmcub.bin for module a
mdgpu
`
these modules have been missing since kernel 5.14.0-8.1, ubuntu launched with software rendering
and since kernel 5.14.0-9.1 I wasn't able to boot
5.14.0-7.1 works like a charm

**Comment by damentz** [comment]
It seems that you never installed the AMDGPU firmware, and this is the first kernel release that refuses to boot without them.

Install AMDGPU firmware through your distribution's packages.  If they are out of date or missing in your distro, manually download and install them to `/lib/firmware/amdgpu` from here: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu

**Comment by Etaash-mathamsetty** [comment]
> It seems that you never installed the AMDGPU firmware, and this is the first kernel release that refuses to boot without them.
> 
> Install AMDGPU firmware through your distribution's packages. If they are out of date or missing in your distro, manually download and install them to `/lib/firmware/amdgpu` from here: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu

any help with that, I have never done this before, im using ubuntu btw
does the amdgpu-dkms-firmware package work?
I think I figured it out

**Comment by Etaash-mathamsetty** [comment]
problem: 
the files are there on 5.14.0-7.1
so how am I supposed to put them into the new kernel?
edit: seems like I have old amdgpu firmware

**Comment by damentz** [comment]
Right, Liquorix doesn't include any firmware.  In-fact, most firmware has a license that prevents distribution with the kernel, so it would actually be illegal for me to include AMDGPU firmware, as far as I'm aware.

You didn't include what your distribution is, but all I can recommend is upgrading to the latest stable version of whatever you're using.  Old frozen distributions have old firmware.  Eventually the firmware is so old that it's incompatible with latest version of Liquorix.

In absence of that, you can manually download latest firmware and add or replace what's on your filesystem.

**Comment by Etaash-mathamsetty** [comment]
Thanks,
now its bricked

**Comment by Etaash-mathamsetty** [comment]
the way you can fix this is by updating to ubuntu 21.10 or using debian firmware

**Comment by damentz** [comment]
Locked and deleted needless comments.  OP posted some follow-up "solutions" that are really bad and are not recommended.  This issue receives an unusual amount of traffic, per GitHub insights, so cleanup is necessary so as not to steer people with the same issue the wrong way.

My final comment above still stands as the correct solution, upgrade your distribution so as to receive latest firmware, or download the firmware manually to replace the old firmware from official sources.
