### ISSUE TITLE
Any ETA on Liquorix Kernel 5.15?

### ISSUE THREAD

**Issue by serialpotato** [damentz/liquorix-package#73]
Hi,

Any ETA when can we have liquorix kernel based on 5.15 kernel? 5.15.5 has already been out.

**Comment by damentz** [comment]
Is your system not getting updates?  5.15 has been out for a week.  Check tags here: https://github.com/damentz/liquorix-package/tags

Debian, Ubuntu, and Arch are all receiving updates on each new tag.

**Comment by serialpotato** [comment]
Yeah, its weird. I keep track of updates using the changelog and for some reason, it hadn't been updated for a while. Must be due to browser cache or something.
