### ISSUE TITLE
Kernel 5.16

### ISSUE THREAD

**Issue by serialpotato** [damentz/liquorix-package#76]
Hi, will we get 5.16 liquorix release anytime soon?

**Comment by damentz** [comment]
I typically wait a few stable releases for three reasons:
1. Sometimes the latest dot zero version has some major bug that affects a lot of people that wasn't caught during RC testing
2. Not all of our patches from the previous kernel are ported to the new kernel yet (for example: https://gitlab.com/alfredchen/linux-prjc/-/issues/47)
3. Major DKMS packages (nvidia comes to mind), need to be updated in their respective repos.

It takes about 2 weeks for all of the above to become clear, so for me it's the least effort to stick with stable updates of the previous kernel for a couple of weeks and then see what the state of things are then.

**Comment by damentz** [comment]
A kernel 5.16 version was released yesterday, closing.
