### ISSUE TITLE
updating to kernel 5.15.0-14.1-liquorix-amd64 has this power_meter issue

### ISSUE THREAD

**Issue by amsaal** [damentz/liquorix-package#77]
an 15 14:31:22 ns3119736 kernel: ipmi_si dmi-ipmi-si.0: IPMI kcs interface initialized
Jan 15 14:31:22 ns3119736 kernel: ISO 9660 Extensions: Microsoft Joliet Level 3
Jan 15 14:31:22 ns3119736 kernel: ISO 9660 Extensions: RRIP_1991A
Jan 15 14:31:22 ns3119736 kernel: power_meter ACPI000D:00: Found ACPI power meter.
Jan 15 14:31:22 ns3119736 kernel: power_meter ACPI000D:00: hwmon_device_register() is deprecated. Please convert the driver to use hwmon_device_register_with_info().
Jan 15 14:31:22 ns3119736 kernel: NET: Registered PF_PACKET protocol family
Jan 15 14:31:22 ns3119736 kernel: power_meter ACPI000D:00: Found ACPI power meter.
Jan 15 14:31:22 ns3119736 kernel: power_meter ACPI000D:00: Ignoring unsafe software power cap!
Jan 15 14:31:22 ns3119736 kernel: random: crng init done
Jan 15 14:31:22 ns3119736 kernel: igb 0000:04:00.0 eno1: igb: eno1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX

**Comment by damentz** [comment]
I don't believe there's any issue here, closing.
