### ISSUE TITLE
ubuntu 21.10 not booting with liquorix-package

### ISSUE THREAD

**Issue by alitoos23** [damentz/liquorix-package#78]
hello 
i install liquorix kernel on ubuntu 21.10 but it can not booting 
boot process stop on ata3 errors 
CPU: g2020 intel
motherboard:  H61MA-D2V
i have two hard disk
sata1: 240 Western Digital SSD which ubuntu installed on it
sata2: 2000 HDD

![3](https://user-images.githubusercontent.com/30020564/150952205-f1ab6bf1-b07d-4f5f-bfcb-63d5df7602f7.jpg)
![2](https://user-images.githubusercontent.com/30020564/150952222-9b7affd1-13ec-49d7-8444-9acd476e7b15.jpg)
![4](https://user-images.githubusercontent.com/30020564/150952234-2b152fb6-358a-4ab9-aab1-91d582c45fb2.jpg)
![1](https://user-images.githubusercontent.com/30020564/150952244-657992ff-cfdc-4b60-8f77-73bbeeb0044a.jpg)

**Comment by damentz** [comment]
Looks like some type of bad interaction with MG-LRU.  However, considering 5.15 is near end of life, I'm not sure if this is worth doing anything about until I rebase Liquorix to kernel 5.16 with a more mature patch set.

I'll keep this open and remind you once a new version is out that may fix it.

**Comment by damentz** [comment]
Can you try the latest 5.16 kernel?  Should be package version `5.16-2`, kernel version `5.16.0-4.2`.

**Comment by alitoos23** [comment]
very thanks . 
it work very well 😀️

**Comment by damentz** [comment]
Great!  Closing issue.
