### ISSUE TITLE
Revert kernel version or install specific version

### ISSUE THREAD

**Issue by serialpotato** [damentz/liquorix-package#79]
Hi, how do I install a specific kernel?

The latest 5.16 kernel has btrfs bug which left me no choice but to downgrade kernel to 5.15. Currently, I have 5.16 liquorix which I install using following command:

sudo apt-get install linux-image-liquorix-amd64 linux-headers-liquorix-amd64

After remove 5.16 kernel, how do I specify the 5.15 kernel in above installation command?

**Comment by damentz** [comment]
The bug you're referencing is already fixed in the latest Liquorix version (5.16-2, 5.16.0-4.2, v5.16.4.lqx2-1).  It includes RC patches from 5.16.5 that fixes btrfs's autodefrag feature.  And if you don't use autodefrag with btrfs, then you wouldn't have been affected anyways.

Patch: https://github.com/zen-kernel/zen-kernel/releases/tag/v5.16.4-lqx2

```
4a95f8fc6c61 btrfs: update writeback index when starting defrag
69e32e3b4bc8 btrfs: add back missing dirty page rate limiting to defrag
b23ceba49dec btrfs: fix deadlock when reserving space during defrag
87f327d1197e btrfs: defrag: properly update range->start for autodefrag
17c18abd6523 btrfs: defrag: fix wrong number of defragged sectors
901cbf4d2c50 btrfs: allow defrag to be interruptible
f3e2900edf2a btrfs: fix too long loop when defragging a 1 byte file
```

**Comment by serialpotato** [comment]
It has not been fixed yet. On liquorix 5.16, I checked btrfs transaction process which had quite a high write rate. The same has been reported here:

https://forum.endeavouros.com/t/psa-linux-5-16-has-major-regression-in-btrfs-causing-extreme-io-load/23446/4

My btrfs partition was mounted with default flag on ubuntu 20. Upon reverting to 5.15 xanmod, I no longer have this issue. I would love to get back on liquorix as it is much snappier but I don't know how to install specific version.

**Comment by damentz** [comment]
I don't keep binary archives of previous versions around due its cost prohibitive nature.  However, you can clone the AUR and build the last 5.15 version considering you're on an Arch distro:

```
git clone https://aur.archlinux.org/linux-lqx.git/ && cd linux-lqx
git reset --hard 070d0af299fccacbc11f876e8e79e1287f9dbf96
makepkg -si
```

**Comment by serialpotato** [comment]
Thank you. I am on ubuntu and can see packages here specific to focal/20. Guess I should just install these:

http://ppa.launchpad.net/damentz/liquorix/ubuntu/pool/main/l/linux-liquorix/

Edit: Figured it out. Used "apt-cache search linux-image" to search for all the available kernel files. And then used the set of header and images which had same release version. It worked. Thank you!

**Comment by damentz** [comment]
Ah, I figured you were an Arch user when you linked the EndeavourOS forum thread.  And you are correct, I usually keep a few versions back after a major release so anyone on Ubuntu has the chance to restore if something is wrong with the new major version.
