### ISSUE TITLE
ashmem and binder module is supported by liquorix ? 

### ISSUE THREAD

**Issue by alitoos23** [damentz/liquorix-package#80]
my goal of install liquorix kernel only install binder & ashmem module for anbox(because its based on Zen kernel )
is ashmem & binder module builded by default in liquorix ?
how i can enable these ?

**Comment by damentz** [comment]
Why don't you install Liquorix and find out?  By the time I answered your question you could have already found out.  Also, you can also simply look at the configuration yourself and compare it against what Anbox recommends.
