### ISSUE TITLE
ultra KSM (uksm)

### ISSUE THREAD

**Issue by fixerivan** [damentz/liquorix-package#83]
Hi, loving your kernel but missing KSM / UKSM

https://github.com/dolohow/uksm

could be very interesting for a lot of people having UKSM in liquorix as there is no prebuild kernel that i am aware of with UKSM enabled / build-in

thx!

**Comment by damentz** [comment]
I don't think I'll be merging that patch set.  UKSM has always been incredibly unstable on every instance it was merged into Zen Kernel.  Typically days within merging, we'd receive reports of unusual stack traces with UKSM in the center of it.

Looking at current issues on that project, there's a report from February 1st that UKSM is crashing one person's kernel: https://github.com/dolohow/uksm/issues/76

Needless to say, I won't be merging UKSM into Liquorix or Zen Kernel.
