### ISSUE TITLE
Merge "Transpose the sched_rq_watermark array" for PDS (Project C)

### ISSUE THREAD

**Issue by xalt7x** [damentz/liquorix-package#87]
I've found promising experimental MR from  Torge Matthies ([openglfreak](https://github.com/openglfreak)) - "[Transpose the sched_rq_watermark array](https://gitlab.com/alfredchen/linux-prjc/-/merge_requests/11)".  Not sure about drawbacks but It greatly improves performance on my machines

**Comment by damentz** [comment]
Thanks, merged to Zen Kernel: https://github.com/zen-kernel/zen-kernel/commit/5741b0010893c13ee5af95c55412032442100191

Will be in the next Liquorix release.

**Comment by xalt7x** [comment]
There's a new small commit - [Add memory barriers around atomics](https://gitlab.com/alfredchen/linux-prjc/-/commit/e299e2db)

**Comment by damentz** [comment]
Thanks again, merged to 5.16/master: https://github.com/zen-kernel/zen-kernel/commit/b284fb8af93723c68973922e1341cb919ea5fcf3

Also, I subscribed to notifications on his merge request so I can get updates going forward.  I'll do the same for contributors' forks.
