### ISSUE TITLE
[Request] Add xt_cgroup kernel module

### ISSUE THREAD

**Issue by glitsj16** [damentz/liquorix-package#9]
Hi, I'm testing this kernel on Ubuntu (16.04 LTS) using packages from [the liquorix PPA](https://launchpad.net/~damentz/+archive/ubuntu/liquorix). So far all seems to run very smoothly indeed. The only issue that's keeping me from using this as my daily driver is related to a bypass-VPN script I've been using on Arch Linux/ stock Ubuntu kernels for quite some time. [The script relies heavily on cgroups](https://gist.github.com/level323/54a921216f0baaa163127d960bfebbf0) to run processes in a custom network environment.

After comparing kernel configs, I believe to have found the reason why it doesn't work on the liquorix kernel. Contrary to stock Ubuntu kernels, liquorix misses the `xt_cgroup` kernel module (which seems to be critical for the aforementioned script). All relevant files in this wonderful repository have `# CONFIG_NETFILTER_XT_MATCH_CGROUP is not set`:
- [arch-32](https://github.com/damentz/liquorix-package/blob/master/linux-liquorix/debian/config/kernelarch-x86/config-arch-32#L1177);
- [arch-32-pae](https://github.com/damentz/liquorix-package/blob/master/linux-liquorix/debian/config/kernelarch-x86/config-arch-32-pae#L1205);
- [arch-64](https://github.com/damentz/liquorix-package/blob/master/linux-liquorix/debian/config/kernelarch-x86/config-arch-64#L1212).

Would it be too much trouble/contrary to the project's goals to add the `xt_cgroup` module to the liquorix kernels (by flipping on `CONFIG_NETFILTER_XT_MATCH_CGROUP=m`)?

Regards

**Comment by damentz** [comment]
That shouldn't be a problem, I'll make the change ahead of the next 4.18 sync and it should be in the next release.

**Comment by glitsj16** [comment]
Thank you for adding this. Looking forward to the next release.

Regards
