### ISSUE TITLE
Request to retain liquorix releases in ubuntu repository for old kernels

### ISSUE THREAD

**Issue by serialpotato** [damentz/liquorix-package#91]
Hi,

I really love liquorix for bleeding edge kernels. I have always preferred it over alternatives due to better real world performance.

I was wondering if its possible to not delete the old liquorix releases from the ubuntu repository, or at the very least keep the final/last variation/release. I know maintaining several branch with latest patches would not be practicable, hence, I am only requesting to retain a copy of the last liquorix release for a particular kernel version. Example, 5.16-27.1 for 5.16, 5.15-22.1 for 5.15, etc. As of writing this request, I am unable to find 5.16-27.1 for my ubuntu distribution (20.04), and upon searching the repository, I can only find the 5.17 releases.

The reason I request this is that at times when the new kernel is released, there still are issues/bugs that have not been discovered/ironed out in early variations till the kernel has matured. Further, there are linux packages which are more compatible/optimized for a specific kernel due to slow development. During times like these, I would love to have the flexibility of moving back and forth to new and old kernels, for better performance.

**Comment by damentz** [comment]
Hi @serialpotato, I think if you need to have an old kernel, it's easier to just build it for yourself.  Old binaries may no longer be optimal as the underlying repository it was originally built for changes.

One person recently had that need and figured out how to build it themselves using the supplied scripts of this repository: https://techpatterns.com/forums/about2939.html

I'll be eventually adding documentation to the main repo with instructions for how to do that, but in the meantime, I recommend building the kernel from the branch you need using the guide from the link above.
