### ISSUE TITLE
Huge battery consumption during s2idle

### ISSUE THREAD

**Issue by dionorgua** [damentz/liquorix-package#92]
It looks like debian unstable package (5.17.0-5.2-liquorix-amd64) eats battery during suspend. I'm trying it on HP EliteBook 850 G7 (Intel). At the same time distro kernel (linux-image-5.17.0-1-amd64      5.17.3-1) works as expected.

I've tried to follow manual:
https://01.org/blogs/qwang59/2018/how-achieve-s0ix-states-linux

And found that liquorix kernel never goes deeper than C3 state. 
Tried to add `intel_pstate=enable hpet=enable` to kernel parameters (because they are disabled in CONFIG_CMDLINE and acpi-cpufreq is used). but it doesn't help.

Any suggestions what else to check?

[liqorix.txt](https://github.com/damentz/liquorix-package/files/8686712/liqorix.txt)
[distro.txt](https://github.com/damentz/liquorix-package/files/8686713/distro.txt)

**Comment by damentz** [comment]
Have you used the s0ix self test tool to verify your system does work? https://github.com/qwang59/S0ixSelftestTool

Other than that, there have been some stable upstream ACPI/PM patches that may impact your system.  No other changes have been made to power management since 5.17.2 based kernels.

Can you verify that Debian's own mainline kernel is affected or not?

**Comment by dionorgua** [comment]
I'm 100% sure that debian kernel works and liquorix doesn't. And this happens not only with 5.17 kernels, but a few older releases (at least 5.16 and 5.15). So I think it's not question of a few stable 5.17.x patches.

As about S0ixSelftestTool: just tried it right now with debian mainline kernel and liquorix (linux-image-5.17.0-7.1-liquorix-amd64   5.17-11.1~sid). 

**Debian mainline:** Congratulations! Your system achieved S2idle S0ix residency: 0.09
**liquorix:** Your system achieved PC3 residency: 84.67, but no PC8 residency during S2idle: 0.00

So I think it's something related to patches in liquorix kernel or it's config. And this was actually a reason why I've tried to restore `intel_pstate=enable hpet=enable`. But without luck.

I'm attaching full output of `./s0ix-selftest-tool.sh -s` for both debian and liquorix kernel. Two files for liquorix: one with thunderbolt dock connected, another without. 

[liquorix-s-2.txt](https://github.com/damentz/liquorix-package/files/8697699/liquorix-s-2.txt)
[liquorix-s.txt](https://github.com/damentz/liquorix-package/files/8697700/liquorix-s.txt)
[debian-s.txt](https://github.com/damentz/liquorix-package/files/8697701/debian-s.txt)

**Comment by damentz** [comment]
The common theme in the liquorix files is this section:

```
The link power management state of PCIe bridge: 0000:00:1c.0 is not expected. 
which is expected to be L1.1 or L1.2, or user would run this script again.
```

Maybe ASPM is busted?  Check `sudo dmesg | grep -i aspm` for anything unusual.  Also, try adding `pcie_aspm=force` to your kernel boot parameters to force the kernel to allow management of PCI power management, regardless of what the kernel decides at boot time.

EDIT: In the original liquorix.txt document (your kernel logs), it appears that your system does support ASPM:
```
ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-7e])
acpi PNP0A08:00: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI EDR HPX-Type3]
acpi PNP0A08:00: _OSC: platform does not support [AER]
acpi PNP0A08:00: _OSC: OS now controls [PCIeHotplug SHPCHotplug PME PCIeCapability LTR DPC]
```

**Comment by dionorgua** [comment]
Tried `pcie_aspm=force` without any luck. Plus tried latest `liquorix-package`. I'm going to try building `liquorix` myself using config from debian kernel. Will post here results if any

**Comment by damentz** [comment]
Is this issue still present on the kernel 5.18 releases?

**Comment by dionorgua** [comment]
Yes. Still same thing with followed kernels:
`linux-image-5.18.0-9.1-liquorix-amd64   5.18-8.1~sid`
`linux-image-5.18.0-2-amd64      5.18.5-1`

Still no PC8 for liquorix and works with debian kernel.

**Comment by damentz** [comment]
It appears that the ASPM performance configuration at the kernel level may be the reason PC10 is not achievable.  I also ran into the same issue when testing on a laptop of mine.

A new kernel is out that leaves the PCIe ASPM settings at BIOS defaults, on a ThinkPad X1 7th gen, I'm able to achieve at least PC10, but not s2idle:
```
$ sudo ./s0ix-selftest-tool.sh -s

...

CPU%c1  CPU%c6  CPU%c7  GFX%rc6 Pkg%pc2 Pkg%pc3 Pkg%pc6 Pkg%pc7 Pkg%pc8 Pkg%pc9 Pk%pc10 SYS%LPI
0.71    0.69    98.06   426.60  1.87    4.92    0.07    0.00    0.00    0.00    89.94   0.00
0.62    0.74    97.91   426.60  1.87    4.92    0.07    0.00    0.00    0.00    89.94   0.00
0.93
0.42    0.69    98.02
1.05
0.45    0.49    98.01
1.16
0.44    0.86    98.28
0.63

CPU Core C7 residency after S2idle is: 98.06
GFX RC6 residency after S2idle is: 426.60
CPU Package C-state 2 residency after S2idle is: 1.87
CPU Package C-state 3 residency after S2idle is: 4.92
CPU Package C-state 8 residency after S2idle is: 0.00
CPU Package C-state 9 residency after S2idle is: 0.00
CPU Package C-state 10 residency after S2idle is: 89.94
S0ix residency after S2idle is: 0.00

...
```

Apparently physical hardware prevents S0ix residency, so there's nothing else I can do software wise.  Can you update your kernel to latest Liquorix and try again?

**Comment by damentz** [comment]
Marking as resolved, let me know if you're still having issues.

**Comment by dionorgua** [comment]
Hi,
Forgot to update. Just there was no time to test/check it. Now I can confirm that there is no such problem with kernel 5.19-liquorix
