### ISSUE TITLE
package fails to validate unless i add the repo for aur

### ISSUE THREAD

**Issue by LethalManBoob** [damentz/liquorix-package#93]
as title says. i also need to install it via the prebuilt aur binary before being able to build it manually.

**Comment by damentz** [comment]
I'm not understanding the issue here.  What what is "validation"?  Are you following instructions on the sticky at the top of the AUR page?

It also sounds like the problem is now solved since you can now build manually if that's what you want to do.

**Comment by LethalManBoob** [comment]
Its concerning to me becuase im not sure if the manual kernel overrides the prebuilt. Anyway this is what happens without any modifications beforehand.

archlinux% paru linux-lqx
3 aur/linux-lqx-docs 5.17.12.lqx1-1 [+144 ~1.92]
    Documentation for the Linux Liquorix kernel
2 aur/linux-lqx-headers 5.17.12.lqx1-1 [+144 ~1.92]
    Headers and scripts for building modules for the Linux Liquorix kernel
1 aur/linux-lqx 5.17.12.lqx1-1 [+144 ~1.92]
    The Linux Liquorix kernel and modules
:: Packages to install (eg: 1 2 3, 1-3):
:: 1 2 3
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) linux-lqx-5.17.12.lqx1-1 (linux-lqx linux-lqx-docs linux-lqx-headers)

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 (1/1) linux-lqx-5.17.12.lqx1-1 (linux-lqx linux-lqx [------------------------------------------------------------------------]
:: Proceed with installation? [Y/n]: y
fetching devel info...
error: can't build linux-lqx-5.17.12.lqx1-1 (linux-lqx linux-lqx-docs linux-lqx-headers), deps not satisfied: linux-lqx  linux-lqx
error: packages failed to build: linux-lqx-5.17.12.lqx1-1 (linux-lqx linux-lqx-docs linux-lqx-headers)
archlinux%

**Comment by damentz** [comment]
Oh I think I understand now, Paru doesn't know how to handle identical AUR and binary packages from a repo.

Maybe submit them an issue and say it should prefer binaries over AUR when available?  I use Trizen myself and it works well with chaotic-aur, the poster child of mixed binary AUR sources.

**Comment by LethalManBoob** [comment]
Yeah turns out because lqx is actually 3 in one (docs, headers and base) but the aur recognizes 3 different packges. Trying to install both causes the error. Maybe put a citation in the description that appears in the aur if you cant fix this or nether can paru.

**Comment by LethalManBoob** [comment]
Turns out the issue is even worse. https://aur.archlinux.org/linux-lqx.git fails to boot at all on archlinux. Only the prebuilt works.

**Comment by damentz** [comment]
> Turns out the issue is even worse. https://aur.archlinux.org/linux-lqx.git fails to boot at all on archlinux. Only the prebuilt works.

That probably means your environment is tainting the build, producing a corrupt artifact.  The prebuilt comes from a clean room containerized build with stock Arch Linux settings.

As for Paru, I'll take the stance of Arch Linux itself.  The only AUR helper supported is `makepkg`.  Any bugs you find with applications besides that need to be reported to that tool's issue tracker.  This is not a Liquorix package issue.

**Comment by LethalManBoob** [comment]
Thats very strange becuase no other linux kernel ive compiled has ever had this issue and, once again, if i download lqx via the prebuilt repo i can then compile and boot without issues. 

Is there anyway I can diagnose this?
