### ISSUE TITLE
r8168-dkms module is not compatible with Liquorix

### ISSUE THREAD

**Issue by Conobi** [damentz/liquorix-package#94]
Hey,
And thanks for your hard work on Liquorix.
I'm currently using a B450 Gaming K4 motherboard, with a RTL8111/8168/8411 Realtek Ethernet Controller. This chip requires the r8168-dkms module to work (on Ubuntu), but Liquorix is flagged as incompatible with this module ; installing r8168-dkms clears liquorix from the computer.
It is quite weird, since the [r8168 module](https://github.com/mtorromeo/r8168) works really well with Liquorix when compiling and installing manually, but each time I update Liquorix, it'll delete the module and remove ethernet from my computer.
Would it be possible to get a solution to make Liquorix works with this module?
Thanks!

**Comment by damentz** [comment]
What version of Ubuntu are you running?

Also, picking any version of this package from Ubuntu says its only dependency is `dkms` itself.  What output are you getting when you try to install this package? https://packages.ubuntu.com/jammy/r8168-dkms

**Comment by Conobi** [comment]
I'm currently running Ubuntu 22.04 LTS, but I can confirm that I had this issue for Ubuntu 21.10 and Ubuntu 21.04 too (and maybe 20.04, not sure about that).
Installing `r8168-dkms` will produce the following:
```
❯ LANG=C sudo apt install r8168-dkms
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  hwinfo libelf-dev libhd21 libobjc-10-dev libperl5.32 libpython3.9
  libpython3.9-minimal libpython3.9-stdlib libstdc++-10-dev libx86emu3
  perl-modules-5.32
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  linux-headers-5.17.0-12.1-liquorix-amd64 linux-headers-liquorix-amd64
  linux-image-5.17.0-12.1-liquorix-amd64 linux-image-liquorix-amd64
The following NEW packages will be installed:
  r8168-dkms
0 upgraded, 1 newly installed, 4 to remove and 16 not upgraded.
Need to get 106 kB of archives.
After this operation, 429 MB disk space will be freed.
Do you want to continue? [Y/n]
```
And then:
![image](https://user-images.githubusercontent.com/5563277/171863020-5d52ef79-88ac-45d3-916b-766533765218.png)
It then remove the kernel, and try to installs the `r8168-dkms` module:
```
Loading new r8168-8.049.02 DKMS files...
Building for 5.17.0-12.1-liquorix-amd64
Module build for kernel 5.17.0-12.1-liquorix-amd64 was skipped since the
kernel headers for this kernel does not seem to be installed.
Traitement des actions différées (« triggers ») pour initramfs-tools (0.140ubuntu13) ...
update-initramfs: Generating /boot/initrd.img-5.15.0-33-generic
I: The initramfs will attempt to resume from /dev/sdc4
I: (UUID=746d737d-6c0a-4bf0-be84-aabb6bd19edf)
I: Set the RESUME variable to override this.
```

Howewer, it looks like Liquorix is showing as conflicting with r8168-dkms module, in the debian package [template headers](https://github.com/damentz/liquorix-package/blob/5.17/master/linux-liquorix/debian/templates/control.headers.in) and [image](https://github.com/damentz/liquorix-package/blob/5.17/master/linux-liquorix/debian/templates/control.image.in).
Removing these conflicts flags should fix the problem, as the module works like a charm with Liquorix anyways!

**Comment by damentz** [comment]
Wow, good catch!  I sync from Debian and Siduction's kernel packages at least once a year, but sometimes customizations in their packages sneak up and cause issues like this.  I'll remove the conflicts and push out a new update.

**Comment by Conobi** [comment]
I can confirm that `r8168-dkms` now works successfully on `5.17`, great job!
**Note:** *(for any user of r8168 module)* `8.049` version of `r8168` doesn't compile, you need to download [`8.050` package available for kinetic](https://packages.ubuntu.com/kinetic/r8168-dkms).

**Comment by real-F-00** [comment]
it seems that the module stopped working altogether, i'm currently using Arch Linux with liquorix version `6.3.3-lqx1-1-lqx` (compiled from https://aur.archlinux.org/packages/linux-lqx), the module simply refuses to load saying

> invalid paramaters

(tried with both `modprobe` and `insmod`)

what could've broken the compatibility? i have never installed a prior version of liquorix so i don't know if it's the DKMS module itself or liquorix that is causing the issue.
