### ISSUE TITLE
No i2c devices detected on kernel 5.18.0-9.1-liquorix-amd64

### ISSUE THREAD

**Issue by TechdudeGames** [damentz/liquorix-package#99]
OS: Ubuntu 22.04
CPU: i5 8400
Kernel: 5.18.0-9.1-liquorix-amd64

Issue: 
i2c devices are no longer being detected on the latest Liquorix kernel. i2cdetect isn't able to find any devices, and when booting a Ubuntu provided kernel i2cdetect functions correctly. I don't know what might be causing this, but I thought I should open an issue and let you know.

**Comment by damentz** [comment]
Hmm, does anything change if you pass `acpi_enforce_resources=lax` into your kernel boot parameters?

The only other major change is I re-enabled GCC -O3 optimization into Liquorix.  There's a small possibility actual code execution has been optimized out.

**Comment by TechdudeGames** [comment]
I tried passing `acpi_enforce_resources=lax` and it doesn't seem to have an effect. I think you might be right about the -O3 since i2cdetect was working about a week ago before the commit to reenable -O3 applied.

**Comment by TechdudeGames** [comment]
Switching a kernel where i2cdetect works and the Liquorix kernel it looks like the only difference is that on Liquorix `/proc/bus/i2c` doesn't exist.
strace of Liqorix:

> execve("/usr/sbin/i2cdetect", ["i2cdetect", "-l"], 0x7ffcf94ba578 /* 16 vars */) = 0
brk(NULL)                               = 0x559ef66c4000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffc97d7bdf0) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1ebfa90000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=168345, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 168345, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f1ebfa66000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libi2c.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=14376, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 16448, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1ebfa61000
mmap(0x7f1ebfa62000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f1ebfa62000
mmap(0x7f1ebfa63000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f1ebfa63000
mmap(0x7f1ebfa64000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f1ebfa64000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\237\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 48, 848) = 48
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\211\303\313\205\371\345PFwdq\376\320^\304A"..., 68, 896) = 68
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2216304, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 2260560, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1ebf800000
mmap(0x7f1ebf828000, 1658880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7f1ebf828000
mmap(0x7f1ebf9bd000, 360448, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7f1ebf9bd000
mmap(0x7f1ebfa15000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x214000) = 0x7f1ebfa15000
mmap(0x7f1ebfa1b000, 52816, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1ebfa1b000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1ebfa5e000
arch_prctl(ARCH_SET_FS, 0x7f1ebfa5e740) = 0
set_tid_address(0x7f1ebfa5ea10)         = 6037
set_robust_list(0x7f1ebfa5ea20, 24)     = 0
rseq(0x7f1ebfa5f0e0, 0x20, 0, 0x53053053) = 0
mprotect(0x7f1ebfa15000, 16384, PROT_READ) = 0
mprotect(0x7f1ebfa64000, 4096, PROT_READ) = 0
mprotect(0x559ef599c000, 4096, PROT_READ) = 0
mprotect(0x7f1ebfaca000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f1ebfa66000, 168345)          = 0
getrandom("\xed\x56\xab\xbd\x92\xc8\x65\xa5", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x559ef66c4000
brk(0x559ef66e5000)                     = 0x559ef66e5000
openat(AT_FDCWD, "/proc/bus/i2c", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/mounts", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_EMPTY_PATH) = 0
read(3, "sysfs /sys sysfs rw,nosuid,nodev"..., 1024) = 1024
close(3)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
exit_group(0)                           = ?
+++ exited with 0 +++

strace on generic kernel:

> execve("/usr/sbin/i2cdetect", ["i2cdetect", "-l"], 0x7fff6166ac28 /* 16 vars */) = 0
brk(NULL)                               = 0x55a1a460e000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffda907eea0) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f09b739e000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=168345, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 168345, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f09b7374000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libi2c.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=14376, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 16448, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f09b736f000
mmap(0x7f09b7370000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f09b7370000
mmap(0x7f09b7371000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f09b7371000
mmap(0x7f09b7372000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f09b7372000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\237\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 48, 848) = 48
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\211\303\313\205\371\345PFwdq\376\320^\304A"..., 68, 896) = 68
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2216304, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 2260560, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f09b7000000
mmap(0x7f09b7028000, 1658880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7f09b7028000
mmap(0x7f09b71bd000, 360448, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7f09b71bd000
mmap(0x7f09b7215000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x214000) = 0x7f09b7215000
mmap(0x7f09b721b000, 52816, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f09b721b000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f09b736c000
arch_prctl(ARCH_SET_FS, 0x7f09b736c740) = 0
set_tid_address(0x7f09b736ca10)         = 5887
set_robust_list(0x7f09b736ca20, 24)     = 0
rseq(0x7f09b736d0e0, 0x20, 0, 0x53053053) = 0
mprotect(0x7f09b7215000, 16384, PROT_READ) = 0
mprotect(0x7f09b7372000, 4096, PROT_READ) = 0
mprotect(0x55a1a3565000, 4096, PROT_READ) = 0
mprotect(0x7f09b73d8000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f09b7374000, 168345)          = 0
getrandom("\xd2\xc7\x33\xf6\xf9\x01\x27\x10", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x55a1a460e000
brk(0x55a1a462f000)                     = 0x55a1a462f000
openat(AT_FDCWD, "/proc/bus/i2c", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/mounts", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_EMPTY_PATH) = 0
read(3, "sysfs /sys sysfs rw,nosuid,nodev"..., 1024) = 1024
close(3)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
newfstatat(3, "", {st_mode=S_IFDIR|0755, st_size=0, ...}, AT_EMPTY_PATH) = 0
getdents64(3, 0x55a1a460e9d0 /* 11 entries */, 32768) = 336
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-3/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "NVIDIA i2c adapter 2 at 1:00.0\n", 4096) = 31
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/3", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-3", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-1/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "NVIDIA GPU I2C adapter\n", 4096) = 23
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/1", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-1", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-8/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "SMBus NCT67xx adapter at 0b00\n", 4096) = 30
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/8", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-8", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-6/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "NVIDIA i2c adapter 6 at 1:00.0\n", 4096) = 31
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/6", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-6", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-4/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "NVIDIA i2c adapter 3 at 1:00.0\n", 4096) = 31
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/4", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-4", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-2/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "NVIDIA i2c adapter 1 at 1:00.0\n", 4096) = 31
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/2", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-2", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-0/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "SMBus I801 adapter at efa0\n", 4096) = 27
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/0", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-0", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-7/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "NVIDIA i2c adapter 7 at 1:00.0\n", 4096) = 31
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/7", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-7", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
openat(AT_FDCWD, "/sys/class/i2c-dev/i2c-5/name", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "NVIDIA i2c adapter 5 at 1:00.0\n", 4096) = 31
close(4)                                = 0
openat(AT_FDCWD, "/dev/i2c/5", O_RDWR)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/i2c-5", O_RDWR)  = 4
ioctl(4, _IOC(_IOC_NONE, 0x7, 0x5, 0), 0x7ffda907eaa8) = 0
close(4)                                = 0
getdents64(3, 0x55a1a460e9d0 /* 0 entries */, 32768) = 0
close(3)                                = 0
newfstatat(1, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x1), ...}, AT_EMPTY_PATH) = 0
write(1, "i2c-0\tsmbus     \tSMBus I801 adap"..., 64) = 64
write(1, "i2c-1\ti2c       \tNVIDIA GPU I2C "..., 62) = 62
write(1, "i2c-2\ti2c       \tNVIDIA i2c adap"..., 62) = 62
write(1, "i2c-3\ti2c       \tNVIDIA i2c adap"..., 62) = 62
write(1, "i2c-4\ti2c       \tNVIDIA i2c adap"..., 62) = 62
write(1, "i2c-5\ti2c       \tNVIDIA i2c adap"..., 62) = 62
write(1, "i2c-6\ti2c       \tNVIDIA i2c adap"..., 62) = 62
write(1, "i2c-7\ti2c       \tNVIDIA i2c adap"..., 62) = 62
write(1, "i2c-8\tsmbus     \tSMBus NCT67xx a"..., 64) = 64
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by damentz** [comment]
What's the output of `lsmod | grep i2c`?  Maybe the module is just not loaded.  You can also run `sensors-detect` to discover missing modules required for `sensors` to work.

On a laptop of mine:
```
$ lsmod | grep i2c
i2c_designware_platform    16384  0
i2c_designware_core    32768  1 i2c_designware_platform
i2c_i801               32768  0
i2c_smbus              16384  1 i2c_i801
i2c_hid_acpi           16384  0
i2c_hid                32768  1 i2c_hid_acpi
i2c_algo_bit           16384  1 i915
```

**Comment by damentz** [comment]
Ok, I see the issue, **i2c-dev** is no longer loaded at boot.  For what reason I don't know.  Loading **i2c-dev** creates the **/sys/class/i2c-dev** folder required by i2cdetect.  That should fix the error below:

`openat(AT_FDCWD, "/sys/class/i2c-dev", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)`

Now where you put it, you should be fine creating a file in **/etc/modules-load.d/modules.conf**.  This is where **sensors-detect** also wants to statically list modules it believes are not autoloading that it discovers through its process.

**Comment by damentz** [comment]
Closing, simply load **i2c-dev** and **i2cdetect** should work.
